/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.BridgeWalletChain;
import org.jhely.money.sdk.bridge.model.Currency;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The balance of a Bridge Wallet for a given currency
 */
@JsonPropertyOrder({
  BridgeWalletBalance.JSON_PROPERTY_BALANCE,
  BridgeWalletBalance.JSON_PROPERTY_CURRENCY,
  BridgeWalletBalance.JSON_PROPERTY_CHAIN,
  BridgeWalletBalance.JSON_PROPERTY_CONTRACT_ADDRESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BridgeWalletBalance {
  public static final String JSON_PROPERTY_BALANCE = "balance";
  @jakarta.annotation.Nonnull
  private String balance;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private Currency currency;

  public static final String JSON_PROPERTY_CHAIN = "chain";
  @jakarta.annotation.Nonnull
  private BridgeWalletChain chain;

  public static final String JSON_PROPERTY_CONTRACT_ADDRESS = "contract_address";
  @jakarta.annotation.Nullable
  private String contractAddress;

  public BridgeWalletBalance() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public BridgeWalletBalance(
    @JsonProperty(JSON_PROPERTY_BALANCE) String balance, 
    @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS) String contractAddress
  ) {
    this();
    this.balance = balance;
    this.contractAddress = contractAddress;
  }

  /**
   * The balance in the given currency. ex. \&quot;10.95\&quot;
   * @return balance
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BALANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBalance() {
    return balance;
  }



  public BridgeWalletBalance currency(@jakarta.annotation.Nonnull Currency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Currency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull Currency currency) {
    this.currency = currency;
  }

  public BridgeWalletBalance chain(@jakarta.annotation.Nonnull BridgeWalletChain chain) {
    
    this.chain = chain;
    return this;
  }

  /**
   * Get chain
   * @return chain
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BridgeWalletChain getChain() {
    return chain;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(@jakarta.annotation.Nonnull BridgeWalletChain chain) {
    this.chain = chain;
  }

  /**
   * The contract address of the currency, or null if it is a native currency
   * @return contractAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTRACT_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContractAddress() {
    return contractAddress;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BridgeWalletBalance bridgeWalletBalance = (BridgeWalletBalance) o;
    return Objects.equals(this.balance, bridgeWalletBalance.balance) &&
        Objects.equals(this.currency, bridgeWalletBalance.currency) &&
        Objects.equals(this.chain, bridgeWalletBalance.chain) &&
        Objects.equals(this.contractAddress, bridgeWalletBalance.contractAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance, currency, chain, contractAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BridgeWalletBalance {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

