/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Gets or Sets BridgeWalletSepaSwiftInclusivePaymentRail
 */
public enum BridgeWalletSepaSwiftInclusivePaymentRail {
  
  ACH("ach"),
  
  WIRE("wire"),
  
  ACH_PUSH("ach_push"),
  
  ACH_SAME_DAY("ach_same_day"),
  
  ARBITRUM("arbitrum"),
  
  AVALANCHE_C_CHAIN("avalanche_c_chain"),
  
  BASE("base"),
  
  BRIDGE_WALLET("bridge_wallet"),
  
  ETHEREUM("ethereum"),
  
  OPTIMISM("optimism"),
  
  POLYGON("polygon"),
  
  SEPA("sepa"),
  
  SOLANA("solana"),
  
  SPEI("spei"),
  
  STELLAR("stellar"),
  
  SWIFT("swift"),
  
  TRON("tron");

  private String value;

  BridgeWalletSepaSwiftInclusivePaymentRail(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BridgeWalletSepaSwiftInclusivePaymentRail fromValue(String value) {
    for (BridgeWalletSepaSwiftInclusivePaymentRail b : BridgeWalletSepaSwiftInclusivePaymentRail.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

