/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BusinessDocumentsInner
 */
@JsonPropertyOrder({
  BusinessDocumentsInner.JSON_PROPERTY_PURPOSES,
  BusinessDocumentsInner.JSON_PROPERTY_FILE,
  BusinessDocumentsInner.JSON_PROPERTY_DESCRIPTION
})
@JsonTypeName("BusinessDocuments_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BusinessDocumentsInner {
  /**
   * Gets or Sets purposes
   */
  public enum PurposesEnum {
    AML_COMFORT_LETTER(String.valueOf("aml_comfort_letter")),
    
    BUSINESS_FORMATION(String.valueOf("business_formation")),
    
    DIRECTORS_REGISTRY(String.valueOf("directors_registry")),
    
    E_SIGNATURE_CERTIFICATE(String.valueOf("e_signature_certificate")),
    
    EVIDENCE_OF_GOOD_STANDING(String.valueOf("evidence_of_good_standing")),
    
    FLOW_OF_FUNDS(String.valueOf("flow_of_funds")),
    
    MARKETING_MATERIALS(String.valueOf("marketing_materials")),
    
    OWNERSHIP_CHART(String.valueOf("ownership_chart")),
    
    OWNERSHIP_INFORMATION(String.valueOf("ownership_information")),
    
    PROOF_OF_ACCOUNT_PURPOSE(String.valueOf("proof_of_account_purpose")),
    
    PROOF_OF_ADDRESS(String.valueOf("proof_of_address")),
    
    PROOF_OF_ENTITY_NAME_CHANGE(String.valueOf("proof_of_entity_name_change")),
    
    PROOF_OF_NATURE_OF_BUSINESS(String.valueOf("proof_of_nature_of_business")),
    
    PROOF_OF_SIGNATORY_AUTHORITY(String.valueOf("proof_of_signatory_authority")),
    
    PROOF_OF_SOURCE_OF_FUNDS(String.valueOf("proof_of_source_of_funds")),
    
    PROOF_OF_SOURCE_OF_WEALTH(String.valueOf("proof_of_source_of_wealth")),
    
    PROOF_OF_TAX_IDENTIFICATION(String.valueOf("proof_of_tax_identification")),
    
    SHAREHOLDER_REGISTER(String.valueOf("shareholder_register")),
    
    OTHER(String.valueOf("other"));

    private String value;

    PurposesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PurposesEnum fromValue(String value) {
      for (PurposesEnum b : PurposesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PURPOSES = "purposes";
  @jakarta.annotation.Nonnull
  private List<PurposesEnum> purposes = new ArrayList<>();

  public static final String JSON_PROPERTY_FILE = "file";
  @jakarta.annotation.Nonnull
  private String _file;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public BusinessDocumentsInner() {
  }

  public BusinessDocumentsInner purposes(@jakarta.annotation.Nonnull List<PurposesEnum> purposes) {
    
    this.purposes = purposes;
    return this;
  }

  public BusinessDocumentsInner addPurposesItem(PurposesEnum purposesItem) {
    if (this.purposes == null) {
      this.purposes = new ArrayList<>();
    }
    this.purposes.add(purposesItem);
    return this;
  }

  /**
   * A list of purposes that the given document serves. Click \&quot;ADD STRING\&quot; to see common document purposes for businesses, or view the full list of possible values [here](https://apidocs.bridge.xyz/docs/supported-documents).  &#x60;business_formation&#x60; and &#x60;ownership_information&#x60; documents are required for businesses. 
   * @return purposes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PURPOSES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PurposesEnum> getPurposes() {
    return purposes;
  }


  @JsonProperty(value = JSON_PROPERTY_PURPOSES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPurposes(@jakarta.annotation.Nonnull List<PurposesEnum> purposes) {
    this.purposes = purposes;
  }

  public BusinessDocumentsInner _file(@jakarta.annotation.Nonnull String _file) {
    
    this._file = _file;
    return this;
  }

  /**
   * Base64 encoded image of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px   *Maximum File Size: 24MB  *Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif
   * @return _file
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFile() {
    return _file;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFile(@jakarta.annotation.Nonnull String _file) {
    this._file = _file;
  }

  public BusinessDocumentsInner description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A description describing the provided document. This field is required when &#x60;other&#x60; is provided as one of the purposes.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessDocumentsInner businessDocumentsInner = (BusinessDocumentsInner) o;
    return Objects.equals(this.purposes, businessDocumentsInner.purposes) &&
        Objects.equals(this._file, businessDocumentsInner._file) &&
        Objects.equals(this.description, businessDocumentsInner.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(purposes, _file, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessDocumentsInner {\n");
    sb.append("    purposes: ").append(toIndentedString(purposes)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

