/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CardAuthorizationDetails;
import org.jhely.money.sdk.bridge.model.CardAuthorizationVerificationData;
import org.jhely.money.sdk.bridge.model.CardLocalTransactionDetails;
import org.jhely.money.sdk.bridge.model.FiatCurrency;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A pending card authorization
 */
@JsonPropertyOrder({
  CardAuthorization.JSON_PROPERTY_ID,
  CardAuthorization.JSON_PROPERTY_AMOUNT,
  CardAuthorization.JSON_PROPERTY_BILLING_AMOUNT,
  CardAuthorization.JSON_PROPERTY_CURRENCY,
  CardAuthorization.JSON_PROPERTY_MERCHANT_CATEGORY_CODE,
  CardAuthorization.JSON_PROPERTY_DESCRIPTION,
  CardAuthorization.JSON_PROPERTY_AUTHORIZED_AT,
  CardAuthorization.JSON_PROPERTY_DETAILS,
  CardAuthorization.JSON_PROPERTY_LOCAL_TRANSACTION_DETAILS,
  CardAuthorization.JSON_PROPERTY_VERIFICATION_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CardAuthorization {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_BILLING_AMOUNT = "billing_amount";
  @jakarta.annotation.Nullable
  private String billingAmount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private FiatCurrency currency;

  public static final String JSON_PROPERTY_MERCHANT_CATEGORY_CODE = "merchant_category_code";
  @jakarta.annotation.Nonnull
  private String merchantCategoryCode;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_AUTHORIZED_AT = "authorized_at";
  @jakarta.annotation.Nonnull
  private String authorizedAt;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @jakarta.annotation.Nonnull
  private CardAuthorizationDetails details;

  public static final String JSON_PROPERTY_LOCAL_TRANSACTION_DETAILS = "local_transaction_details";
  @jakarta.annotation.Nullable
  private CardLocalTransactionDetails localTransactionDetails;

  public static final String JSON_PROPERTY_VERIFICATION_DATA = "verification_data";
  @jakarta.annotation.Nullable
  private CardAuthorizationVerificationData verificationData;

  public CardAuthorization() {
  }

  public CardAuthorization id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public CardAuthorization amount(@jakarta.annotation.Nonnull String amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * The amount represented as a decimal string
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }

  public CardAuthorization billingAmount(@jakarta.annotation.Nullable String billingAmount) {
    
    this.billingAmount = billingAmount;
    return this;
  }

  /**
   * The billing amount, represented as a decimal string. The billing amount is the amount of the transaction excluding any additional hold. This amount should be present on all purchases, but will only differ from the amount field for some merchant categories in which an upcharge is involved (e.g. gas stations, hotels).
   * @return billingAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BILLING_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBillingAmount() {
    return billingAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_BILLING_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingAmount(@jakarta.annotation.Nullable String billingAmount) {
    this.billingAmount = billingAmount;
  }

  public CardAuthorization currency(@jakarta.annotation.Nonnull FiatCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FiatCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull FiatCurrency currency) {
    this.currency = currency;
  }

  public CardAuthorization merchantCategoryCode(@jakarta.annotation.Nonnull String merchantCategoryCode) {
    
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

  /**
   * A merchant category code for card transactions (e.g., &#39;5712&#39;)
   * @return merchantCategoryCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MERCHANT_CATEGORY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantCategoryCode() {
    return merchantCategoryCode;
  }


  @JsonProperty(value = JSON_PROPERTY_MERCHANT_CATEGORY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantCategoryCode(@jakarta.annotation.Nonnull String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }

  public CardAuthorization description(@jakarta.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A description of the card transaction, including the merchant&#39;s name and location information
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }

  public CardAuthorization authorizedAt(@jakarta.annotation.Nonnull String authorizedAt) {
    
    this.authorizedAt = authorizedAt;
    return this;
  }

  /**
   * Timestamp when the card transaction was authorized, in ISO8601 format
   * @return authorizedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuthorizedAt() {
    return authorizedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorizedAt(@jakarta.annotation.Nonnull String authorizedAt) {
    this.authorizedAt = authorizedAt;
  }

  public CardAuthorization details(@jakarta.annotation.Nonnull CardAuthorizationDetails details) {
    
    this.details = details;
    return this;
  }

  /**
   * Get details
   * @return details
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CardAuthorizationDetails getDetails() {
    return details;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetails(@jakarta.annotation.Nonnull CardAuthorizationDetails details) {
    this.details = details;
  }

  public CardAuthorization localTransactionDetails(@jakarta.annotation.Nullable CardLocalTransactionDetails localTransactionDetails) {
    
    this.localTransactionDetails = localTransactionDetails;
    return this;
  }

  /**
   * Get localTransactionDetails
   * @return localTransactionDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCAL_TRANSACTION_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardLocalTransactionDetails getLocalTransactionDetails() {
    return localTransactionDetails;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCAL_TRANSACTION_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalTransactionDetails(@jakarta.annotation.Nullable CardLocalTransactionDetails localTransactionDetails) {
    this.localTransactionDetails = localTransactionDetails;
  }

  public CardAuthorization verificationData(@jakarta.annotation.Nullable CardAuthorizationVerificationData verificationData) {
    
    this.verificationData = verificationData;
    return this;
  }

  /**
   * Get verificationData
   * @return verificationData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardAuthorizationVerificationData getVerificationData() {
    return verificationData;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerificationData(@jakarta.annotation.Nullable CardAuthorizationVerificationData verificationData) {
    this.verificationData = verificationData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardAuthorization cardAuthorization = (CardAuthorization) o;
    return Objects.equals(this.id, cardAuthorization.id) &&
        Objects.equals(this.amount, cardAuthorization.amount) &&
        Objects.equals(this.billingAmount, cardAuthorization.billingAmount) &&
        Objects.equals(this.currency, cardAuthorization.currency) &&
        Objects.equals(this.merchantCategoryCode, cardAuthorization.merchantCategoryCode) &&
        Objects.equals(this.description, cardAuthorization.description) &&
        Objects.equals(this.authorizedAt, cardAuthorization.authorizedAt) &&
        Objects.equals(this.details, cardAuthorization.details) &&
        Objects.equals(this.localTransactionDetails, cardAuthorization.localTransactionDetails) &&
        Objects.equals(this.verificationData, cardAuthorization.verificationData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, amount, billingAmount, currency, merchantCategoryCode, description, authorizedAt, details, localTransactionDetails, verificationData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardAuthorization {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    billingAmount: ").append(toIndentedString(billingAmount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    authorizedAt: ").append(toIndentedString(authorizedAt)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    localTransactionDetails: ").append(toIndentedString(localTransactionDetails)).append("\n");
    sb.append("    verificationData: ").append(toIndentedString(verificationData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

