/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CardAuthorizationDetails
 */
@JsonPropertyOrder({
  CardAuthorizationDetails.JSON_PROPERTY_VENDOR_AUTH_ID
})
@JsonTypeName("CardAuthorization_details")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CardAuthorizationDetails {
  public static final String JSON_PROPERTY_VENDOR_AUTH_ID = "vendor_auth_id";
  @jakarta.annotation.Nullable
  private String vendorAuthId;

  public CardAuthorizationDetails() {
  }

  public CardAuthorizationDetails vendorAuthId(@jakarta.annotation.Nullable String vendorAuthId) {
    
    this.vendorAuthId = vendorAuthId;
    return this;
  }

  /**
   * ID in the vendor system used to identify this authorized card transaction
   * @return vendorAuthId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VENDOR_AUTH_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVendorAuthId() {
    return vendorAuthId;
  }


  @JsonProperty(value = JSON_PROPERTY_VENDOR_AUTH_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVendorAuthId(@jakarta.annotation.Nullable String vendorAuthId) {
    this.vendorAuthId = vendorAuthId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardAuthorizationDetails cardAuthorizationDetails = (CardAuthorizationDetails) o;
    return Objects.equals(this.vendorAuthId, cardAuthorizationDetails.vendorAuthId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vendorAuthId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardAuthorizationDetails {\n");
    sb.append("    vendorAuthId: ").append(toIndentedString(vendorAuthId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

