/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CardPushProvisioningResponseApplePay;
import org.jhely.money.sdk.bridge.model.CardPushProvisioningResponseGooglePay;
import org.jhely.money.sdk.bridge.model.CardWalletProvider;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The mobile wallet push provisioning response
 */
@JsonPropertyOrder({
  CardPushProvisioningResponse.JSON_PROPERTY_WALLET_PROVIDER,
  CardPushProvisioningResponse.JSON_PROPERTY_APPLE_PAY,
  CardPushProvisioningResponse.JSON_PROPERTY_GOOGLE_PAY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CardPushProvisioningResponse {
  public static final String JSON_PROPERTY_WALLET_PROVIDER = "wallet_provider";
  @jakarta.annotation.Nullable
  private CardWalletProvider walletProvider;

  public static final String JSON_PROPERTY_APPLE_PAY = "apple_pay";
  @jakarta.annotation.Nullable
  private CardPushProvisioningResponseApplePay applePay;

  public static final String JSON_PROPERTY_GOOGLE_PAY = "google_pay";
  @jakarta.annotation.Nullable
  private CardPushProvisioningResponseGooglePay googlePay;

  public CardPushProvisioningResponse() {
  }

  public CardPushProvisioningResponse walletProvider(@jakarta.annotation.Nullable CardWalletProvider walletProvider) {
    
    this.walletProvider = walletProvider;
    return this;
  }

  /**
   * The wallet provider of the push provisioning request
   * @return walletProvider
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WALLET_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardWalletProvider getWalletProvider() {
    return walletProvider;
  }


  @JsonProperty(value = JSON_PROPERTY_WALLET_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletProvider(@jakarta.annotation.Nullable CardWalletProvider walletProvider) {
    this.walletProvider = walletProvider;
  }

  public CardPushProvisioningResponse applePay(@jakarta.annotation.Nullable CardPushProvisioningResponseApplePay applePay) {
    
    this.applePay = applePay;
    return this;
  }

  /**
   * Get applePay
   * @return applePay
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APPLE_PAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardPushProvisioningResponseApplePay getApplePay() {
    return applePay;
  }


  @JsonProperty(value = JSON_PROPERTY_APPLE_PAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplePay(@jakarta.annotation.Nullable CardPushProvisioningResponseApplePay applePay) {
    this.applePay = applePay;
  }

  public CardPushProvisioningResponse googlePay(@jakarta.annotation.Nullable CardPushProvisioningResponseGooglePay googlePay) {
    
    this.googlePay = googlePay;
    return this;
  }

  /**
   * Get googlePay
   * @return googlePay
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GOOGLE_PAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardPushProvisioningResponseGooglePay getGooglePay() {
    return googlePay;
  }


  @JsonProperty(value = JSON_PROPERTY_GOOGLE_PAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGooglePay(@jakarta.annotation.Nullable CardPushProvisioningResponseGooglePay googlePay) {
    this.googlePay = googlePay;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardPushProvisioningResponse cardPushProvisioningResponse = (CardPushProvisioningResponse) o;
    return Objects.equals(this.walletProvider, cardPushProvisioningResponse.walletProvider) &&
        Objects.equals(this.applePay, cardPushProvisioningResponse.applePay) &&
        Objects.equals(this.googlePay, cardPushProvisioningResponse.googlePay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletProvider, applePay, googlePay);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardPushProvisioningResponse {\n");
    sb.append("    walletProvider: ").append(toIndentedString(walletProvider)).append("\n");
    sb.append("    applePay: ").append(toIndentedString(applePay)).append("\n");
    sb.append("    googlePay: ").append(toIndentedString(googlePay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

