/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jhely.money.sdk.bridge.model.EndorsementType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateKycLinks
 */
@JsonPropertyOrder({
  CreateKycLinks.JSON_PROPERTY_FULL_NAME,
  CreateKycLinks.JSON_PROPERTY_EMAIL,
  CreateKycLinks.JSON_PROPERTY_TYPE,
  CreateKycLinks.JSON_PROPERTY_ENDORSEMENTS,
  CreateKycLinks.JSON_PROPERTY_REDIRECT_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateKycLinks {
  public static final String JSON_PROPERTY_FULL_NAME = "full_name";
  @jakarta.annotation.Nullable
  private String fullName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nonnull
  private String email;

  /**
   * Type of the customer (individual vs. business)
   */
  public enum TypeEnum {
    INDIVIDUAL(String.valueOf("individual")),
    
    BUSINESS(String.valueOf("business"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_ENDORSEMENTS = "endorsements";
  @jakarta.annotation.Nullable
  private List<EndorsementType> endorsements = new ArrayList<>();

  public static final String JSON_PROPERTY_REDIRECT_URI = "redirect_uri";
  @jakarta.annotation.Nullable
  private String redirectUri;

  public CreateKycLinks() {
  }

  public CreateKycLinks fullName(@jakarta.annotation.Nullable String fullName) {
    
    this.fullName = fullName;
    return this;
  }

  /**
   * Full name of the customer, for a business, this would be the business entity&#39;s legal name
   * @return fullName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(@jakarta.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }

  public CreateKycLinks email(@jakarta.annotation.Nonnull String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Email of the customer
   * @return email
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@jakarta.annotation.Nonnull String email) {
    this.email = email;
  }

  public CreateKycLinks type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Type of the customer (individual vs. business)
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public CreateKycLinks endorsements(@jakarta.annotation.Nullable List<EndorsementType> endorsements) {
    
    this.endorsements = endorsements;
    return this;
  }

  public CreateKycLinks addEndorsementsItem(EndorsementType endorsementsItem) {
    if (this.endorsements == null) {
      this.endorsements = new ArrayList<>();
    }
    this.endorsements.add(endorsementsItem);
    return this;
  }

  /**
   * List of endorsements to request for the generated KYC link. For example, &#x60;sepa&#x60; endorsement could be requested to allow an &#x60;individual&#x60; customer to submit &#x60;proof-of-address&#x60; documents in the KYC flow.
   * @return endorsements
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDORSEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EndorsementType> getEndorsements() {
    return endorsements;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDORSEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndorsements(@jakarta.annotation.Nullable List<EndorsementType> endorsements) {
    this.endorsements = endorsements;
  }

  public CreateKycLinks redirectUri(@jakarta.annotation.Nullable String redirectUri) {
    
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * The location where the customer should be redirected after completing the KYC flow. Must be in the form of http:// or https://.
   * @return redirectUri
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectUri(@jakarta.annotation.Nullable String redirectUri) {
    this.redirectUri = redirectUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateKycLinks createKycLinks = (CreateKycLinks) o;
    return Objects.equals(this.fullName, createKycLinks.fullName) &&
        Objects.equals(this.email, createKycLinks.email) &&
        Objects.equals(this.type, createKycLinks.type) &&
        Objects.equals(this.endorsements, createKycLinks.endorsements) &&
        Objects.equals(this.redirectUri, createKycLinks.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, email, type, endorsements, redirectUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateKycLinks {\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    endorsements: ").append(toIndentedString(endorsements)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

