/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.BridgeWalletChain;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateBridgeWallet
 */
@JsonPropertyOrder({
  CreateBridgeWallet.JSON_PROPERTY_CHAIN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateBridgeWallet {
  public static final String JSON_PROPERTY_CHAIN = "chain";
  @jakarta.annotation.Nonnull
  private BridgeWalletChain chain;

  public CreateBridgeWallet() {
  }

  public CreateBridgeWallet chain(@jakarta.annotation.Nonnull BridgeWalletChain chain) {
    
    this.chain = chain;
    return this;
  }

  /**
   * Get chain
   * @return chain
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BridgeWalletChain getChain() {
    return chain;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(@jakarta.annotation.Nonnull BridgeWalletChain chain) {
    this.chain = chain;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBridgeWallet createBridgeWallet = (CreateBridgeWallet) o;
    return Objects.equals(this.chain, createBridgeWallet.chain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chain);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBridgeWallet {\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

