/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.jhely.money.sdk.bridge.model.StaticMemoDestination;
import org.jhely.money.sdk.bridge.model.StaticMemoSourceInput;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateStaticMemo
 */
@JsonPropertyOrder({
  CreateStaticMemo.JSON_PROPERTY_DEVELOPER_FEE_PERCENT,
  CreateStaticMemo.JSON_PROPERTY_SOURCE,
  CreateStaticMemo.JSON_PROPERTY_DESTINATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateStaticMemo {
  public static final String JSON_PROPERTY_DEVELOPER_FEE_PERCENT = "developer_fee_percent";
  @jakarta.annotation.Nullable
  private BigDecimal developerFeePercent;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull
  private StaticMemoSourceInput source;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nonnull
  private StaticMemoDestination destination;

  public CreateStaticMemo() {
  }

  public CreateStaticMemo developerFeePercent(@jakarta.annotation.Nullable BigDecimal developerFeePercent) {
    
    this.developerFeePercent = developerFeePercent;
    return this;
  }

  /**
   * The developer fee percent that will be applied to this Virtual Account. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
   * minimum: 0
   * maximum: 100
   * @return developerFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDeveloperFeePercent() {
    return developerFeePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal developerFeePercent) {
    this.developerFeePercent = developerFeePercent;
  }

  public CreateStaticMemo source(@jakarta.annotation.Nonnull StaticMemoSourceInput source) {
    
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StaticMemoSourceInput getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull StaticMemoSourceInput source) {
    this.source = source;
  }

  public CreateStaticMemo destination(@jakarta.annotation.Nonnull StaticMemoDestination destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StaticMemoDestination getDestination() {
    return destination;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(@jakarta.annotation.Nonnull StaticMemoDestination destination) {
    this.destination = destination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateStaticMemo createStaticMemo = (CreateStaticMemo) o;
    return Objects.equals(this.developerFeePercent, createStaticMemo.developerFeePercent) &&
        Objects.equals(this.source, createStaticMemo.source) &&
        Objects.equals(this.destination, createStaticMemo.destination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(developerFeePercent, source, destination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateStaticMemo {\n");
    sb.append("    developerFeePercent: ").append(toIndentedString(developerFeePercent)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

