/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.jhely.money.sdk.bridge.model.LiquidationAddressSourceChain;
import org.jhely.money.sdk.bridge.model.LiquidationAddressSourceCurrency;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateLiquidationAddressResponse
 */
@JsonPropertyOrder({
  CreateLiquidationAddressResponse.JSON_PROPERTY_CURRENCY,
  CreateLiquidationAddressResponse.JSON_PROPERTY_CHAIN,
  CreateLiquidationAddressResponse.JSON_PROPERTY_EXTERNAL_ACCOUNT_ID,
  CreateLiquidationAddressResponse.JSON_PROPERTY_PREFUNDED_ACCOUNT_ID,
  CreateLiquidationAddressResponse.JSON_PROPERTY_BRIDGE_WALLET_ID,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_WIRE_MESSAGE,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_SEPA_REFERENCE,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_ACH_REFERENCE,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_SPEI_REFERENCE,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_REFERENCE,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_PAYMENT_RAIL,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_CURRENCY,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_ADDRESS,
  CreateLiquidationAddressResponse.JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO,
  CreateLiquidationAddressResponse.JSON_PROPERTY_RETURN_ADDRESS,
  CreateLiquidationAddressResponse.JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT,
  CreateLiquidationAddressResponse.JSON_PROPERTY_ADDRESS,
  CreateLiquidationAddressResponse.JSON_PROPERTY_STATE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateLiquidationAddressResponse {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private LiquidationAddressSourceCurrency currency;

  public static final String JSON_PROPERTY_CHAIN = "chain";
  @jakarta.annotation.Nonnull
  private LiquidationAddressSourceChain chain;

  public static final String JSON_PROPERTY_EXTERNAL_ACCOUNT_ID = "external_account_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> externalAccountId = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_PREFUNDED_ACCOUNT_ID = "prefunded_account_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> prefundedAccountId = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_BRIDGE_WALLET_ID = "bridge_wallet_id";
  @jakarta.annotation.Nullable
  private String bridgeWalletId;

  public static final String JSON_PROPERTY_DESTINATION_WIRE_MESSAGE = "destination_wire_message";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> destinationWireMessage = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_DESTINATION_SEPA_REFERENCE = "destination_sepa_reference";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> destinationSepaReference = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_DESTINATION_ACH_REFERENCE = "destination_ach_reference";
  @jakarta.annotation.Nullable
  private String destinationAchReference;

  public static final String JSON_PROPERTY_DESTINATION_SPEI_REFERENCE = "destination_spei_reference";
  @jakarta.annotation.Nullable
  private String destinationSpeiReference;

  public static final String JSON_PROPERTY_DESTINATION_REFERENCE = "destination_reference";
  @jakarta.annotation.Nullable
  private String destinationReference;

  public static final String JSON_PROPERTY_DESTINATION_PAYMENT_RAIL = "destination_payment_rail";
  @jakarta.annotation.Nullable
  private Object destinationPaymentRail = null;

  public static final String JSON_PROPERTY_DESTINATION_CURRENCY = "destination_currency";
  @jakarta.annotation.Nullable
  private Object destinationCurrency = null;

  public static final String JSON_PROPERTY_DESTINATION_ADDRESS = "destination_address";
  @jakarta.annotation.Nullable
  private String destinationAddress;

  public static final String JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO = "destination_blockchain_memo";
  @jakarta.annotation.Nullable
  private String destinationBlockchainMemo;

  public static final String JSON_PROPERTY_RETURN_ADDRESS = "return_address";
  @jakarta.annotation.Nullable
  private String returnAddress;

  public static final String JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT = "custom_developer_fee_percent";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> customDeveloperFeePercent = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public CreateLiquidationAddressResponse() {
  }

  public CreateLiquidationAddressResponse currency(@jakarta.annotation.Nonnull LiquidationAddressSourceCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LiquidationAddressSourceCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull LiquidationAddressSourceCurrency currency) {
    this.currency = currency;
  }

  public CreateLiquidationAddressResponse chain(@jakarta.annotation.Nonnull LiquidationAddressSourceChain chain) {
    
    this.chain = chain;
    return this;
  }

  /**
   * Get chain
   * @return chain
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LiquidationAddressSourceChain getChain() {
    return chain;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(@jakarta.annotation.Nonnull LiquidationAddressSourceChain chain) {
    this.chain = chain;
  }

  public CreateLiquidationAddressResponse externalAccountId(@jakarta.annotation.Nullable Object externalAccountId) {
    this.externalAccountId = JsonNullable.<Object>of(externalAccountId);
    
    return this;
  }

  /**
   * External bank account to which Bridge will send the funds.
   * @return externalAccountId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getExternalAccountId() {
        return externalAccountId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getExternalAccountId_JsonNullable() {
    return externalAccountId;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ACCOUNT_ID)
  public void setExternalAccountId_JsonNullable(JsonNullable<Object> externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public void setExternalAccountId(@jakarta.annotation.Nullable Object externalAccountId) {
    this.externalAccountId = JsonNullable.<Object>of(externalAccountId);
  }

  public CreateLiquidationAddressResponse prefundedAccountId(@jakarta.annotation.Nullable Object prefundedAccountId) {
    this.prefundedAccountId = JsonNullable.<Object>of(prefundedAccountId);
    
    return this;
  }

  /**
   * The developer&#39;s prefunded account to which Bridge will send the funds.
   * @return prefundedAccountId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getPrefundedAccountId() {
        return prefundedAccountId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PREFUNDED_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getPrefundedAccountId_JsonNullable() {
    return prefundedAccountId;
  }
  
  @JsonProperty(JSON_PROPERTY_PREFUNDED_ACCOUNT_ID)
  public void setPrefundedAccountId_JsonNullable(JsonNullable<Object> prefundedAccountId) {
    this.prefundedAccountId = prefundedAccountId;
  }

  public void setPrefundedAccountId(@jakarta.annotation.Nullable Object prefundedAccountId) {
    this.prefundedAccountId = JsonNullable.<Object>of(prefundedAccountId);
  }

  public CreateLiquidationAddressResponse bridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    
    this.bridgeWalletId = bridgeWalletId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return bridgeWalletId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBridgeWalletId() {
    return bridgeWalletId;
  }


  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    this.bridgeWalletId = bridgeWalletId;
  }

  public CreateLiquidationAddressResponse destinationWireMessage(@jakarta.annotation.Nullable Object destinationWireMessage) {
    this.destinationWireMessage = JsonNullable.<Object>of(destinationWireMessage);
    
    return this;
  }

  /**
   * A message to be sent with a wire transfer.
   * @return destinationWireMessage
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getDestinationWireMessage() {
        return destinationWireMessage.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESTINATION_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getDestinationWireMessage_JsonNullable() {
    return destinationWireMessage;
  }
  
  @JsonProperty(JSON_PROPERTY_DESTINATION_WIRE_MESSAGE)
  public void setDestinationWireMessage_JsonNullable(JsonNullable<Object> destinationWireMessage) {
    this.destinationWireMessage = destinationWireMessage;
  }

  public void setDestinationWireMessage(@jakarta.annotation.Nullable Object destinationWireMessage) {
    this.destinationWireMessage = JsonNullable.<Object>of(destinationWireMessage);
  }

  public CreateLiquidationAddressResponse destinationSepaReference(@jakarta.annotation.Nullable Object destinationSepaReference) {
    this.destinationSepaReference = JsonNullable.<Object>of(destinationSepaReference);
    
    return this;
  }

  /**
   * A reference message to be sent with a SEPA transaction.
   * @return destinationSepaReference
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getDestinationSepaReference() {
        return destinationSepaReference.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getDestinationSepaReference_JsonNullable() {
    return destinationSepaReference;
  }
  
  @JsonProperty(JSON_PROPERTY_DESTINATION_SEPA_REFERENCE)
  public void setDestinationSepaReference_JsonNullable(JsonNullable<Object> destinationSepaReference) {
    this.destinationSepaReference = destinationSepaReference;
  }

  public void setDestinationSepaReference(@jakarta.annotation.Nullable Object destinationSepaReference) {
    this.destinationSepaReference = JsonNullable.<Object>of(destinationSepaReference);
  }

  public CreateLiquidationAddressResponse destinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    
    this.destinationAchReference = destinationAchReference;
    return this;
  }

  /**
   * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
   * @return destinationAchReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationAchReference() {
    return destinationAchReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    this.destinationAchReference = destinationAchReference;
  }

  public CreateLiquidationAddressResponse destinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    
    this.destinationSpeiReference = destinationSpeiReference;
    return this;
  }

  /**
   * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, and space
   * @return destinationSpeiReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationSpeiReference() {
    return destinationSpeiReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    this.destinationSpeiReference = destinationSpeiReference;
  }

  public CreateLiquidationAddressResponse destinationReference(@jakarta.annotation.Nullable String destinationReference) {
    
    this.destinationReference = destinationReference;
    return this;
  }

  /**
   * A payment reference message for newer payment rails (e.g. PIX).
   * @return destinationReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationReference() {
    return destinationReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationReference(@jakarta.annotation.Nullable String destinationReference) {
    this.destinationReference = destinationReference;
  }

  public CreateLiquidationAddressResponse destinationPaymentRail(@jakarta.annotation.Nullable Object destinationPaymentRail) {
    
    this.destinationPaymentRail = destinationPaymentRail;
    return this;
  }

  /**
   * The payment rail that Bridge will use to send funds to the customer.
   * @return destinationPaymentRail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_PAYMENT_RAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getDestinationPaymentRail() {
    return destinationPaymentRail;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_PAYMENT_RAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestinationPaymentRail(@jakarta.annotation.Nullable Object destinationPaymentRail) {
    this.destinationPaymentRail = destinationPaymentRail;
  }

  public CreateLiquidationAddressResponse destinationCurrency(@jakarta.annotation.Nullable Object destinationCurrency) {
    
    this.destinationCurrency = destinationCurrency;
    return this;
  }

  /**
   * The currency that Bridge will use to send funds to the customer.
   * @return destinationCurrency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getDestinationCurrency() {
    return destinationCurrency;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestinationCurrency(@jakarta.annotation.Nullable Object destinationCurrency) {
    this.destinationCurrency = destinationCurrency;
  }

  public CreateLiquidationAddressResponse destinationAddress(@jakarta.annotation.Nullable String destinationAddress) {
    
    this.destinationAddress = destinationAddress;
    return this;
  }

  /**
   * The crypto wallet address that Bridge will use to send funds to the customer.
   * @return destinationAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationAddress() {
    return destinationAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationAddress(@jakarta.annotation.Nullable String destinationAddress) {
    this.destinationAddress = destinationAddress;
  }

  public CreateLiquidationAddressResponse destinationBlockchainMemo(@jakarta.annotation.Nullable String destinationBlockchainMemo) {
    
    this.destinationBlockchainMemo = destinationBlockchainMemo;
    return this;
  }

  /**
   * The memo to include in the transaction, for blockchains that support memos only
   * @return destinationBlockchainMemo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationBlockchainMemo() {
    return destinationBlockchainMemo;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationBlockchainMemo(@jakarta.annotation.Nullable String destinationBlockchainMemo) {
    this.destinationBlockchainMemo = destinationBlockchainMemo;
  }

  public CreateLiquidationAddressResponse returnAddress(@jakarta.annotation.Nullable String returnAddress) {
    
    this.returnAddress = returnAddress;
    return this;
  }

  /**
   * The crypto wallet address that Bridge will use to return funds to the customer in case of a failed transaction. This address must be on the same chain specified for the liquidation address. Please note, this functionality is not supported on Stellar.
   * @return returnAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnAddress() {
    return returnAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnAddress(@jakarta.annotation.Nullable String returnAddress) {
    this.returnAddress = returnAddress;
  }

  public CreateLiquidationAddressResponse customDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
    
    return this;
  }

  /**
   * The developer fee percent that will be applied to this Liquidation Address or null to use the default fee. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
   * minimum: 0
   * maximum: 100
   * @return customDeveloperFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getCustomDeveloperFeePercent() {
        return customDeveloperFeePercent.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getCustomDeveloperFeePercent_JsonNullable() {
    return customDeveloperFeePercent;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT)
  public void setCustomDeveloperFeePercent_JsonNullable(JsonNullable<BigDecimal> customDeveloperFeePercent) {
    this.customDeveloperFeePercent = customDeveloperFeePercent;
  }

  public void setCustomDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
  }

  public CreateLiquidationAddressResponse address(@jakarta.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * The blockchain address the customer will send funds to.
   * @return address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@jakarta.annotation.Nullable String address) {
    this.address = address;
  }

  public CreateLiquidationAddressResponse state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The state of the liquidation address. It could be \&quot;active\&quot; or \&quot;deactivated\&quot;
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLiquidationAddressResponse createLiquidationAddressResponse = (CreateLiquidationAddressResponse) o;
    return Objects.equals(this.currency, createLiquidationAddressResponse.currency) &&
        Objects.equals(this.chain, createLiquidationAddressResponse.chain) &&
        equalsNullable(this.externalAccountId, createLiquidationAddressResponse.externalAccountId) &&
        equalsNullable(this.prefundedAccountId, createLiquidationAddressResponse.prefundedAccountId) &&
        Objects.equals(this.bridgeWalletId, createLiquidationAddressResponse.bridgeWalletId) &&
        equalsNullable(this.destinationWireMessage, createLiquidationAddressResponse.destinationWireMessage) &&
        equalsNullable(this.destinationSepaReference, createLiquidationAddressResponse.destinationSepaReference) &&
        Objects.equals(this.destinationAchReference, createLiquidationAddressResponse.destinationAchReference) &&
        Objects.equals(this.destinationSpeiReference, createLiquidationAddressResponse.destinationSpeiReference) &&
        Objects.equals(this.destinationReference, createLiquidationAddressResponse.destinationReference) &&
        Objects.equals(this.destinationPaymentRail, createLiquidationAddressResponse.destinationPaymentRail) &&
        Objects.equals(this.destinationCurrency, createLiquidationAddressResponse.destinationCurrency) &&
        Objects.equals(this.destinationAddress, createLiquidationAddressResponse.destinationAddress) &&
        Objects.equals(this.destinationBlockchainMemo, createLiquidationAddressResponse.destinationBlockchainMemo) &&
        Objects.equals(this.returnAddress, createLiquidationAddressResponse.returnAddress) &&
        equalsNullable(this.customDeveloperFeePercent, createLiquidationAddressResponse.customDeveloperFeePercent) &&
        Objects.equals(this.address, createLiquidationAddressResponse.address) &&
        Objects.equals(this.state, createLiquidationAddressResponse.state);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, chain, hashCodeNullable(externalAccountId), hashCodeNullable(prefundedAccountId), bridgeWalletId, hashCodeNullable(destinationWireMessage), hashCodeNullable(destinationSepaReference), destinationAchReference, destinationSpeiReference, destinationReference, destinationPaymentRail, destinationCurrency, destinationAddress, destinationBlockchainMemo, returnAddress, hashCodeNullable(customDeveloperFeePercent), address, state);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLiquidationAddressResponse {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    prefundedAccountId: ").append(toIndentedString(prefundedAccountId)).append("\n");
    sb.append("    bridgeWalletId: ").append(toIndentedString(bridgeWalletId)).append("\n");
    sb.append("    destinationWireMessage: ").append(toIndentedString(destinationWireMessage)).append("\n");
    sb.append("    destinationSepaReference: ").append(toIndentedString(destinationSepaReference)).append("\n");
    sb.append("    destinationAchReference: ").append(toIndentedString(destinationAchReference)).append("\n");
    sb.append("    destinationSpeiReference: ").append(toIndentedString(destinationSpeiReference)).append("\n");
    sb.append("    destinationReference: ").append(toIndentedString(destinationReference)).append("\n");
    sb.append("    destinationPaymentRail: ").append(toIndentedString(destinationPaymentRail)).append("\n");
    sb.append("    destinationCurrency: ").append(toIndentedString(destinationCurrency)).append("\n");
    sb.append("    destinationAddress: ").append(toIndentedString(destinationAddress)).append("\n");
    sb.append("    destinationBlockchainMemo: ").append(toIndentedString(destinationBlockchainMemo)).append("\n");
    sb.append("    returnAddress: ").append(toIndentedString(returnAddress)).append("\n");
    sb.append("    customDeveloperFeePercent: ").append(toIndentedString(customDeveloperFeePercent)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

