/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.jhely.money.sdk.bridge.model.EuroInclusiveCurrency;
import org.jhely.money.sdk.bridge.model.LiquidationAddressSourceChain;
import org.jhely.money.sdk.bridge.model.LiquidationAddressSourceCurrency;
import org.jhely.money.sdk.bridge.model.SepaSwiftInclusivePaymentRail;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateLiquidationAddress
 */
@JsonPropertyOrder({
  CreateLiquidationAddress.JSON_PROPERTY_CURRENCY,
  CreateLiquidationAddress.JSON_PROPERTY_CHAIN,
  CreateLiquidationAddress.JSON_PROPERTY_EXTERNAL_ACCOUNT_ID,
  CreateLiquidationAddress.JSON_PROPERTY_PREFUNDED_ACCOUNT_ID,
  CreateLiquidationAddress.JSON_PROPERTY_BRIDGE_WALLET_ID,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_WIRE_MESSAGE,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_SEPA_REFERENCE,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_ACH_REFERENCE,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_SPEI_REFERENCE,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_REFERENCE,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_PAYMENT_RAIL,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_CURRENCY,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_ADDRESS,
  CreateLiquidationAddress.JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO,
  CreateLiquidationAddress.JSON_PROPERTY_RETURN_ADDRESS,
  CreateLiquidationAddress.JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateLiquidationAddress {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private LiquidationAddressSourceCurrency currency;

  public static final String JSON_PROPERTY_CHAIN = "chain";
  @jakarta.annotation.Nonnull
  private LiquidationAddressSourceChain chain;

  public static final String JSON_PROPERTY_EXTERNAL_ACCOUNT_ID = "external_account_id";
  @jakarta.annotation.Nullable
  private String externalAccountId;

  public static final String JSON_PROPERTY_PREFUNDED_ACCOUNT_ID = "prefunded_account_id";
  @jakarta.annotation.Nullable
  private String prefundedAccountId;

  public static final String JSON_PROPERTY_BRIDGE_WALLET_ID = "bridge_wallet_id";
  @jakarta.annotation.Nullable
  private String bridgeWalletId;

  public static final String JSON_PROPERTY_DESTINATION_WIRE_MESSAGE = "destination_wire_message";
  @jakarta.annotation.Nullable
  private String destinationWireMessage;

  public static final String JSON_PROPERTY_DESTINATION_SEPA_REFERENCE = "destination_sepa_reference";
  @jakarta.annotation.Nullable
  private String destinationSepaReference;

  public static final String JSON_PROPERTY_DESTINATION_ACH_REFERENCE = "destination_ach_reference";
  @jakarta.annotation.Nullable
  private String destinationAchReference;

  public static final String JSON_PROPERTY_DESTINATION_SPEI_REFERENCE = "destination_spei_reference";
  @jakarta.annotation.Nullable
  private String destinationSpeiReference;

  public static final String JSON_PROPERTY_DESTINATION_REFERENCE = "destination_reference";
  @jakarta.annotation.Nullable
  private String destinationReference;

  public static final String JSON_PROPERTY_DESTINATION_PAYMENT_RAIL = "destination_payment_rail";
  @jakarta.annotation.Nullable
  private SepaSwiftInclusivePaymentRail destinationPaymentRail;

  public static final String JSON_PROPERTY_DESTINATION_CURRENCY = "destination_currency";
  @jakarta.annotation.Nullable
  private EuroInclusiveCurrency destinationCurrency;

  public static final String JSON_PROPERTY_DESTINATION_ADDRESS = "destination_address";
  @jakarta.annotation.Nullable
  private String destinationAddress;

  public static final String JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO = "destination_blockchain_memo";
  @jakarta.annotation.Nullable
  private String destinationBlockchainMemo;

  public static final String JSON_PROPERTY_RETURN_ADDRESS = "return_address";
  @jakarta.annotation.Nullable
  private String returnAddress;

  public static final String JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT = "custom_developer_fee_percent";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> customDeveloperFeePercent = JsonNullable.<BigDecimal>undefined();

  public CreateLiquidationAddress() {
  }

  public CreateLiquidationAddress currency(@jakarta.annotation.Nonnull LiquidationAddressSourceCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LiquidationAddressSourceCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull LiquidationAddressSourceCurrency currency) {
    this.currency = currency;
  }

  public CreateLiquidationAddress chain(@jakarta.annotation.Nonnull LiquidationAddressSourceChain chain) {
    
    this.chain = chain;
    return this;
  }

  /**
   * Get chain
   * @return chain
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LiquidationAddressSourceChain getChain() {
    return chain;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(@jakarta.annotation.Nonnull LiquidationAddressSourceChain chain) {
    this.chain = chain;
  }

  public CreateLiquidationAddress externalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    
    this.externalAccountId = externalAccountId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return externalAccountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalAccountId() {
    return externalAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public CreateLiquidationAddress prefundedAccountId(@jakarta.annotation.Nullable String prefundedAccountId) {
    
    this.prefundedAccountId = prefundedAccountId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return prefundedAccountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREFUNDED_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrefundedAccountId() {
    return prefundedAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFUNDED_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefundedAccountId(@jakarta.annotation.Nullable String prefundedAccountId) {
    this.prefundedAccountId = prefundedAccountId;
  }

  public CreateLiquidationAddress bridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    
    this.bridgeWalletId = bridgeWalletId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return bridgeWalletId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBridgeWalletId() {
    return bridgeWalletId;
  }


  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    this.bridgeWalletId = bridgeWalletId;
  }

  public CreateLiquidationAddress destinationWireMessage(@jakarta.annotation.Nullable String destinationWireMessage) {
    
    this.destinationWireMessage = destinationWireMessage;
    return this;
  }

  /**
   * A message to be sent with a wire transfer. It can have up to 140 characters. This message will be validated against 4 lines, each with a max length of 35 characters according to the Fedwire standard.
   * @return destinationWireMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationWireMessage() {
    return destinationWireMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationWireMessage(@jakarta.annotation.Nullable String destinationWireMessage) {
    this.destinationWireMessage = destinationWireMessage;
  }

  public CreateLiquidationAddress destinationSepaReference(@jakarta.annotation.Nullable String destinationSepaReference) {
    
    this.destinationSepaReference = destinationSepaReference;
    return this;
  }

  /**
   * A reference message to be sent with a SEPA transaction. We recommend you set a unique value to help you and your customers track payments end to end. It must be from 6 to 140 characters. The allowed characters are &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, spaces, ampersand (&#x60;&amp;&#x60;), hyphen (&#x60;-&#x60;), full stop (&#x60;.&#x60;), and solidus (&#x60;/&#x60;). If not populated, the default value is \&quot;Payment via Bridge {unique_token}\&quot;.
   * @return destinationSepaReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationSepaReference() {
    return destinationSepaReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationSepaReference(@jakarta.annotation.Nullable String destinationSepaReference) {
    this.destinationSepaReference = destinationSepaReference;
  }

  public CreateLiquidationAddress destinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    
    this.destinationAchReference = destinationAchReference;
    return this;
  }

  /**
   * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
   * @return destinationAchReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationAchReference() {
    return destinationAchReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    this.destinationAchReference = destinationAchReference;
  }

  public CreateLiquidationAddress destinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    
    this.destinationSpeiReference = destinationSpeiReference;
    return this;
  }

  /**
   * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, and space
   * @return destinationSpeiReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationSpeiReference() {
    return destinationSpeiReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    this.destinationSpeiReference = destinationSpeiReference;
  }

  public CreateLiquidationAddress destinationReference(@jakarta.annotation.Nullable String destinationReference) {
    
    this.destinationReference = destinationReference;
    return this;
  }

  /**
   * A payment reference message for newer payment rails (e.g. PIX).
   * @return destinationReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationReference() {
    return destinationReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationReference(@jakarta.annotation.Nullable String destinationReference) {
    this.destinationReference = destinationReference;
  }

  public CreateLiquidationAddress destinationPaymentRail(@jakarta.annotation.Nullable SepaSwiftInclusivePaymentRail destinationPaymentRail) {
    
    this.destinationPaymentRail = destinationPaymentRail;
    return this;
  }

  /**
   * Get destinationPaymentRail
   * @return destinationPaymentRail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_PAYMENT_RAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SepaSwiftInclusivePaymentRail getDestinationPaymentRail() {
    return destinationPaymentRail;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_PAYMENT_RAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationPaymentRail(@jakarta.annotation.Nullable SepaSwiftInclusivePaymentRail destinationPaymentRail) {
    this.destinationPaymentRail = destinationPaymentRail;
  }

  public CreateLiquidationAddress destinationCurrency(@jakarta.annotation.Nullable EuroInclusiveCurrency destinationCurrency) {
    
    this.destinationCurrency = destinationCurrency;
    return this;
  }

  /**
   * Get destinationCurrency
   * @return destinationCurrency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EuroInclusiveCurrency getDestinationCurrency() {
    return destinationCurrency;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationCurrency(@jakarta.annotation.Nullable EuroInclusiveCurrency destinationCurrency) {
    this.destinationCurrency = destinationCurrency;
  }

  public CreateLiquidationAddress destinationAddress(@jakarta.annotation.Nullable String destinationAddress) {
    
    this.destinationAddress = destinationAddress;
    return this;
  }

  /**
   * The crypto wallet address that Bridge will use to send funds to the customer.
   * @return destinationAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationAddress() {
    return destinationAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationAddress(@jakarta.annotation.Nullable String destinationAddress) {
    this.destinationAddress = destinationAddress;
  }

  public CreateLiquidationAddress destinationBlockchainMemo(@jakarta.annotation.Nullable String destinationBlockchainMemo) {
    
    this.destinationBlockchainMemo = destinationBlockchainMemo;
    return this;
  }

  /**
   * The memo to include in the transaction, for blockchains that support memos only
   * @return destinationBlockchainMemo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationBlockchainMemo() {
    return destinationBlockchainMemo;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationBlockchainMemo(@jakarta.annotation.Nullable String destinationBlockchainMemo) {
    this.destinationBlockchainMemo = destinationBlockchainMemo;
  }

  public CreateLiquidationAddress returnAddress(@jakarta.annotation.Nullable String returnAddress) {
    
    this.returnAddress = returnAddress;
    return this;
  }

  /**
   * The crypto wallet address that Bridge will use to return funds to the customer in case of a failed transaction. This address must be on the same chain specified for the liquidation address. Please note, this functionality is not supported on Stellar.
   * @return returnAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnAddress() {
    return returnAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnAddress(@jakarta.annotation.Nullable String returnAddress) {
    this.returnAddress = returnAddress;
  }

  public CreateLiquidationAddress customDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
    
    return this;
  }

  /**
   * The developer fee percent that will be applied to this Liquidation Address or null to use the default fee. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
   * minimum: 0
   * maximum: 100
   * @return customDeveloperFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getCustomDeveloperFeePercent() {
        return customDeveloperFeePercent.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getCustomDeveloperFeePercent_JsonNullable() {
    return customDeveloperFeePercent;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT)
  public void setCustomDeveloperFeePercent_JsonNullable(JsonNullable<BigDecimal> customDeveloperFeePercent) {
    this.customDeveloperFeePercent = customDeveloperFeePercent;
  }

  public void setCustomDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLiquidationAddress createLiquidationAddress = (CreateLiquidationAddress) o;
    return Objects.equals(this.currency, createLiquidationAddress.currency) &&
        Objects.equals(this.chain, createLiquidationAddress.chain) &&
        Objects.equals(this.externalAccountId, createLiquidationAddress.externalAccountId) &&
        Objects.equals(this.prefundedAccountId, createLiquidationAddress.prefundedAccountId) &&
        Objects.equals(this.bridgeWalletId, createLiquidationAddress.bridgeWalletId) &&
        Objects.equals(this.destinationWireMessage, createLiquidationAddress.destinationWireMessage) &&
        Objects.equals(this.destinationSepaReference, createLiquidationAddress.destinationSepaReference) &&
        Objects.equals(this.destinationAchReference, createLiquidationAddress.destinationAchReference) &&
        Objects.equals(this.destinationSpeiReference, createLiquidationAddress.destinationSpeiReference) &&
        Objects.equals(this.destinationReference, createLiquidationAddress.destinationReference) &&
        Objects.equals(this.destinationPaymentRail, createLiquidationAddress.destinationPaymentRail) &&
        Objects.equals(this.destinationCurrency, createLiquidationAddress.destinationCurrency) &&
        Objects.equals(this.destinationAddress, createLiquidationAddress.destinationAddress) &&
        Objects.equals(this.destinationBlockchainMemo, createLiquidationAddress.destinationBlockchainMemo) &&
        Objects.equals(this.returnAddress, createLiquidationAddress.returnAddress) &&
        equalsNullable(this.customDeveloperFeePercent, createLiquidationAddress.customDeveloperFeePercent);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, chain, externalAccountId, prefundedAccountId, bridgeWalletId, destinationWireMessage, destinationSepaReference, destinationAchReference, destinationSpeiReference, destinationReference, destinationPaymentRail, destinationCurrency, destinationAddress, destinationBlockchainMemo, returnAddress, hashCodeNullable(customDeveloperFeePercent));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLiquidationAddress {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    prefundedAccountId: ").append(toIndentedString(prefundedAccountId)).append("\n");
    sb.append("    bridgeWalletId: ").append(toIndentedString(bridgeWalletId)).append("\n");
    sb.append("    destinationWireMessage: ").append(toIndentedString(destinationWireMessage)).append("\n");
    sb.append("    destinationSepaReference: ").append(toIndentedString(destinationSepaReference)).append("\n");
    sb.append("    destinationAchReference: ").append(toIndentedString(destinationAchReference)).append("\n");
    sb.append("    destinationSpeiReference: ").append(toIndentedString(destinationSpeiReference)).append("\n");
    sb.append("    destinationReference: ").append(toIndentedString(destinationReference)).append("\n");
    sb.append("    destinationPaymentRail: ").append(toIndentedString(destinationPaymentRail)).append("\n");
    sb.append("    destinationCurrency: ").append(toIndentedString(destinationCurrency)).append("\n");
    sb.append("    destinationAddress: ").append(toIndentedString(destinationAddress)).append("\n");
    sb.append("    destinationBlockchainMemo: ").append(toIndentedString(destinationBlockchainMemo)).append("\n");
    sb.append("    returnAddress: ").append(toIndentedString(returnAddress)).append("\n");
    sb.append("    customDeveloperFeePercent: ").append(toIndentedString(customDeveloperFeePercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

