/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.jhely.money.sdk.bridge.model.VirtualAccountDestination;
import org.jhely.money.sdk.bridge.model.VirtualAccountSourceDepositInstructions;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response
 */
@JsonPropertyOrder({
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_ID,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_STATUS,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_DEVELOPER_FEE_PERCENT,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_CUSTOMER_ID,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_CREATED_AT,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS,
  CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.JSON_PROPERTY_DESTINATION
})
@JsonTypeName("_customers__customerID__virtual_accounts__virtualAccountID__deactivate_post_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> status = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_DEVELOPER_FEE_PERCENT = "developer_fee_percent";
  @jakarta.annotation.Nullable
  private BigDecimal developerFeePercent;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customer_id";
  @jakarta.annotation.Nullable
  private String customerId;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS = "source_deposit_instructions";
  @jakarta.annotation.Nullable
  private VirtualAccountSourceDepositInstructions sourceDepositInstructions;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nullable
  private VirtualAccountDestination destination;

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt
  ) {
    this();
    this.createdAt = createdAt;
  }

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response status(@jakarta.annotation.Nullable Object status) {
    this.status = JsonNullable.<Object>of(status);
    
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getStatus() {
        return status.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getStatus_JsonNullable() {
    return status;
  }
  
  @JsonProperty(JSON_PROPERTY_STATUS)
  public void setStatus_JsonNullable(JsonNullable<Object> status) {
    this.status = status;
  }

  public void setStatus(@jakarta.annotation.Nullable Object status) {
    this.status = JsonNullable.<Object>of(status);
  }

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response developerFeePercent(@jakarta.annotation.Nullable BigDecimal developerFeePercent) {
    
    this.developerFeePercent = developerFeePercent;
    return this;
  }

  /**
   * The developer fee percent that will be applied to this Virtual Account. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
   * minimum: 0
   * maximum: 100
   * @return developerFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDeveloperFeePercent() {
    return developerFeePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal developerFeePercent) {
    this.developerFeePercent = developerFeePercent;
  }

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response customerId(@jakarta.annotation.Nullable String customerId) {
    
    this.customerId = customerId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return customerId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerId(@jakarta.annotation.Nullable String customerId) {
    this.customerId = customerId;
  }

  /**
   * Time of creation of the virtual account
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response sourceDepositInstructions(@jakarta.annotation.Nullable VirtualAccountSourceDepositInstructions sourceDepositInstructions) {
    
    this.sourceDepositInstructions = sourceDepositInstructions;
    return this;
  }

  /**
   * Get sourceDepositInstructions
   * @return sourceDepositInstructions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VirtualAccountSourceDepositInstructions getSourceDepositInstructions() {
    return sourceDepositInstructions;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceDepositInstructions(@jakarta.annotation.Nullable VirtualAccountSourceDepositInstructions sourceDepositInstructions) {
    this.sourceDepositInstructions = sourceDepositInstructions;
  }

  public CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response destination(@jakarta.annotation.Nullable VirtualAccountDestination destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VirtualAccountDestination getDestination() {
    return destination;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestination(@jakarta.annotation.Nullable VirtualAccountDestination destination) {
    this.destination = destination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response = (CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response) o;
    return Objects.equals(this.id, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.id) &&
        equalsNullable(this.status, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.status) &&
        Objects.equals(this.developerFeePercent, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.developerFeePercent) &&
        Objects.equals(this.customerId, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.customerId) &&
        Objects.equals(this.createdAt, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.createdAt) &&
        Objects.equals(this.sourceDepositInstructions, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.sourceDepositInstructions) &&
        Objects.equals(this.destination, customersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response.destination);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCodeNullable(status), developerFeePercent, customerId, createdAt, sourceDepositInstructions, destination);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivatePost200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    developerFeePercent: ").append(toIndentedString(developerFeePercent)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    sourceDepositInstructions: ").append(toIndentedString(sourceDepositInstructions)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

