/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CustomerCapabilityState;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerCapabilities
 */
@JsonPropertyOrder({
  CustomerCapabilities.JSON_PROPERTY_PAYIN_CRYPTO,
  CustomerCapabilities.JSON_PROPERTY_PAYOUT_CRYPTO,
  CustomerCapabilities.JSON_PROPERTY_PAYIN_FIAT,
  CustomerCapabilities.JSON_PROPERTY_PAYOUT_FIAT
})
@JsonTypeName("Customer_capabilities")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CustomerCapabilities {
  public static final String JSON_PROPERTY_PAYIN_CRYPTO = "payin_crypto";
  @jakarta.annotation.Nullable
  private CustomerCapabilityState payinCrypto;

  public static final String JSON_PROPERTY_PAYOUT_CRYPTO = "payout_crypto";
  @jakarta.annotation.Nullable
  private CustomerCapabilityState payoutCrypto;

  public static final String JSON_PROPERTY_PAYIN_FIAT = "payin_fiat";
  @jakarta.annotation.Nullable
  private CustomerCapabilityState payinFiat;

  public static final String JSON_PROPERTY_PAYOUT_FIAT = "payout_fiat";
  @jakarta.annotation.Nullable
  private CustomerCapabilityState payoutFiat;

  public CustomerCapabilities() {
  }

  public CustomerCapabilities payinCrypto(@jakarta.annotation.Nullable CustomerCapabilityState payinCrypto) {
    
    this.payinCrypto = payinCrypto;
    return this;
  }

  /**
   * Get payinCrypto
   * @return payinCrypto
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYIN_CRYPTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerCapabilityState getPayinCrypto() {
    return payinCrypto;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYIN_CRYPTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinCrypto(@jakarta.annotation.Nullable CustomerCapabilityState payinCrypto) {
    this.payinCrypto = payinCrypto;
  }

  public CustomerCapabilities payoutCrypto(@jakarta.annotation.Nullable CustomerCapabilityState payoutCrypto) {
    
    this.payoutCrypto = payoutCrypto;
    return this;
  }

  /**
   * Get payoutCrypto
   * @return payoutCrypto
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYOUT_CRYPTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerCapabilityState getPayoutCrypto() {
    return payoutCrypto;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYOUT_CRYPTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutCrypto(@jakarta.annotation.Nullable CustomerCapabilityState payoutCrypto) {
    this.payoutCrypto = payoutCrypto;
  }

  public CustomerCapabilities payinFiat(@jakarta.annotation.Nullable CustomerCapabilityState payinFiat) {
    
    this.payinFiat = payinFiat;
    return this;
  }

  /**
   * Get payinFiat
   * @return payinFiat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYIN_FIAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerCapabilityState getPayinFiat() {
    return payinFiat;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYIN_FIAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinFiat(@jakarta.annotation.Nullable CustomerCapabilityState payinFiat) {
    this.payinFiat = payinFiat;
  }

  public CustomerCapabilities payoutFiat(@jakarta.annotation.Nullable CustomerCapabilityState payoutFiat) {
    
    this.payoutFiat = payoutFiat;
    return this;
  }

  /**
   * Get payoutFiat
   * @return payoutFiat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYOUT_FIAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerCapabilityState getPayoutFiat() {
    return payoutFiat;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYOUT_FIAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutFiat(@jakarta.annotation.Nullable CustomerCapabilityState payoutFiat) {
    this.payoutFiat = payoutFiat;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerCapabilities customerCapabilities = (CustomerCapabilities) o;
    return Objects.equals(this.payinCrypto, customerCapabilities.payinCrypto) &&
        Objects.equals(this.payoutCrypto, customerCapabilities.payoutCrypto) &&
        Objects.equals(this.payinFiat, customerCapabilities.payinFiat) &&
        Objects.equals(this.payoutFiat, customerCapabilities.payoutFiat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payinCrypto, payoutCrypto, payinFiat, payoutFiat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerCapabilities {\n");
    sb.append("    payinCrypto: ").append(toIndentedString(payinCrypto)).append("\n");
    sb.append("    payoutCrypto: ").append(toIndentedString(payoutCrypto)).append("\n");
    sb.append("    payinFiat: ").append(toIndentedString(payinFiat)).append("\n");
    sb.append("    payoutFiat: ").append(toIndentedString(payoutFiat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

