/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * &#x60;offboarded&#x60;: represents a customer&#39;s account that was
 * internally reviewed and closed due to suspicious activity.
 * &#x60;paused&#x60;: represents a customer&#39;s account that is currently
 * under review because of activity on the platform.
 */
public enum CustomerStatus {

  ACTIVE("active"),

  AWAITING_QUESTIONNAIRE("awaiting_questionnaire"),

  AWAITING_UBO("awaiting_ubo"),

  INCOMPLETE("incomplete"),

  NOT_STARTED("not_started"),

  OFFBOARDED("offboarded"),

  PAUSED("paused"),

  REJECTED("rejected"),

  UNDER_REVIEW("under_review");

  private String value;

  CustomerStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CustomerStatus fromValue(String value) {
    for (CustomerStatus b : CustomerStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null; // Return null for unknown values to avoid deserialization failures
  }
}
