/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.Currency;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DrainReceipt
 */
@JsonPropertyOrder({
  DrainReceipt.JSON_PROPERTY_INITIAL_AMOUNT,
  DrainReceipt.JSON_PROPERTY_DEVELOPER_FEE,
  DrainReceipt.JSON_PROPERTY_SUBTOTAL_AMOUNT,
  DrainReceipt.JSON_PROPERTY_GAS_FEE,
  DrainReceipt.JSON_PROPERTY_CONVERTED_AMOUNT,
  DrainReceipt.JSON_PROPERTY_EXCHANGE_RATE,
  DrainReceipt.JSON_PROPERTY_OUTGOING_AMOUNT,
  DrainReceipt.JSON_PROPERTY_DESTINATION_CURRENCY,
  DrainReceipt.JSON_PROPERTY_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class DrainReceipt {
  public static final String JSON_PROPERTY_INITIAL_AMOUNT = "initial_amount";
  @jakarta.annotation.Nonnull
  private String initialAmount;

  public static final String JSON_PROPERTY_DEVELOPER_FEE = "developer_fee";
  @jakarta.annotation.Nonnull
  private String developerFee;

  public static final String JSON_PROPERTY_SUBTOTAL_AMOUNT = "subtotal_amount";
  @jakarta.annotation.Nonnull
  private String subtotalAmount;

  public static final String JSON_PROPERTY_GAS_FEE = "gas_fee";
  @jakarta.annotation.Nullable
  private String gasFee;

  public static final String JSON_PROPERTY_CONVERTED_AMOUNT = "converted_amount";
  @jakarta.annotation.Nonnull
  private String convertedAmount;

  public static final String JSON_PROPERTY_EXCHANGE_RATE = "exchange_rate";
  @jakarta.annotation.Nullable
  private Object exchangeRate = null;

  public static final String JSON_PROPERTY_OUTGOING_AMOUNT = "outgoing_amount";
  @jakarta.annotation.Nonnull
  private String outgoingAmount;

  public static final String JSON_PROPERTY_DESTINATION_CURRENCY = "destination_currency";
  @jakarta.annotation.Nonnull
  private Currency destinationCurrency;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public DrainReceipt() {
  }

  public DrainReceipt initialAmount(@jakarta.annotation.Nonnull String initialAmount) {
    
    this.initialAmount = initialAmount;
    return this;
  }

  /**
   * The initial amount of the drain, denominated in the fiat currency to which the currency of the Liquidation Address is pegged. Examples include \&quot;100.25\&quot;, \&quot;0.1\&quot;, \&quot;1.234567\&quot;, \&quot;1.000000000000000001\&quot; etc.
   * @return initialAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INITIAL_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInitialAmount() {
    return initialAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_INITIAL_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitialAmount(@jakarta.annotation.Nonnull String initialAmount) {
    this.initialAmount = initialAmount;
  }

  public DrainReceipt developerFee(@jakarta.annotation.Nonnull String developerFee) {
    
    this.developerFee = developerFee;
    return this;
  }

  /**
   * The developer fee, denominated in the fiat currency to which the currency of the Liquidation Address is pegged. This fee is a specific amount deducted from the initial total before conversion, rather than a percentage.
   * @return developerFee
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeveloperFee() {
    return developerFee;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeveloperFee(@jakarta.annotation.Nonnull String developerFee) {
    this.developerFee = developerFee;
  }

  public DrainReceipt subtotalAmount(@jakarta.annotation.Nonnull String subtotalAmount) {
    
    this.subtotalAmount = subtotalAmount;
    return this;
  }

  /**
   * The initial amount of the drain less the &#x60;developer_fee&#x60;, denominated in the fiat currency to which the Liquidation Address currency is pegged. Examples include \&quot;100.25\&quot;, \&quot;0.1\&quot;, \&quot;1.234567\&quot;, \&quot;1.000000000000000001\&quot; etc.
   * @return subtotalAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBTOTAL_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubtotalAmount() {
    return subtotalAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBTOTAL_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubtotalAmount(@jakarta.annotation.Nonnull String subtotalAmount) {
    this.subtotalAmount = subtotalAmount;
  }

  public DrainReceipt gasFee(@jakarta.annotation.Nullable String gasFee) {
    
    this.gasFee = gasFee;
    return this;
  }

  /**
   * The fee that is deducted from the withdrawn amount to pay for gas.  Only included for crypto withdrawals that cost gas (e.g. USDT or DAI). It&#39;s denominated in the fiat currency to which the destination currency is pegged.
   * @return gasFee
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAS_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGasFee() {
    return gasFee;
  }


  @JsonProperty(value = JSON_PROPERTY_GAS_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGasFee(@jakarta.annotation.Nullable String gasFee) {
    this.gasFee = gasFee;
  }

  public DrainReceipt convertedAmount(@jakarta.annotation.Nonnull String convertedAmount) {
    
    this.convertedAmount = convertedAmount;
    return this;
  }

  /**
   * The converted amount of the drain. It&#39;s denominated in the destination currency or its pegged fiat currency.
   * @return convertedAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONVERTED_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConvertedAmount() {
    return convertedAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_CONVERTED_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConvertedAmount(@jakarta.annotation.Nonnull String convertedAmount) {
    this.convertedAmount = convertedAmount;
  }

  public DrainReceipt exchangeRate(@jakarta.annotation.Nullable Object exchangeRate) {
    
    this.exchangeRate = exchangeRate;
    return this;
  }

  /**
   * The effective exchange rate that can be calculated by dividing the converted amount by the amount available for conversion after deducting the developer fee.
   * @return exchangeRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getExchangeRate() {
    return exchangeRate;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExchangeRate(@jakarta.annotation.Nullable Object exchangeRate) {
    this.exchangeRate = exchangeRate;
  }

  public DrainReceipt outgoingAmount(@jakarta.annotation.Nonnull String outgoingAmount) {
    
    this.outgoingAmount = outgoingAmount;
    return this;
  }

  /**
   * The final amount of the drain, equal to the &#x60;converted_amount&#x60; minus any gas fees. It&#39;s denominated in the destination currency or its pegged fiat currency.
   * @return outgoingAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTGOING_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOutgoingAmount() {
    return outgoingAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTGOING_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutgoingAmount(@jakarta.annotation.Nonnull String outgoingAmount) {
    this.outgoingAmount = outgoingAmount;
  }

  public DrainReceipt destinationCurrency(@jakarta.annotation.Nonnull Currency destinationCurrency) {
    
    this.destinationCurrency = destinationCurrency;
    return this;
  }

  /**
   * Get destinationCurrency
   * @return destinationCurrency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Currency getDestinationCurrency() {
    return destinationCurrency;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestinationCurrency(@jakarta.annotation.Nonnull Currency destinationCurrency) {
    this.destinationCurrency = destinationCurrency;
  }

  public DrainReceipt url(@jakarta.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * The URL of a user-facing copy of the receipt.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrainReceipt drainReceipt = (DrainReceipt) o;
    return Objects.equals(this.initialAmount, drainReceipt.initialAmount) &&
        Objects.equals(this.developerFee, drainReceipt.developerFee) &&
        Objects.equals(this.subtotalAmount, drainReceipt.subtotalAmount) &&
        Objects.equals(this.gasFee, drainReceipt.gasFee) &&
        Objects.equals(this.convertedAmount, drainReceipt.convertedAmount) &&
        Objects.equals(this.exchangeRate, drainReceipt.exchangeRate) &&
        Objects.equals(this.outgoingAmount, drainReceipt.outgoingAmount) &&
        Objects.equals(this.destinationCurrency, drainReceipt.destinationCurrency) &&
        Objects.equals(this.url, drainReceipt.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(initialAmount, developerFee, subtotalAmount, gasFee, convertedAmount, exchangeRate, outgoingAmount, destinationCurrency, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrainReceipt {\n");
    sb.append("    initialAmount: ").append(toIndentedString(initialAmount)).append("\n");
    sb.append("    developerFee: ").append(toIndentedString(developerFee)).append("\n");
    sb.append("    subtotalAmount: ").append(toIndentedString(subtotalAmount)).append("\n");
    sb.append("    gasFee: ").append(toIndentedString(gasFee)).append("\n");
    sb.append("    convertedAmount: ").append(toIndentedString(convertedAmount)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    outgoingAmount: ").append(toIndentedString(outgoingAmount)).append("\n");
    sb.append("    destinationCurrency: ").append(toIndentedString(destinationCurrency)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

