/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Gets or Sets EndorsementRequirementEnum
 */
public enum EndorsementRequirementEnum {

  KYC_APPROVAL("kyc_approval"),

  TOS_ACCEPTANCE("tos_acceptance"),

  KYC_WITH_PROOF_OF_ADDRESS("kyc_with_proof_of_address"),

  TOS_V2_ACCEPTANCE("tos_v2_acceptance");

  private String value;

  EndorsementRequirementEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EndorsementRequirementEnum fromValue(String value) {
    for (EndorsementRequirementEnum b : EndorsementRequirementEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null; // Return null for unknown values to avoid deserialization failures
  }
}
