/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jhely.money.sdk.bridge.model.EndorsementRequirementEnum;
import org.jhely.money.sdk.bridge.model.EndorsementRequirements;
import org.jhely.money.sdk.bridge.model.EndorsementType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Endorsement
 */
@JsonPropertyOrder({
  Endorsement.JSON_PROPERTY_NAME,
  Endorsement.JSON_PROPERTY_STATUS,
  Endorsement.JSON_PROPERTY_ADDITIONAL_REQUIREMENTS,
  Endorsement.JSON_PROPERTY_REQUIREMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Endorsement {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private EndorsementType name;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    INCOMPLETE(String.valueOf("incomplete")),
    
    APPROVED(String.valueOf("approved")),
    
    REVOKED(String.valueOf("revoked"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_ADDITIONAL_REQUIREMENTS = "additional_requirements";
  @jakarta.annotation.Nullable
  private List<EndorsementRequirementEnum> additionalRequirements = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUIREMENTS = "requirements";
  @jakarta.annotation.Nullable
  private EndorsementRequirements requirements;

  public Endorsement() {
  }

  public Endorsement name(@jakarta.annotation.Nonnull EndorsementType name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EndorsementType getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull EndorsementType name) {
    this.name = name;
  }

  public Endorsement status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public Endorsement additionalRequirements(@jakarta.annotation.Nullable List<EndorsementRequirementEnum> additionalRequirements) {
    
    this.additionalRequirements = additionalRequirements;
    return this;
  }

  public Endorsement addAdditionalRequirementsItem(EndorsementRequirementEnum additionalRequirementsItem) {
    if (this.additionalRequirements == null) {
      this.additionalRequirements = new ArrayList<>();
    }
    this.additionalRequirements.add(additionalRequirementsItem);
    return this;
  }

  /**
   * Additional requirements that need to be completed for obtaining the approval for the endorsement.   1. &#x60;kyc_approval&#x60; and &#x60;tos_acceptance&#x60; are required for the &#x60;base&#x60; endorsement.  2. &#x60;tos_v2_acceptance&#x60; is required for &#x60;sepa&#x60; and &#x60;kyc_with_proof_of_address&#x60; may also be needed in certain situations. If &#x60;tos_v2_acceptance&#x60; is not completed, a ToS acceptance link can be retrieved for the current customer from the endpoint &#x60;/v0/customers/{customerID}/tos_acceptance_link&#x60;. To fulfill the &#x60;kyc_with_proof_of_address&#x60; requirement, a KYC link can be specifically requested for the current customer via the endpoint &#x60;/v0/customers/{customerID}/kyc_link&#x60;, with &#x60;endorsement&#x3D;sepa&#x60; included in the query string
   * @return additionalRequirements
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_REQUIREMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EndorsementRequirementEnum> getAdditionalRequirements() {
    return additionalRequirements;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_REQUIREMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalRequirements(@jakarta.annotation.Nullable List<EndorsementRequirementEnum> additionalRequirements) {
    this.additionalRequirements = additionalRequirements;
  }

  public Endorsement requirements(@jakarta.annotation.Nullable EndorsementRequirements requirements) {
    
    this.requirements = requirements;
    return this;
  }

  /**
   * Get requirements
   * @return requirements
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUIREMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EndorsementRequirements getRequirements() {
    return requirements;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIREMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequirements(@jakarta.annotation.Nullable EndorsementRequirements requirements) {
    this.requirements = requirements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Endorsement endorsement = (Endorsement) o;
    return Objects.equals(this.name, endorsement.name) &&
        Objects.equals(this.status, endorsement.status) &&
        Objects.equals(this.additionalRequirements, endorsement.additionalRequirements) &&
        Objects.equals(this.requirements, endorsement.requirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, additionalRequirements, requirements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Endorsement {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    additionalRequirements: ").append(toIndentedString(additionalRequirements)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

