/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Gets or Sets EuroInclusiveCurrency
 */
public enum EuroInclusiveCurrency {
  
  DAI("dai"),
  
  EUR("eur"),
  
  EURC("eurc"),
  
  MXN("mxn"),
  
  PYUSD("pyusd"),
  
  USD("usd"),
  
  USDB("usdb"),
  
  USDC("usdc"),
  
  USDT("usdt");

  private String value;

  EuroInclusiveCurrency(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EuroInclusiveCurrency fromValue(String value) {
    for (EuroInclusiveCurrency b : EuroInclusiveCurrency.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

