/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * IdentifyingInformationInner
 */
@JsonPropertyOrder({
  IdentifyingInformationInner.JSON_PROPERTY_TYPE,
  IdentifyingInformationInner.JSON_PROPERTY_ISSUING_COUNTRY,
  IdentifyingInformationInner.JSON_PROPERTY_NUMBER,
  IdentifyingInformationInner.JSON_PROPERTY_DESCRIPTION,
  IdentifyingInformationInner.JSON_PROPERTY_EXPIRATION,
  IdentifyingInformationInner.JSON_PROPERTY_IMAGE_FRONT,
  IdentifyingInformationInner.JSON_PROPERTY_IMAGE_BACK
})
@JsonTypeName("IdentifyingInformation_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class IdentifyingInformationInner {
  /**
   * The &#x60;type&#x60; provided determines whether you are submitting a tax identification number or some form of government-issued ID.  Reference these lists for tax identification numbers by country: [Individuals](https://apidocs.bridge.xyz/docs/individual-tax-identification-numbers-by-country), [Businesses](https://apidocs.bridge.xyz/docs/business-tax-identification-numbers-by-country)  Here is the list of acceptable government issued id documents: &#x60;drivers_license&#x60;, &#x60;matriculate_id&#x60;, &#x60;military_id&#x60;, &#x60;permanent_residency_id&#x60;, &#x60;state_or_provincial_id&#x60;, &#x60;visa&#x60;, &#x60;national_id&#x60;, &#x60;passport&#x60;  All customers must provide at least one Tax Identification Number for their issuing country. If a country cannot be found, please select &#x60;other&#x60; and ensure the &#x60;description&#x60; field is provided.  Non-U.S. &#x60;individual&#x60; customers and associated persons must include a combination of at least one Tax Identification Number and at least one photo id document such as a &#x60;passport&#x60; (with &#x60;image_front&#x60;) or a government-issued &#x60;drivers_license&#x60;. If the photo id document used is also a valid tax identification number (like a national id), it can be submitted as a single object in the &#x60;identifying_information&#x60; array; otherwise, a valid tax identification number must also be submitted as a separate object in the &#x60;identifying_information&#x60; array. 
   */
  public enum TypeEnum {
    DRIVERS_LICENSE(String.valueOf("drivers_license")),
    
    MATRICULATE_ID(String.valueOf("matriculate_id")),
    
    MILITARY_ID(String.valueOf("military_id")),
    
    NATIONAL_ID(String.valueOf("national_id")),
    
    PASSPORT(String.valueOf("passport")),
    
    PERMANENT_RESIDENCY_ID(String.valueOf("permanent_residency_id")),
    
    STATE_OR_PROVINCIAL_ID(String.valueOf("state_or_provincial_id")),
    
    VISA(String.valueOf("visa")),
    
    ABN(String.valueOf("abn")),
    
    ACN(String.valueOf("acn")),
    
    AHV(String.valueOf("ahv")),
    
    AK(String.valueOf("ak")),
    
    AOM(String.valueOf("aom")),
    
    ARBN(String.valueOf("arbn")),
    
    AVS(String.valueOf("avs")),
    
    BC(String.valueOf("bc")),
    
    BCE(String.valueOf("bce")),
    
    BIN(String.valueOf("bin")),
    
    BIR(String.valueOf("bir")),
    
    BP(String.valueOf("bp")),
    
    BRN(String.valueOf("brn")),
    
    BSN(String.valueOf("bsn")),
    
    BVN(String.valueOf("bvn")),
    
    CC(String.valueOf("cc")),
    
    CDI(String.valueOf("cdi")),
    
    CEDULA_JURIDICA(String.valueOf("cedula_juridica")),
    
    CF(String.valueOf("cf")),
    
    CIF(String.valueOf("cif")),
    
    CIN(String.valueOf("cin")),
    
    CIPC(String.valueOf("cipc")),
    
    CN(String.valueOf("cn")),
    
    CNP(String.valueOf("cnp")),
    
    CNPJ(String.valueOf("cnpj")),
    
    CPF(String.valueOf("cpf")),
    
    CPR(String.valueOf("cpr")),
    
    CRC(String.valueOf("crc")),
    
    CRIB(String.valueOf("crib")),
    
    CRN(String.valueOf("crn")),
    
    CRO(String.valueOf("cro")),
    
    CUI(String.valueOf("cui")),
    
    CUIL(String.valueOf("cuil")),
    
    CURP(String.valueOf("curp")),
    
    CUIT(String.valueOf("cuit")),
    
    CVR(String.valueOf("cvr")),
    
    EDRPOU(String.valueOf("edrpou")),
    
    EIN(String.valueOf("ein")),
    
    EMBG(String.valueOf("embg")),
    
    EMIRATES_ID(String.valueOf("emirates_id")),
    
    EN(String.valueOf("en")),
    
    FIN(String.valueOf("fin")),
    
    FN(String.valueOf("fn")),
    
    GSTIN(String.valueOf("gstin")),
    
    GUI(String.valueOf("gui")),
    
    HETU(String.valueOf("hetu")),
    
    HKID(String.valueOf("hkid")),
    
    HN(String.valueOf("hn")),
    
    IC(String.valueOf("ic")),
    
    ICO(String.valueOf("ico")),
    
    ID(String.valueOf("id")),
    
    ID_BROJ(String.valueOf("id_broj")),
    
    IDNO(String.valueOf("idno")),
    
    IDNP(String.valueOf("idnp")),
    
    IDNR(String.valueOf("idnr")),
    
    IF(String.valueOf("if")),
    
    IIN(String.valueOf("iin")),
    
    IK(String.valueOf("ik")),
    
    INN(String.valueOf("inn")),
    
    IRD(String.valueOf("ird")),
    
    ITIN(String.valueOf("itin")),
    
    ITR(String.valueOf("itr")),
    
    IVA(String.valueOf("iva")),
    
    JMBG(String.valueOf("jmbg")),
    
    KBO(String.valueOf("kbo")),
    
    KVK(String.valueOf("kvk")),
    
    MATRICULE(String.valueOf("matricule")),
    
    MF(String.valueOf("mf")),
    
    MN(String.valueOf("mn")),
    
    MS(String.valueOf("ms")),
    
    MST(String.valueOf("mst")),
    
    NIC(String.valueOf("nic")),
    
    NICN(String.valueOf("nicn")),
    
    NIE(String.valueOf("nie")),
    
    NIF(String.valueOf("nif")),
    
    NIN(String.valueOf("nin")),
    
    NINO(String.valueOf("nino")),
    
    NIP(String.valueOf("nip")),
    
    NIPC(String.valueOf("nipc")),
    
    NIPT(String.valueOf("nipt")),
    
    NIT(String.valueOf("nit")),
    
    NPWP(String.valueOf("npwp")),
    
    NRIC(String.valueOf("nric")),
    
    NRN(String.valueOf("nrn")),
    
    NRT(String.valueOf("nrt")),
    
    NTN(String.valueOf("ntn")),
    
    NUIT(String.valueOf("nuit")),
    
    NZBN(String.valueOf("nzbn")),
    
    OIB(String.valueOf("oib")),
    
    ORGNR(String.valueOf("orgnr")),
    
    OTHER(String.valueOf("other")),
    
    PAN(String.valueOf("pan")),
    
    PARTITA_IVA(String.valueOf("partita_iva")),
    
    PESEL(String.valueOf("pesel")),
    
    PIB(String.valueOf("pib")),
    
    PIN(String.valueOf("pin")),
    
    PK(String.valueOf("pk")),
    
    PPSN(String.valueOf("ppsn")),
    
    QID(String.valueOf("qid")),
    
    RC(String.valueOf("rc")),
    
    REGON(String.valueOf("regon")),
    
    RFC(String.valueOf("rfc")),
    
    RICN(String.valueOf("ricn")),
    
    RIF(String.valueOf("rif")),
    
    RN(String.valueOf("rn")),
    
    RNC(String.valueOf("rnc")),
    
    RNOKPP(String.valueOf("rnokpp")),
    
    RP(String.valueOf("rp")),
    
    RRN(String.valueOf("rrn")),
    
    RTN(String.valueOf("rtn")),
    
    RUC(String.valueOf("ruc")),
    
    RUT(String.valueOf("rut")),
    
    SI(String.valueOf("si")),
    
    SIN(String.valueOf("sin")),
    
    SIREN(String.valueOf("siren")),
    
    SIRET(String.valueOf("siret")),
    
    SPI(String.valueOf("spi")),
    
    SSM(String.valueOf("ssm")),
    
    SSN(String.valueOf("ssn")),
    
    STEUER_ID(String.valueOf("steuer_id")),
    
    STRN(String.valueOf("strn")),
    
    TCKN(String.valueOf("tckn")),
    
    TFN(String.valueOf("tfn")),
    
    TIN(String.valueOf("tin")),
    
    TPIN(String.valueOf("tpin")),
    
    TRN(String.valueOf("trn")),
    
    UCN(String.valueOf("ucn")),
    
    UEN(String.valueOf("uen")),
    
    UIC(String.valueOf("uic")),
    
    UID(String.valueOf("uid")),
    
    USC(String.valueOf("usc")),
    
    UST_IDNR(String.valueOf("ust_idnr")),
    
    UTR(String.valueOf("utr")),
    
    VAT(String.valueOf("vat")),
    
    VKN(String.valueOf("vkn")),
    
    VOEN(String.valueOf("voen")),
    
    Y_TUNNUS(String.valueOf("y_tunnus"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_ISSUING_COUNTRY = "issuing_country";
  @jakarta.annotation.Nonnull
  private String issuingCountry;

  public static final String JSON_PROPERTY_NUMBER = "number";
  @jakarta.annotation.Nullable
  private String number;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @jakarta.annotation.Nullable
  private String expiration;

  public static final String JSON_PROPERTY_IMAGE_FRONT = "image_front";
  @jakarta.annotation.Nullable
  private String imageFront;

  public static final String JSON_PROPERTY_IMAGE_BACK = "image_back";
  @jakarta.annotation.Nullable
  private String imageBack;

  public IdentifyingInformationInner() {
  }

  public IdentifyingInformationInner type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The &#x60;type&#x60; provided determines whether you are submitting a tax identification number or some form of government-issued ID.  Reference these lists for tax identification numbers by country: [Individuals](https://apidocs.bridge.xyz/docs/individual-tax-identification-numbers-by-country), [Businesses](https://apidocs.bridge.xyz/docs/business-tax-identification-numbers-by-country)  Here is the list of acceptable government issued id documents: &#x60;drivers_license&#x60;, &#x60;matriculate_id&#x60;, &#x60;military_id&#x60;, &#x60;permanent_residency_id&#x60;, &#x60;state_or_provincial_id&#x60;, &#x60;visa&#x60;, &#x60;national_id&#x60;, &#x60;passport&#x60;  All customers must provide at least one Tax Identification Number for their issuing country. If a country cannot be found, please select &#x60;other&#x60; and ensure the &#x60;description&#x60; field is provided.  Non-U.S. &#x60;individual&#x60; customers and associated persons must include a combination of at least one Tax Identification Number and at least one photo id document such as a &#x60;passport&#x60; (with &#x60;image_front&#x60;) or a government-issued &#x60;drivers_license&#x60;. If the photo id document used is also a valid tax identification number (like a national id), it can be submitted as a single object in the &#x60;identifying_information&#x60; array; otherwise, a valid tax identification number must also be submitted as a separate object in the &#x60;identifying_information&#x60; array. 
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public IdentifyingInformationInner issuingCountry(@jakarta.annotation.Nonnull String issuingCountry) {
    
    this.issuingCountry = issuingCountry;
    return this;
  }

  /**
   * The ISO 3166-1 (three-character) country code that issued the provided document.
   * @return issuingCountry
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ISSUING_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIssuingCountry() {
    return issuingCountry;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUING_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssuingCountry(@jakarta.annotation.Nonnull String issuingCountry) {
    this.issuingCountry = issuingCountry;
  }

  public IdentifyingInformationInner number(@jakarta.annotation.Nullable String number) {
    
    this.number = number;
    return this;
  }

  /**
   * The unique identifier of the document. Required if this document is being used as a tax identification number (e.g., you are providing a passport or national_id with no other identification).
   * @return number
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumber() {
    return number;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumber(@jakarta.annotation.Nullable String number) {
    this.number = number;
  }

  public IdentifyingInformationInner description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A description describing the provided document. This field is required when &#x60;other&#x60; is selected.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public IdentifyingInformationInner expiration(@jakarta.annotation.Nullable String expiration) {
    
    this.expiration = expiration;
    return this;
  }

  /**
   * The expiration date of the given document in yyyy-mm-dd format.
   * @return expiration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpiration() {
    return expiration;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiration(@jakarta.annotation.Nullable String expiration) {
    this.expiration = expiration;
  }

  public IdentifyingInformationInner imageFront(@jakarta.annotation.Nullable String imageFront) {
    
    this.imageFront = imageFront;
    return this;
  }

  /**
   * This field is optionally accepted for tax_id types, but required for government_id types. Base64 encoded image* of the front side of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px \\n\\n*Maximum File Size: 15MB\\n\\n*Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif  _Note: When combined with an &#x60;image_back&#x60;, the combined size of both images must not exceed 24MB._ 
   * @return imageFront
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_FRONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageFront() {
    return imageFront;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_FRONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageFront(@jakarta.annotation.Nullable String imageFront) {
    this.imageFront = imageFront;
  }

  public IdentifyingInformationInner imageBack(@jakarta.annotation.Nullable String imageBack) {
    
    this.imageBack = imageBack;
    return this;
  }

  /**
   * Base64 encoded image* of the back side of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px \\n\\n*Maximum File Size: 15MB\\n\\n*Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif  _Note: When combined with an &#x60;image_front&#x60;, the combined size of both images must not exceed 24MB._ 
   * @return imageBack
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_BACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageBack() {
    return imageBack;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_BACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageBack(@jakarta.annotation.Nullable String imageBack) {
    this.imageBack = imageBack;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentifyingInformationInner identifyingInformationInner = (IdentifyingInformationInner) o;
    return Objects.equals(this.type, identifyingInformationInner.type) &&
        Objects.equals(this.issuingCountry, identifyingInformationInner.issuingCountry) &&
        Objects.equals(this.number, identifyingInformationInner.number) &&
        Objects.equals(this.description, identifyingInformationInner.description) &&
        Objects.equals(this.expiration, identifyingInformationInner.expiration) &&
        Objects.equals(this.imageFront, identifyingInformationInner.imageFront) &&
        Objects.equals(this.imageBack, identifyingInformationInner.imageBack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, issuingCountry, number, description, expiration, imageFront, imageBack);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentifyingInformationInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    issuingCountry: ").append(toIndentedString(issuingCountry)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    imageFront: ").append(toIndentedString(imageFront)).append("\n");
    sb.append("    imageBack: ").append(toIndentedString(imageBack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

