/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The developer fee percent that will be default applied to all Liquidation Addresses.
 */
@JsonPropertyOrder({
  LiquidationAddressGlobalDeveloperFeePercent.JSON_PROPERTY_PERCENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class LiquidationAddressGlobalDeveloperFeePercent {
  public static final String JSON_PROPERTY_PERCENT = "percent";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> percent = JsonNullable.<BigDecimal>undefined();

  public LiquidationAddressGlobalDeveloperFeePercent() {
  }

  public LiquidationAddressGlobalDeveloperFeePercent percent(@jakarta.annotation.Nullable BigDecimal percent) {
    this.percent = JsonNullable.<BigDecimal>of(percent);
    
    return this;
  }

  /**
   * Get percent
   * minimum: 0
   * maximum: 100
   * @return percent
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getPercent() {
        return percent.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getPercent_JsonNullable() {
    return percent;
  }
  
  @JsonProperty(JSON_PROPERTY_PERCENT)
  public void setPercent_JsonNullable(JsonNullable<BigDecimal> percent) {
    this.percent = percent;
  }

  public void setPercent(@jakarta.annotation.Nullable BigDecimal percent) {
    this.percent = JsonNullable.<BigDecimal>of(percent);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiquidationAddressGlobalDeveloperFeePercent liquidationAddressGlobalDeveloperFeePercent = (LiquidationAddressGlobalDeveloperFeePercent) o;
    return equalsNullable(this.percent, liquidationAddressGlobalDeveloperFeePercent.percent);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(percent));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiquidationAddressGlobalDeveloperFeePercent {\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

