/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CardFreezeInitiator;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostCardUnfreezeInput
 */
@JsonPropertyOrder({
  PostCardUnfreezeInput.JSON_PROPERTY_INITIATOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PostCardUnfreezeInput {
  public static final String JSON_PROPERTY_INITIATOR = "initiator";
  @jakarta.annotation.Nonnull
  private CardFreezeInitiator initiator;

  public PostCardUnfreezeInput() {
  }

  public PostCardUnfreezeInput initiator(@jakarta.annotation.Nonnull CardFreezeInitiator initiator) {
    
    this.initiator = initiator;
    return this;
  }

  /**
   * The party of the freeze to be removed
   * @return initiator
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INITIATOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CardFreezeInitiator getInitiator() {
    return initiator;
  }


  @JsonProperty(value = JSON_PROPERTY_INITIATOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitiator(@jakarta.annotation.Nonnull CardFreezeInitiator initiator) {
    this.initiator = initiator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCardUnfreezeInput postCardUnfreezeInput = (PostCardUnfreezeInput) o;
    return Objects.equals(this.initiator, postCardUnfreezeInput.initiator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(initiator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCardUnfreezeInput {\n");
    sb.append("    initiator: ").append(toIndentedString(initiator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

