/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CardCryptoAccount;
import org.jhely.money.sdk.bridge.model.CardsCryptoCurrency;
import org.jhely.money.sdk.bridge.model.OfframpChainForCards;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostCardAccountsInput
 */
@JsonPropertyOrder({
  PostCardAccountsInput.JSON_PROPERTY_CLIENT_REFERENCE_ID,
  PostCardAccountsInput.JSON_PROPERTY_CURRENCY,
  PostCardAccountsInput.JSON_PROPERTY_CHAIN,
  PostCardAccountsInput.JSON_PROPERTY_CRYPTO_ACCOUNT,
  PostCardAccountsInput.JSON_PROPERTY_CARD_DESIGN_SHORTNAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PostCardAccountsInput {
  public static final String JSON_PROPERTY_CLIENT_REFERENCE_ID = "client_reference_id";
  @jakarta.annotation.Nullable
  private String clientReferenceId;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private CardsCryptoCurrency currency;

  public static final String JSON_PROPERTY_CHAIN = "chain";
  @jakarta.annotation.Nonnull
  private OfframpChainForCards chain;

  public static final String JSON_PROPERTY_CRYPTO_ACCOUNT = "crypto_account";
  @jakarta.annotation.Nullable
  private CardCryptoAccount cryptoAccount;

  public static final String JSON_PROPERTY_CARD_DESIGN_SHORTNAME = "card_design_shortname";
  @jakarta.annotation.Nullable
  private String cardDesignShortname;

  public PostCardAccountsInput() {
  }

  public PostCardAccountsInput clientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * An optional client-provided reference ID that uniquely identifies the card account in the client&#39;s system
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientReferenceId() {
    return clientReferenceId;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }

  public PostCardAccountsInput currency(@jakarta.annotation.Nonnull CardsCryptoCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CardsCryptoCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull CardsCryptoCurrency currency) {
    this.currency = currency;
  }

  public PostCardAccountsInput chain(@jakarta.annotation.Nonnull OfframpChainForCards chain) {
    
    this.chain = chain;
    return this;
  }

  /**
   * Get chain
   * @return chain
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OfframpChainForCards getChain() {
    return chain;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(@jakarta.annotation.Nonnull OfframpChainForCards chain) {
    this.chain = chain;
  }

  public PostCardAccountsInput cryptoAccount(@jakarta.annotation.Nullable CardCryptoAccount cryptoAccount) {
    
    this.cryptoAccount = cryptoAccount;
    return this;
  }

  /**
   * Get cryptoAccount
   * @return cryptoAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CRYPTO_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardCryptoAccount getCryptoAccount() {
    return cryptoAccount;
  }


  @JsonProperty(value = JSON_PROPERTY_CRYPTO_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCryptoAccount(@jakarta.annotation.Nullable CardCryptoAccount cryptoAccount) {
    this.cryptoAccount = cryptoAccount;
  }

  public PostCardAccountsInput cardDesignShortname(@jakarta.annotation.Nullable String cardDesignShortname) {
    
    this.cardDesignShortname = cardDesignShortname;
    return this;
  }

  /**
   * The shortname of the card design to use for the card account. If not specified, the default card design will be used.
   * @return cardDesignShortname
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CARD_DESIGN_SHORTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCardDesignShortname() {
    return cardDesignShortname;
  }


  @JsonProperty(value = JSON_PROPERTY_CARD_DESIGN_SHORTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardDesignShortname(@jakarta.annotation.Nullable String cardDesignShortname) {
    this.cardDesignShortname = cardDesignShortname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCardAccountsInput postCardAccountsInput = (PostCardAccountsInput) o;
    return Objects.equals(this.clientReferenceId, postCardAccountsInput.clientReferenceId) &&
        Objects.equals(this.currency, postCardAccountsInput.currency) &&
        Objects.equals(this.chain, postCardAccountsInput.chain) &&
        Objects.equals(this.cryptoAccount, postCardAccountsInput.cryptoAccount) &&
        Objects.equals(this.cardDesignShortname, postCardAccountsInput.cardDesignShortname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientReferenceId, currency, chain, cryptoAccount, cardDesignShortname);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCardAccountsInput {\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    cryptoAccount: ").append(toIndentedString(cryptoAccount)).append("\n");
    sb.append("    cardDesignShortname: ").append(toIndentedString(cardDesignShortname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

