/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RewardRate
 */
@JsonPropertyOrder({
  RewardRate.JSON_PROPERTY_RATE,
  RewardRate.JSON_PROPERTY_EFFECTIVE_AT,
  RewardRate.JSON_PROPERTY_EXPIRES_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RewardRate {
  public static final String JSON_PROPERTY_RATE = "rate";
  @jakarta.annotation.Nullable
  private String rate;

  public static final String JSON_PROPERTY_EFFECTIVE_AT = "effective_at";
  @jakarta.annotation.Nullable
  private String effectiveAt;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @jakarta.annotation.Nullable
  private String expiresAt;

  public RewardRate() {
  }

  public RewardRate rate(@jakarta.annotation.Nullable String rate) {
    
    this.rate = rate;
    return this;
  }

  /**
   * The reward rate for the given stablecoin
   * @return rate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRate() {
    return rate;
  }


  @JsonProperty(value = JSON_PROPERTY_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRate(@jakarta.annotation.Nullable String rate) {
    this.rate = rate;
  }

  public RewardRate effectiveAt(@jakarta.annotation.Nullable String effectiveAt) {
    
    this.effectiveAt = effectiveAt;
    return this;
  }

  /**
   * The effective date of the reward rate, in ISO8601 format
   * @return effectiveAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEffectiveAt() {
    return effectiveAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectiveAt(@jakarta.annotation.Nullable String effectiveAt) {
    this.effectiveAt = effectiveAt;
  }

  public RewardRate expiresAt(@jakarta.annotation.Nullable String expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * The expiration date of the reward rate, in ISO8601 format
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardRate rewardRate = (RewardRate) o;
    return Objects.equals(this.rate, rewardRate.rate) &&
        Objects.equals(this.effectiveAt, rewardRate.effectiveAt) &&
        Objects.equals(this.expiresAt, rewardRate.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rate, effectiveAt, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardRate {\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    effectiveAt: ").append(toIndentedString(effectiveAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

