/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.CryptoCurrency;
import org.jhely.money.sdk.bridge.model.OfframpChain;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StaticMemoDestination
 */
@JsonPropertyOrder({
  StaticMemoDestination.JSON_PROPERTY_CURRENCY,
  StaticMemoDestination.JSON_PROPERTY_PAYMENT_RAIL,
  StaticMemoDestination.JSON_PROPERTY_ADDRESS,
  StaticMemoDestination.JSON_PROPERTY_BRIDGE_WALLET_ID,
  StaticMemoDestination.JSON_PROPERTY_BLOCKCHAIN_MEMO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class StaticMemoDestination {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private CryptoCurrency currency;

  public static final String JSON_PROPERTY_PAYMENT_RAIL = "payment_rail";
  @jakarta.annotation.Nonnull
  private OfframpChain paymentRail;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_BRIDGE_WALLET_ID = "bridge_wallet_id";
  @jakarta.annotation.Nullable
  private String bridgeWalletId;

  public static final String JSON_PROPERTY_BLOCKCHAIN_MEMO = "blockchain_memo";
  @jakarta.annotation.Nullable
  private String blockchainMemo;

  public StaticMemoDestination() {
  }

  public StaticMemoDestination currency(@jakarta.annotation.Nonnull CryptoCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CryptoCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull CryptoCurrency currency) {
    this.currency = currency;
  }

  public StaticMemoDestination paymentRail(@jakarta.annotation.Nonnull OfframpChain paymentRail) {
    
    this.paymentRail = paymentRail;
    return this;
  }

  /**
   * Get paymentRail
   * @return paymentRail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OfframpChain getPaymentRail() {
    return paymentRail;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRail(@jakarta.annotation.Nonnull OfframpChain paymentRail) {
    this.paymentRail = paymentRail;
  }

  public StaticMemoDestination address(@jakarta.annotation.Nonnull String address) {
    
    this.address = address;
    return this;
  }

  /**
   * The crypto wallet address that the customer wishes to ultimately receive funds at
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }

  public StaticMemoDestination bridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    
    this.bridgeWalletId = bridgeWalletId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return bridgeWalletId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBridgeWalletId() {
    return bridgeWalletId;
  }


  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    this.bridgeWalletId = bridgeWalletId;
  }

  public StaticMemoDestination blockchainMemo(@jakarta.annotation.Nullable String blockchainMemo) {
    
    this.blockchainMemo = blockchainMemo;
    return this;
  }

  /**
   * The memo to include when sending funds on chain. Only allowed for blockchains that support memos such as Stellar
   * @return blockchainMemo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBlockchainMemo() {
    return blockchainMemo;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockchainMemo(@jakarta.annotation.Nullable String blockchainMemo) {
    this.blockchainMemo = blockchainMemo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticMemoDestination staticMemoDestination = (StaticMemoDestination) o;
    return Objects.equals(this.currency, staticMemoDestination.currency) &&
        Objects.equals(this.paymentRail, staticMemoDestination.paymentRail) &&
        Objects.equals(this.address, staticMemoDestination.address) &&
        Objects.equals(this.bridgeWalletId, staticMemoDestination.bridgeWalletId) &&
        Objects.equals(this.blockchainMemo, staticMemoDestination.blockchainMemo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, paymentRail, address, bridgeWalletId, blockchainMemo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticMemoDestination {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentRail: ").append(toIndentedString(paymentRail)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    bridgeWalletId: ").append(toIndentedString(bridgeWalletId)).append("\n");
    sb.append("    blockchainMemo: ").append(toIndentedString(blockchainMemo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

