/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StaticMemoEventSourceDepositInstructions
 */
@JsonPropertyOrder({
  StaticMemoEventSourceDepositInstructions.JSON_PROPERTY_DEPOSIT_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class StaticMemoEventSourceDepositInstructions {
  public static final String JSON_PROPERTY_DEPOSIT_MESSAGE = "deposit_message";
  @jakarta.annotation.Nonnull
  private String depositMessage;

  public StaticMemoEventSourceDepositInstructions() {
  }

  public StaticMemoEventSourceDepositInstructions depositMessage(@jakarta.annotation.Nonnull String depositMessage) {
    
    this.depositMessage = depositMessage;
    return this;
  }

  /**
   * The message that the customer MUST include in their wire memo/message or ach push description
   * @return depositMessage
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEPOSIT_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDepositMessage() {
    return depositMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPOSIT_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepositMessage(@jakarta.annotation.Nonnull String depositMessage) {
    this.depositMessage = depositMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticMemoEventSourceDepositInstructions staticMemoEventSourceDepositInstructions = (StaticMemoEventSourceDepositInstructions) o;
    return Objects.equals(this.depositMessage, staticMemoEventSourceDepositInstructions.depositMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depositMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticMemoEventSourceDepositInstructions {\n");
    sb.append("    depositMessage: ").append(toIndentedString(depositMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

