/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jhely.money.sdk.bridge.model.EuroInclusiveFiatCurrency;
import org.jhely.money.sdk.bridge.model.Receipt;
import org.jhely.money.sdk.bridge.model.TransferResponse;
import org.jhely.money.sdk.bridge.model.TransferResponseDestination;
import org.jhely.money.sdk.bridge.model.TransferResponseSource;
import org.jhely.money.sdk.bridge.model.TransferResponseSourceDepositInstructions;
import org.jhely.money.sdk.bridge.model.TransferReturnDetails;
import org.jhely.money.sdk.bridge.model.TransferRouteResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransfersPost201Response
 */
@JsonPropertyOrder({
  TransfersPost201Response.JSON_PROPERTY_ID,
  TransfersPost201Response.JSON_PROPERTY_CLIENT_REFERENCE_ID,
  TransfersPost201Response.JSON_PROPERTY_AMOUNT,
  TransfersPost201Response.JSON_PROPERTY_CURRENCY,
  TransfersPost201Response.JSON_PROPERTY_ON_BEHALF_OF,
  TransfersPost201Response.JSON_PROPERTY_DEVELOPER_FEE,
  TransfersPost201Response.JSON_PROPERTY_DEVELOPER_FEE_PERCENT,
  TransfersPost201Response.JSON_PROPERTY_SOURCE,
  TransfersPost201Response.JSON_PROPERTY_DESTINATION,
  TransfersPost201Response.JSON_PROPERTY_STATE,
  TransfersPost201Response.JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS,
  TransfersPost201Response.JSON_PROPERTY_RECEIPT,
  TransfersPost201Response.JSON_PROPERTY_RETURN_DETAILS,
  TransfersPost201Response.JSON_PROPERTY_CREATED_AT,
  TransfersPost201Response.JSON_PROPERTY_UPDATED_AT,
  TransfersPost201Response.JSON_PROPERTY_NOTES
})
@JsonTypeName("_transfers_post_201_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TransfersPost201Response {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_CLIENT_REFERENCE_ID = "client_reference_id";
  @jakarta.annotation.Nullable
  private String clientReferenceId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private EuroInclusiveFiatCurrency currency;

  public static final String JSON_PROPERTY_ON_BEHALF_OF = "on_behalf_of";
  @jakarta.annotation.Nonnull
  private String onBehalfOf;

  public static final String JSON_PROPERTY_DEVELOPER_FEE = "developer_fee";
  @jakarta.annotation.Nonnull
  private String developerFee;

  public static final String JSON_PROPERTY_DEVELOPER_FEE_PERCENT = "developer_fee_percent";
  @jakarta.annotation.Nullable
  private String developerFeePercent;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull
  private TransferResponseSource source;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nonnull
  private TransferResponseDestination destination;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    VALID(String.valueOf("valid")),
    
    INVALID(String.valueOf("invalid"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nonnull
  private StateEnum state;

  public static final String JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS = "source_deposit_instructions";
  @jakarta.annotation.Nullable
  private TransferResponseSourceDepositInstructions sourceDepositInstructions;

  public static final String JSON_PROPERTY_RECEIPT = "receipt";
  @jakarta.annotation.Nonnull
  private Receipt receipt;

  public static final String JSON_PROPERTY_RETURN_DETAILS = "return_details";
  @jakarta.annotation.Nullable
  private TransferReturnDetails returnDetails;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_NOTES = "notes";
  @jakarta.annotation.Nonnull
  private List<String> notes = new ArrayList<>();

  public TransfersPost201Response() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public TransfersPost201Response(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public TransfersPost201Response id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public TransfersPost201Response clientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * A client-provided reference ID that uniquely identifies a resource in the client&#39;s system
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientReferenceId() {
    return clientReferenceId;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }

  public TransfersPost201Response amount(@jakarta.annotation.Nonnull String amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount of the transfer, expressed as a decimal string.  Examples include \&quot;100.25\&quot;, \&quot;0.1\&quot;, \&quot;1.234567\&quot;, \&quot;1.01\&quot; etc.  It is denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged.
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }

  public TransfersPost201Response currency(@jakarta.annotation.Nonnull EuroInclusiveFiatCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EuroInclusiveFiatCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull EuroInclusiveFiatCurrency currency) {
    this.currency = currency;
  }

  public TransfersPost201Response onBehalfOf(@jakarta.annotation.Nonnull String onBehalfOf) {
    
    this.onBehalfOf = onBehalfOf;
    return this;
  }

  /**
   * The id of the Bridge customer that you are moving funds on behalf of.
   * @return onBehalfOf
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ON_BEHALF_OF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOnBehalfOf() {
    return onBehalfOf;
  }


  @JsonProperty(value = JSON_PROPERTY_ON_BEHALF_OF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOnBehalfOf(@jakarta.annotation.Nonnull String onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
  }

  public TransfersPost201Response developerFee(@jakarta.annotation.Nonnull String developerFee) {
    
    this.developerFee = developerFee;
    return this;
  }

  /**
   * The fee, expressed as a decimal string, represents the amount you wish to reserve for your own account. This fee is the final amount deducted from what your customer ultimately receives, rather than a percentage.  It is denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged.
   * @return developerFee
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeveloperFee() {
    return developerFee;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeveloperFee(@jakarta.annotation.Nonnull String developerFee) {
    this.developerFee = developerFee;
  }

  public TransfersPost201Response developerFeePercent(@jakarta.annotation.Nullable String developerFeePercent) {
    
    this.developerFeePercent = developerFeePercent;
    return this;
  }

  /**
   * The fee percent, expressed as a decimal string from &#x60;0.0&#x60; to &#x60;100.0&#x60;, represents the percentage of the transfer you wish to reserve for your own account.  This field must be set instead of &#x60;developer_fee&#x60; when using [Flexible Amounts](https://apidocs.bridge.xyz/platform/orchestration/fees-and-mins/devfees#transfers-with-fixed-amounts).
   * @return developerFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeveloperFeePercent() {
    return developerFeePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperFeePercent(@jakarta.annotation.Nullable String developerFeePercent) {
    this.developerFeePercent = developerFeePercent;
  }

  public TransfersPost201Response source(@jakarta.annotation.Nonnull TransferResponseSource source) {
    
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransferResponseSource getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull TransferResponseSource source) {
    this.source = source;
  }

  public TransfersPost201Response destination(@jakarta.annotation.Nonnull TransferResponseDestination destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransferResponseDestination getDestination() {
    return destination;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(@jakarta.annotation.Nonnull TransferResponseDestination destination) {
    this.destination = destination;
  }

  public TransfersPost201Response state(@jakarta.annotation.Nonnull StateEnum state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@jakarta.annotation.Nonnull StateEnum state) {
    this.state = state;
  }

  public TransfersPost201Response sourceDepositInstructions(@jakarta.annotation.Nullable TransferResponseSourceDepositInstructions sourceDepositInstructions) {
    
    this.sourceDepositInstructions = sourceDepositInstructions;
    return this;
  }

  /**
   * Get sourceDepositInstructions
   * @return sourceDepositInstructions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TransferResponseSourceDepositInstructions getSourceDepositInstructions() {
    return sourceDepositInstructions;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_DEPOSIT_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceDepositInstructions(@jakarta.annotation.Nullable TransferResponseSourceDepositInstructions sourceDepositInstructions) {
    this.sourceDepositInstructions = sourceDepositInstructions;
  }

  public TransfersPost201Response receipt(@jakarta.annotation.Nonnull Receipt receipt) {
    
    this.receipt = receipt;
    return this;
  }

  /**
   * Get receipt
   * @return receipt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECEIPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Receipt getReceipt() {
    return receipt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceipt(@jakarta.annotation.Nonnull Receipt receipt) {
    this.receipt = receipt;
  }

  public TransfersPost201Response returnDetails(@jakarta.annotation.Nullable TransferReturnDetails returnDetails) {
    
    this.returnDetails = returnDetails;
    return this;
  }

  /**
   * Get returnDetails
   * @return returnDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETURN_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TransferReturnDetails getReturnDetails() {
    return returnDetails;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnDetails(@jakarta.annotation.Nullable TransferReturnDetails returnDetails) {
    this.returnDetails = returnDetails;
  }

  /**
   * Time of creation of the transfer
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * Time of update of the transfer
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }



  public TransfersPost201Response notes(@jakarta.annotation.Nonnull List<String> notes) {
    
    this.notes = notes;
    return this;
  }

  public TransfersPost201Response addNotesItem(String notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<>();
    }
    this.notes.add(notesItem);
    return this;
  }

  /**
   * Get notes
   * @return notes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getNotes() {
    return notes;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotes(@jakarta.annotation.Nonnull List<String> notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransfersPost201Response transfersPost201Response = (TransfersPost201Response) o;
    return Objects.equals(this.id, transfersPost201Response.id) &&
        Objects.equals(this.clientReferenceId, transfersPost201Response.clientReferenceId) &&
        Objects.equals(this.amount, transfersPost201Response.amount) &&
        Objects.equals(this.currency, transfersPost201Response.currency) &&
        Objects.equals(this.onBehalfOf, transfersPost201Response.onBehalfOf) &&
        Objects.equals(this.developerFee, transfersPost201Response.developerFee) &&
        Objects.equals(this.developerFeePercent, transfersPost201Response.developerFeePercent) &&
        Objects.equals(this.source, transfersPost201Response.source) &&
        Objects.equals(this.destination, transfersPost201Response.destination) &&
        Objects.equals(this.state, transfersPost201Response.state) &&
        Objects.equals(this.sourceDepositInstructions, transfersPost201Response.sourceDepositInstructions) &&
        Objects.equals(this.receipt, transfersPost201Response.receipt) &&
        Objects.equals(this.returnDetails, transfersPost201Response.returnDetails) &&
        Objects.equals(this.createdAt, transfersPost201Response.createdAt) &&
        Objects.equals(this.updatedAt, transfersPost201Response.updatedAt) &&
        Objects.equals(this.notes, transfersPost201Response.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientReferenceId, amount, currency, onBehalfOf, developerFee, developerFeePercent, source, destination, state, sourceDepositInstructions, receipt, returnDetails, createdAt, updatedAt, notes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransfersPost201Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    onBehalfOf: ").append(toIndentedString(onBehalfOf)).append("\n");
    sb.append("    developerFee: ").append(toIndentedString(developerFee)).append("\n");
    sb.append("    developerFeePercent: ").append(toIndentedString(developerFeePercent)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    sourceDepositInstructions: ").append(toIndentedString(sourceDepositInstructions)).append("\n");
    sb.append("    receipt: ").append(toIndentedString(receipt)).append("\n");
    sb.append("    returnDetails: ").append(toIndentedString(returnDetails)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

