/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.EuroInclusiveCurrency;
import org.jhely.money.sdk.bridge.model.SepaSwiftInclusivePaymentRail;
import org.jhely.money.sdk.bridge.model.SwiftCharges;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The destination of the transfer, which could be an external bank account, a bridge account, or a crypto wallet address
 */
@JsonPropertyOrder({
  TransferResponseDestination.JSON_PROPERTY_CURRENCY,
  TransferResponseDestination.JSON_PROPERTY_PAYMENT_RAIL,
  TransferResponseDestination.JSON_PROPERTY_EXTERNAL_ACCOUNT_ID,
  TransferResponseDestination.JSON_PROPERTY_BRIDGE_WALLET_ID,
  TransferResponseDestination.JSON_PROPERTY_OMAD,
  TransferResponseDestination.JSON_PROPERTY_IMAD,
  TransferResponseDestination.JSON_PROPERTY_TRACE_NUMBER,
  TransferResponseDestination.JSON_PROPERTY_WIRE_MESSAGE,
  TransferResponseDestination.JSON_PROPERTY_SEPA_REFERENCE,
  TransferResponseDestination.JSON_PROPERTY_SWIFT_REFERENCE,
  TransferResponseDestination.JSON_PROPERTY_SPEI_REFERENCE,
  TransferResponseDestination.JSON_PROPERTY_REFERENCE,
  TransferResponseDestination.JSON_PROPERTY_SWIFT_CHARGES,
  TransferResponseDestination.JSON_PROPERTY_ACH_REFERENCE,
  TransferResponseDestination.JSON_PROPERTY_UETR,
  TransferResponseDestination.JSON_PROPERTY_BLOCKCHAIN_MEMO,
  TransferResponseDestination.JSON_PROPERTY_DEPOSIT_ID,
  TransferResponseDestination.JSON_PROPERTY_TRACKING_NUMBER,
  TransferResponseDestination.JSON_PROPERTY_TRANSACTION_ID,
  TransferResponseDestination.JSON_PROPERTY_SENDING_INSTITUTION_NAME,
  TransferResponseDestination.JSON_PROPERTY_TO_ADDRESS
})
@JsonTypeName("TransferResponse_destination")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TransferResponseDestination {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private EuroInclusiveCurrency currency;

  public static final String JSON_PROPERTY_PAYMENT_RAIL = "payment_rail";
  @jakarta.annotation.Nonnull
  private SepaSwiftInclusivePaymentRail paymentRail;

  public static final String JSON_PROPERTY_EXTERNAL_ACCOUNT_ID = "external_account_id";
  @jakarta.annotation.Nullable
  private String externalAccountId;

  public static final String JSON_PROPERTY_BRIDGE_WALLET_ID = "bridge_wallet_id";
  @jakarta.annotation.Nullable
  private String bridgeWalletId;

  public static final String JSON_PROPERTY_OMAD = "omad";
  @jakarta.annotation.Nullable
  private String omad;

  public static final String JSON_PROPERTY_IMAD = "imad";
  @jakarta.annotation.Nullable
  private String imad;

  public static final String JSON_PROPERTY_TRACE_NUMBER = "trace_number";
  @jakarta.annotation.Nullable
  private String traceNumber;

  public static final String JSON_PROPERTY_WIRE_MESSAGE = "wire_message";
  @jakarta.annotation.Nullable
  private String wireMessage;

  public static final String JSON_PROPERTY_SEPA_REFERENCE = "sepa_reference";
  @jakarta.annotation.Nullable
  private String sepaReference;

  public static final String JSON_PROPERTY_SWIFT_REFERENCE = "swift_reference";
  @jakarta.annotation.Nullable
  private String swiftReference;

  public static final String JSON_PROPERTY_SPEI_REFERENCE = "spei_reference";
  @jakarta.annotation.Nullable
  private String speiReference;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  @jakarta.annotation.Nullable
  private String reference;

  public static final String JSON_PROPERTY_SWIFT_CHARGES = "swift_charges";
  @jakarta.annotation.Nullable
  private SwiftCharges swiftCharges;

  public static final String JSON_PROPERTY_ACH_REFERENCE = "ach_reference";
  @jakarta.annotation.Nullable
  private String achReference;

  public static final String JSON_PROPERTY_UETR = "uetr";
  @jakarta.annotation.Nullable
  private String uetr;

  public static final String JSON_PROPERTY_BLOCKCHAIN_MEMO = "blockchain_memo";
  @jakarta.annotation.Nullable
  private String blockchainMemo;

  public static final String JSON_PROPERTY_DEPOSIT_ID = "deposit_id";
  @jakarta.annotation.Nullable
  private String depositId;

  public static final String JSON_PROPERTY_TRACKING_NUMBER = "tracking_number";
  @jakarta.annotation.Nullable
  private String trackingNumber;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transaction_id";
  @jakarta.annotation.Nullable
  private String transactionId;

  public static final String JSON_PROPERTY_SENDING_INSTITUTION_NAME = "sending_institution_name";
  @jakarta.annotation.Nullable
  private String sendingInstitutionName;

  public static final String JSON_PROPERTY_TO_ADDRESS = "to_address";
  @jakarta.annotation.Nullable
  private String toAddress;

  public TransferResponseDestination() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public TransferResponseDestination(
    @JsonProperty(JSON_PROPERTY_UETR) String uetr, 
    @JsonProperty(JSON_PROPERTY_SENDING_INSTITUTION_NAME) String sendingInstitutionName
  ) {
    this();
    this.uetr = uetr;
    this.sendingInstitutionName = sendingInstitutionName;
  }

  public TransferResponseDestination currency(@jakarta.annotation.Nonnull EuroInclusiveCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EuroInclusiveCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull EuroInclusiveCurrency currency) {
    this.currency = currency;
  }

  public TransferResponseDestination paymentRail(@jakarta.annotation.Nonnull SepaSwiftInclusivePaymentRail paymentRail) {
    
    this.paymentRail = paymentRail;
    return this;
  }

  /**
   * Get paymentRail
   * @return paymentRail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SepaSwiftInclusivePaymentRail getPaymentRail() {
    return paymentRail;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRail(@jakarta.annotation.Nonnull SepaSwiftInclusivePaymentRail paymentRail) {
    this.paymentRail = paymentRail;
  }

  public TransferResponseDestination externalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    
    this.externalAccountId = externalAccountId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return externalAccountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalAccountId() {
    return externalAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public TransferResponseDestination bridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    
    this.bridgeWalletId = bridgeWalletId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return bridgeWalletId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBridgeWalletId() {
    return bridgeWalletId;
  }


  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    this.bridgeWalletId = bridgeWalletId;
  }

  public TransferResponseDestination omad(@jakarta.annotation.Nullable String omad) {
    
    this.omad = omad;
    return this;
  }

  /**
   * (Wire only) The OMAD of a wire transfer, if available
   * @return omad
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOmad() {
    return omad;
  }


  @JsonProperty(value = JSON_PROPERTY_OMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOmad(@jakarta.annotation.Nullable String omad) {
    this.omad = omad;
  }

  public TransferResponseDestination imad(@jakarta.annotation.Nullable String imad) {
    
    this.imad = imad;
    return this;
  }

  /**
   * (Wire only) The IMAD of a wire transfer, if available
   * @return imad
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImad() {
    return imad;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImad(@jakarta.annotation.Nullable String imad) {
    this.imad = imad;
  }

  public TransferResponseDestination traceNumber(@jakarta.annotation.Nullable String traceNumber) {
    
    this.traceNumber = traceNumber;
    return this;
  }

  /**
   * The trace number of an ACH transfer
   * @return traceNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTraceNumber() {
    return traceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTraceNumber(@jakarta.annotation.Nullable String traceNumber) {
    this.traceNumber = traceNumber;
  }

  public TransferResponseDestination wireMessage(@jakarta.annotation.Nullable String wireMessage) {
    
    this.wireMessage = wireMessage;
    return this;
  }

  /**
   * A message to be sent with a wire transfer, only allowed when the payment rail is a wire.  This message will be validated against 4 lines, each with a max length of 35 char according to the Fedwire standard.
   * @return wireMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWireMessage() {
    return wireMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWireMessage(@jakarta.annotation.Nullable String wireMessage) {
    this.wireMessage = wireMessage;
  }

  public TransferResponseDestination sepaReference(@jakarta.annotation.Nullable String sepaReference) {
    
    this.sepaReference = sepaReference;
    return this;
  }

  /**
   * A reference message to be sent with a SEPA transaction. We recommend you set a unique value to help you and your customers track payments end to end. It must be from 6 to 140 characters. The allowed characters are &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, spaces, ampersand (&#x60;&amp;&#x60;), hyphen (&#x60;-&#x60;), full stop (&#x60;.&#x60;), and solidus (&#x60;/&#x60;). If not populated, the default value is \&quot;Payment via Bridge {unique_token}\&quot;.
   * @return sepaReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSepaReference() {
    return sepaReference;
  }


  @JsonProperty(value = JSON_PROPERTY_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSepaReference(@jakarta.annotation.Nullable String sepaReference) {
    this.sepaReference = sepaReference;
  }

  public TransferResponseDestination swiftReference(@jakarta.annotation.Nullable String swiftReference) {
    
    this.swiftReference = swiftReference;
    return this;
  }

  /**
   * A payment reference message or remittance information to be included in a SWIFT transaction. It can have at most 4 lines (separated by \&quot;\\n\&quot;), each line with a max length of 35 chars. The allowed characters are &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, special characters (&#x60;/&#x60; &#x60;-&#x60; &#x60;?&#x60; &#x60;:&#x60; &#x60;(&#x60; &#x60;)&#x60; &#x60;.&#x60; &#x60;,&#x60; &#x60;&#39;&#x60; &#x60;+&#x60;), and space
   * @return swiftReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SWIFT_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSwiftReference() {
    return swiftReference;
  }


  @JsonProperty(value = JSON_PROPERTY_SWIFT_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSwiftReference(@jakarta.annotation.Nullable String swiftReference) {
    this.swiftReference = swiftReference;
  }

  public TransferResponseDestination speiReference(@jakarta.annotation.Nullable String speiReference) {
    
    this.speiReference = speiReference;
    return this;
  }

  /**
   * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, and space
   * @return speiReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpeiReference() {
    return speiReference;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeiReference(@jakarta.annotation.Nullable String speiReference) {
    this.speiReference = speiReference;
  }

  public TransferResponseDestination reference(@jakarta.annotation.Nullable String reference) {
    
    this.reference = reference;
    return this;
  }

  /**
   * A payment reference message for newer payment rails (e.g. PIX).
   * @return reference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReference() {
    return reference;
  }


  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference(@jakarta.annotation.Nullable String reference) {
    this.reference = reference;
  }

  public TransferResponseDestination swiftCharges(@jakarta.annotation.Nullable SwiftCharges swiftCharges) {
    
    this.swiftCharges = swiftCharges;
    return this;
  }

  /**
   * Get swiftCharges
   * @return swiftCharges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SWIFT_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SwiftCharges getSwiftCharges() {
    return swiftCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_SWIFT_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSwiftCharges(@jakarta.annotation.Nullable SwiftCharges swiftCharges) {
    this.swiftCharges = swiftCharges;
  }

  public TransferResponseDestination achReference(@jakarta.annotation.Nullable String achReference) {
    
    this.achReference = achReference;
    return this;
  }

  /**
   * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
   * @return achReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAchReference() {
    return achReference;
  }


  @JsonProperty(value = JSON_PROPERTY_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAchReference(@jakarta.annotation.Nullable String achReference) {
    this.achReference = achReference;
  }

  /**
   * The UETR of this SEPA transaction, for tracing purposes.
   * @return uetr
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UETR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUetr() {
    return uetr;
  }



  public TransferResponseDestination blockchainMemo(@jakarta.annotation.Nullable String blockchainMemo) {
    
    this.blockchainMemo = blockchainMemo;
    return this;
  }

  /**
   * A message to be sent with a crypto transaction, only allowed when the payment rail is Stellar.
   * @return blockchainMemo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBlockchainMemo() {
    return blockchainMemo;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCKCHAIN_MEMO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockchainMemo(@jakarta.annotation.Nullable String blockchainMemo) {
    this.blockchainMemo = blockchainMemo;
  }

  public TransferResponseDestination depositId(@jakarta.annotation.Nullable String depositId) {
    
    this.depositId = depositId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a deposit
   * @return depositId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPOSIT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDepositId() {
    return depositId;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPOSIT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepositId(@jakarta.annotation.Nullable String depositId) {
    this.depositId = depositId;
  }

  public TransferResponseDestination trackingNumber(@jakarta.annotation.Nullable String trackingNumber) {
    
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * The clave de rastreo or tracking number of a SPEI transaction
   * @return trackingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingNumber() {
    return trackingNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingNumber(@jakarta.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public TransferResponseDestination transactionId(@jakarta.annotation.Nullable String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

  /**
   * The unique transaction identifier for a PIX transaction
   * @return transactionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@jakarta.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }

  /**
   * The name of the institution sending the funds
   * @return sendingInstitutionName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDING_INSTITUTION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSendingInstitutionName() {
    return sendingInstitutionName;
  }



  public TransferResponseDestination toAddress(@jakarta.annotation.Nullable String toAddress) {
    
    this.toAddress = toAddress;
    return this;
  }

  /**
   * The crypto wallet address that the customer wishes to ultimately receive funds at, in order to complete this transfer
   * @return toAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToAddress() {
    return toAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToAddress(@jakarta.annotation.Nullable String toAddress) {
    this.toAddress = toAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferResponseDestination transferResponseDestination = (TransferResponseDestination) o;
    return Objects.equals(this.currency, transferResponseDestination.currency) &&
        Objects.equals(this.paymentRail, transferResponseDestination.paymentRail) &&
        Objects.equals(this.externalAccountId, transferResponseDestination.externalAccountId) &&
        Objects.equals(this.bridgeWalletId, transferResponseDestination.bridgeWalletId) &&
        Objects.equals(this.omad, transferResponseDestination.omad) &&
        Objects.equals(this.imad, transferResponseDestination.imad) &&
        Objects.equals(this.traceNumber, transferResponseDestination.traceNumber) &&
        Objects.equals(this.wireMessage, transferResponseDestination.wireMessage) &&
        Objects.equals(this.sepaReference, transferResponseDestination.sepaReference) &&
        Objects.equals(this.swiftReference, transferResponseDestination.swiftReference) &&
        Objects.equals(this.speiReference, transferResponseDestination.speiReference) &&
        Objects.equals(this.reference, transferResponseDestination.reference) &&
        Objects.equals(this.swiftCharges, transferResponseDestination.swiftCharges) &&
        Objects.equals(this.achReference, transferResponseDestination.achReference) &&
        Objects.equals(this.uetr, transferResponseDestination.uetr) &&
        Objects.equals(this.blockchainMemo, transferResponseDestination.blockchainMemo) &&
        Objects.equals(this.depositId, transferResponseDestination.depositId) &&
        Objects.equals(this.trackingNumber, transferResponseDestination.trackingNumber) &&
        Objects.equals(this.transactionId, transferResponseDestination.transactionId) &&
        Objects.equals(this.sendingInstitutionName, transferResponseDestination.sendingInstitutionName) &&
        Objects.equals(this.toAddress, transferResponseDestination.toAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, paymentRail, externalAccountId, bridgeWalletId, omad, imad, traceNumber, wireMessage, sepaReference, swiftReference, speiReference, reference, swiftCharges, achReference, uetr, blockchainMemo, depositId, trackingNumber, transactionId, sendingInstitutionName, toAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferResponseDestination {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentRail: ").append(toIndentedString(paymentRail)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    bridgeWalletId: ").append(toIndentedString(bridgeWalletId)).append("\n");
    sb.append("    omad: ").append(toIndentedString(omad)).append("\n");
    sb.append("    imad: ").append(toIndentedString(imad)).append("\n");
    sb.append("    traceNumber: ").append(toIndentedString(traceNumber)).append("\n");
    sb.append("    wireMessage: ").append(toIndentedString(wireMessage)).append("\n");
    sb.append("    sepaReference: ").append(toIndentedString(sepaReference)).append("\n");
    sb.append("    swiftReference: ").append(toIndentedString(swiftReference)).append("\n");
    sb.append("    speiReference: ").append(toIndentedString(speiReference)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    swiftCharges: ").append(toIndentedString(swiftCharges)).append("\n");
    sb.append("    achReference: ").append(toIndentedString(achReference)).append("\n");
    sb.append("    uetr: ").append(toIndentedString(uetr)).append("\n");
    sb.append("    blockchainMemo: ").append(toIndentedString(blockchainMemo)).append("\n");
    sb.append("    depositId: ").append(toIndentedString(depositId)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    sendingInstitutionName: ").append(toIndentedString(sendingInstitutionName)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

