/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.TransferRequestDestination;
import org.jhely.money.sdk.bridge.model.TransferRequestFeatures;
import org.jhely.money.sdk.bridge.model.TransferRequestSource;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransferRequest
 */
@JsonPropertyOrder({
  TransferRequest.JSON_PROPERTY_ID,
  TransferRequest.JSON_PROPERTY_CLIENT_REFERENCE_ID,
  TransferRequest.JSON_PROPERTY_AMOUNT,
  TransferRequest.JSON_PROPERTY_ON_BEHALF_OF,
  TransferRequest.JSON_PROPERTY_DEVELOPER_FEE,
  TransferRequest.JSON_PROPERTY_DEVELOPER_FEE_PERCENT,
  TransferRequest.JSON_PROPERTY_DRY_RUN,
  TransferRequest.JSON_PROPERTY_SOURCE,
  TransferRequest.JSON_PROPERTY_DESTINATION,
  TransferRequest.JSON_PROPERTY_FEATURES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TransferRequest {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_CLIENT_REFERENCE_ID = "client_reference_id";
  @jakarta.annotation.Nullable
  private String clientReferenceId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nullable
  private String amount;

  public static final String JSON_PROPERTY_ON_BEHALF_OF = "on_behalf_of";
  @jakarta.annotation.Nonnull
  private String onBehalfOf;

  public static final String JSON_PROPERTY_DEVELOPER_FEE = "developer_fee";
  @jakarta.annotation.Nullable
  private String developerFee;

  public static final String JSON_PROPERTY_DEVELOPER_FEE_PERCENT = "developer_fee_percent";
  @jakarta.annotation.Nullable
  private String developerFeePercent;

  public static final String JSON_PROPERTY_DRY_RUN = "dry_run";
  @jakarta.annotation.Nullable
  private Boolean dryRun;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull
  private TransferRequestSource source;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nonnull
  private TransferRequestDestination destination;

  public static final String JSON_PROPERTY_FEATURES = "features";
  @jakarta.annotation.Nullable
  private TransferRequestFeatures features;

  public TransferRequest() {
  }

  public TransferRequest id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public TransferRequest clientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * A client-provided reference ID that uniquely identifies a resource in the client&#39;s system
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientReferenceId() {
    return clientReferenceId;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }

  public TransferRequest amount(@jakarta.annotation.Nullable String amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount of the transfer, expressed as a decimal string.  Examples include \&quot;100.25\&quot;, \&quot;0.1\&quot;, \&quot;1.234567\&quot;, \&quot;1.01\&quot; etc.  It is denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged.
   * @return amount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@jakarta.annotation.Nullable String amount) {
    this.amount = amount;
  }

  public TransferRequest onBehalfOf(@jakarta.annotation.Nonnull String onBehalfOf) {
    
    this.onBehalfOf = onBehalfOf;
    return this;
  }

  /**
   * The id of the Bridge customer that you are moving funds on behalf of.
   * @return onBehalfOf
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ON_BEHALF_OF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOnBehalfOf() {
    return onBehalfOf;
  }


  @JsonProperty(value = JSON_PROPERTY_ON_BEHALF_OF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOnBehalfOf(@jakarta.annotation.Nonnull String onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
  }

  public TransferRequest developerFee(@jakarta.annotation.Nullable String developerFee) {
    
    this.developerFee = developerFee;
    return this;
  }

  /**
   * The fee, expressed as a decimal string, represents the amount you wish to reserve for your own account.  This fee is the final amount deducted from what your customer ultimately receives, rather than a percentage.  It is denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged.
   * @return developerFee
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeveloperFee() {
    return developerFee;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperFee(@jakarta.annotation.Nullable String developerFee) {
    this.developerFee = developerFee;
  }

  public TransferRequest developerFeePercent(@jakarta.annotation.Nullable String developerFeePercent) {
    
    this.developerFeePercent = developerFeePercent;
    return this;
  }

  /**
   * The fee percent, expressed as a decimal string from &#x60;0.0&#x60; to &#x60;100.0&#x60;, represents the percentage of the transfer you wish to reserve for your own account.  This field must be set instead of &#x60;developer_fee&#x60; when using [Flexible Amounts](https://apidocs.bridge.xyz/platform/orchestration/fees-and-mins/devfees#transfers-with-fixed-amounts).
   * @return developerFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeveloperFeePercent() {
    return developerFeePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperFeePercent(@jakarta.annotation.Nullable String developerFeePercent) {
    this.developerFeePercent = developerFeePercent;
  }

  public TransferRequest dryRun(@jakarta.annotation.Nullable Boolean dryRun) {
    
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Whether to validate the transfer route without creating a transfer. If set to true, a valid transfer will return a &#x60;TransferRouteResponse&#x60; indicating the transfer would have been valid. The same error response will be returned for an invalid transfer as in the non-dry-run case.
   * @return dryRun
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DRY_RUN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDryRun() {
    return dryRun;
  }


  @JsonProperty(value = JSON_PROPERTY_DRY_RUN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDryRun(@jakarta.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
  }

  public TransferRequest source(@jakarta.annotation.Nonnull TransferRequestSource source) {
    
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransferRequestSource getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull TransferRequestSource source) {
    this.source = source;
  }

  public TransferRequest destination(@jakarta.annotation.Nonnull TransferRequestDestination destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransferRequestDestination getDestination() {
    return destination;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(@jakarta.annotation.Nonnull TransferRequestDestination destination) {
    this.destination = destination;
  }

  public TransferRequest features(@jakarta.annotation.Nullable TransferRequestFeatures features) {
    
    this.features = features;
    return this;
  }

  /**
   * Get features
   * @return features
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEATURES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TransferRequestFeatures getFeatures() {
    return features;
  }


  @JsonProperty(value = JSON_PROPERTY_FEATURES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatures(@jakarta.annotation.Nullable TransferRequestFeatures features) {
    this.features = features;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferRequest transferRequest = (TransferRequest) o;
    return Objects.equals(this.id, transferRequest.id) &&
        Objects.equals(this.clientReferenceId, transferRequest.clientReferenceId) &&
        Objects.equals(this.amount, transferRequest.amount) &&
        Objects.equals(this.onBehalfOf, transferRequest.onBehalfOf) &&
        Objects.equals(this.developerFee, transferRequest.developerFee) &&
        Objects.equals(this.developerFeePercent, transferRequest.developerFeePercent) &&
        Objects.equals(this.dryRun, transferRequest.dryRun) &&
        Objects.equals(this.source, transferRequest.source) &&
        Objects.equals(this.destination, transferRequest.destination) &&
        Objects.equals(this.features, transferRequest.features);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientReferenceId, amount, onBehalfOf, developerFee, developerFeePercent, dryRun, source, destination, features);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    onBehalfOf: ").append(toIndentedString(onBehalfOf)).append("\n");
    sb.append("    developerFee: ").append(toIndentedString(developerFee)).append("\n");
    sb.append("    developerFeePercent: ").append(toIndentedString(developerFeePercent)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

