/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jhely.money.sdk.bridge.model.BridgeWalletSepaSwiftInclusivePaymentRail;
import org.jhely.money.sdk.bridge.model.EuroInclusiveCurrency;
import org.jhely.money.sdk.bridge.model.PaymentScheme;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransferSource
 */
@JsonPropertyOrder({
  TransferSource.JSON_PROPERTY_CURRENCY,
  TransferSource.JSON_PROPERTY_PAYMENT_RAIL,
  TransferSource.JSON_PROPERTY_PAYMENT_SCHEME,
  TransferSource.JSON_PROPERTY_EXTERNAL_ACCOUNT_ID,
  TransferSource.JSON_PROPERTY_OMAD,
  TransferSource.JSON_PROPERTY_IMAD,
  TransferSource.JSON_PROPERTY_BANK_BENEFICIARY_NAME,
  TransferSource.JSON_PROPERTY_BANK_BENEFICIARY_ADDRESS,
  TransferSource.JSON_PROPERTY_BANK_ROUTING_NUMBER,
  TransferSource.JSON_PROPERTY_BANK_NAME,
  TransferSource.JSON_PROPERTY_ORIGINATOR_NAME,
  TransferSource.JSON_PROPERTY_ORIGINATOR_ADDRESS,
  TransferSource.JSON_PROPERTY_WIRE_MESSAGE,
  TransferSource.JSON_PROPERTY_BRIDGE_WALLET_ID,
  TransferSource.JSON_PROPERTY_SENDER_NAME,
  TransferSource.JSON_PROPERTY_SENDER_BANK_ROUTING_NUMBER,
  TransferSource.JSON_PROPERTY_DESCRIPTION,
  TransferSource.JSON_PROPERTY_TRACKING_NUMBER,
  TransferSource.JSON_PROPERTY_TRANSACTION_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TransferSource {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private EuroInclusiveCurrency currency;

  public static final String JSON_PROPERTY_PAYMENT_RAIL = "payment_rail";
  @jakarta.annotation.Nonnull
  private BridgeWalletSepaSwiftInclusivePaymentRail paymentRail;

  public static final String JSON_PROPERTY_PAYMENT_SCHEME = "payment_scheme";
  @jakarta.annotation.Nullable
  private PaymentScheme paymentScheme;

  public static final String JSON_PROPERTY_EXTERNAL_ACCOUNT_ID = "external_account_id";
  @jakarta.annotation.Nullable
  private String externalAccountId;

  public static final String JSON_PROPERTY_OMAD = "omad";
  @jakarta.annotation.Nullable
  private String omad;

  public static final String JSON_PROPERTY_IMAD = "imad";
  @jakarta.annotation.Nullable
  private String imad;

  public static final String JSON_PROPERTY_BANK_BENEFICIARY_NAME = "bank_beneficiary_name";
  @jakarta.annotation.Nullable
  private String bankBeneficiaryName;

  public static final String JSON_PROPERTY_BANK_BENEFICIARY_ADDRESS = "bank_beneficiary_address";
  @jakarta.annotation.Nullable
  private String bankBeneficiaryAddress;

  public static final String JSON_PROPERTY_BANK_ROUTING_NUMBER = "bank_routing_number";
  @jakarta.annotation.Nullable
  private String bankRoutingNumber;

  public static final String JSON_PROPERTY_BANK_NAME = "bank_name";
  @jakarta.annotation.Nullable
  private String bankName;

  public static final String JSON_PROPERTY_ORIGINATOR_NAME = "originator_name";
  @jakarta.annotation.Nullable
  private String originatorName;

  public static final String JSON_PROPERTY_ORIGINATOR_ADDRESS = "originator_address";
  @jakarta.annotation.Nullable
  private String originatorAddress;

  public static final String JSON_PROPERTY_WIRE_MESSAGE = "wire_message";
  @jakarta.annotation.Nullable
  private String wireMessage;

  public static final String JSON_PROPERTY_BRIDGE_WALLET_ID = "bridge_wallet_id";
  @jakarta.annotation.Nullable
  private String bridgeWalletId;

  public static final String JSON_PROPERTY_SENDER_NAME = "sender_name";
  @jakarta.annotation.Nullable
  private String senderName;

  public static final String JSON_PROPERTY_SENDER_BANK_ROUTING_NUMBER = "sender_bank_routing_number";
  @jakarta.annotation.Nullable
  private String senderBankRoutingNumber;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TRACKING_NUMBER = "tracking_number";
  @jakarta.annotation.Nullable
  private String trackingNumber;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transaction_id";
  @jakarta.annotation.Nullable
  private String transactionId;

  public TransferSource() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public TransferSource(
    @JsonProperty(JSON_PROPERTY_BANK_BENEFICIARY_NAME) String bankBeneficiaryName, 
    @JsonProperty(JSON_PROPERTY_BANK_BENEFICIARY_ADDRESS) String bankBeneficiaryAddress, 
    @JsonProperty(JSON_PROPERTY_BANK_ROUTING_NUMBER) String bankRoutingNumber, 
    @JsonProperty(JSON_PROPERTY_BANK_NAME) String bankName, 
    @JsonProperty(JSON_PROPERTY_ORIGINATOR_NAME) String originatorName, 
    @JsonProperty(JSON_PROPERTY_ORIGINATOR_ADDRESS) String originatorAddress, 
    @JsonProperty(JSON_PROPERTY_WIRE_MESSAGE) String wireMessage, 
    @JsonProperty(JSON_PROPERTY_SENDER_NAME) String senderName, 
    @JsonProperty(JSON_PROPERTY_SENDER_BANK_ROUTING_NUMBER) String senderBankRoutingNumber, 
    @JsonProperty(JSON_PROPERTY_DESCRIPTION) String description
  ) {
    this();
    this.bankBeneficiaryName = bankBeneficiaryName;
    this.bankBeneficiaryAddress = bankBeneficiaryAddress;
    this.bankRoutingNumber = bankRoutingNumber;
    this.bankName = bankName;
    this.originatorName = originatorName;
    this.originatorAddress = originatorAddress;
    this.wireMessage = wireMessage;
    this.senderName = senderName;
    this.senderBankRoutingNumber = senderBankRoutingNumber;
    this.description = description;
  }

  public TransferSource currency(@jakarta.annotation.Nonnull EuroInclusiveCurrency currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EuroInclusiveCurrency getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull EuroInclusiveCurrency currency) {
    this.currency = currency;
  }

  public TransferSource paymentRail(@jakarta.annotation.Nonnull BridgeWalletSepaSwiftInclusivePaymentRail paymentRail) {
    
    this.paymentRail = paymentRail;
    return this;
  }

  /**
   * Get paymentRail
   * @return paymentRail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BridgeWalletSepaSwiftInclusivePaymentRail getPaymentRail() {
    return paymentRail;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_RAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRail(@jakarta.annotation.Nonnull BridgeWalletSepaSwiftInclusivePaymentRail paymentRail) {
    this.paymentRail = paymentRail;
  }

  public TransferSource paymentScheme(@jakarta.annotation.Nullable PaymentScheme paymentScheme) {
    
    this.paymentScheme = paymentScheme;
    return this;
  }

  /**
   * Get paymentScheme
   * @return paymentScheme
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_SCHEME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentScheme getPaymentScheme() {
    return paymentScheme;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_SCHEME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentScheme(@jakarta.annotation.Nullable PaymentScheme paymentScheme) {
    this.paymentScheme = paymentScheme;
  }

  public TransferSource externalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    
    this.externalAccountId = externalAccountId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return externalAccountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalAccountId() {
    return externalAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public TransferSource omad(@jakarta.annotation.Nullable String omad) {
    
    this.omad = omad;
    return this;
  }

  /**
   * (Wire only) The OMAD of a wire transfer, if available
   * @return omad
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOmad() {
    return omad;
  }


  @JsonProperty(value = JSON_PROPERTY_OMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOmad(@jakarta.annotation.Nullable String omad) {
    this.omad = omad;
  }

  public TransferSource imad(@jakarta.annotation.Nullable String imad) {
    
    this.imad = imad;
    return this;
  }

  /**
   * (Wire only) The IMAD of a wire transfer, if available
   * @return imad
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImad() {
    return imad;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImad(@jakarta.annotation.Nullable String imad) {
    this.imad = imad;
  }

  /**
   * (Wire only) The name of the beneficiary of the bank account that the customer sent the deposit to
   * @return bankBeneficiaryName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_BENEFICIARY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBankBeneficiaryName() {
    return bankBeneficiaryName;
  }



  /**
   * (Wire only) The address of the beneficiary of the bank account that the customer sent the deposit to
   * @return bankBeneficiaryAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_BENEFICIARY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBankBeneficiaryAddress() {
    return bankBeneficiaryAddress;
  }



  /**
   * (Wire only) The routing number of the bank that the customer sent the deposit to
   * @return bankRoutingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_ROUTING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBankRoutingNumber() {
    return bankRoutingNumber;
  }



  /**
   * (Wire only) The name of the bank that the customer sent the deposit to
   * @return bankName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBankName() {
    return bankName;
  }



  /**
   * (Wire only) The originator name of this wire
   * @return originatorName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINATOR_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginatorName() {
    return originatorName;
  }



  /**
   * (Wire only) The originator address of this wire
   * @return originatorAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINATOR_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginatorAddress() {
    return originatorAddress;
  }



  /**
   * (Wire only) The memo for this wire
   * @return wireMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWireMessage() {
    return wireMessage;
  }



  public TransferSource bridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    
    this.bridgeWalletId = bridgeWalletId;
    return this;
  }

  /**
   * A UUID that uniquely identifies a resource
   * @return bridgeWalletId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBridgeWalletId() {
    return bridgeWalletId;
  }


  @JsonProperty(value = JSON_PROPERTY_BRIDGE_WALLET_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBridgeWalletId(@jakarta.annotation.Nullable String bridgeWalletId) {
    this.bridgeWalletId = bridgeWalletId;
  }

  /**
   * (ACH only) The name of the business or individual who initiated the transaction
   * @return senderName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSenderName() {
    return senderName;
  }



  /**
   * (ACH only) The routing number of the entity that initiated this ACH transaction
   * @return senderBankRoutingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_BANK_ROUTING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSenderBankRoutingNumber() {
    return senderBankRoutingNumber;
  }



  /**
   * (ACH only) The description of the deposit that the customer sent
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }



  public TransferSource trackingNumber(@jakarta.annotation.Nullable String trackingNumber) {
    
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * The clave de rastreo or tracking number of a SPEI transaction
   * @return trackingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingNumber() {
    return trackingNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingNumber(@jakarta.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public TransferSource transactionId(@jakarta.annotation.Nullable String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

  /**
   * The unique transaction identifier for a PIX transaction
   * @return transactionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@jakarta.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferSource transferSource = (TransferSource) o;
    return Objects.equals(this.currency, transferSource.currency) &&
        Objects.equals(this.paymentRail, transferSource.paymentRail) &&
        Objects.equals(this.paymentScheme, transferSource.paymentScheme) &&
        Objects.equals(this.externalAccountId, transferSource.externalAccountId) &&
        Objects.equals(this.omad, transferSource.omad) &&
        Objects.equals(this.imad, transferSource.imad) &&
        Objects.equals(this.bankBeneficiaryName, transferSource.bankBeneficiaryName) &&
        Objects.equals(this.bankBeneficiaryAddress, transferSource.bankBeneficiaryAddress) &&
        Objects.equals(this.bankRoutingNumber, transferSource.bankRoutingNumber) &&
        Objects.equals(this.bankName, transferSource.bankName) &&
        Objects.equals(this.originatorName, transferSource.originatorName) &&
        Objects.equals(this.originatorAddress, transferSource.originatorAddress) &&
        Objects.equals(this.wireMessage, transferSource.wireMessage) &&
        Objects.equals(this.bridgeWalletId, transferSource.bridgeWalletId) &&
        Objects.equals(this.senderName, transferSource.senderName) &&
        Objects.equals(this.senderBankRoutingNumber, transferSource.senderBankRoutingNumber) &&
        Objects.equals(this.description, transferSource.description) &&
        Objects.equals(this.trackingNumber, transferSource.trackingNumber) &&
        Objects.equals(this.transactionId, transferSource.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, paymentRail, paymentScheme, externalAccountId, omad, imad, bankBeneficiaryName, bankBeneficiaryAddress, bankRoutingNumber, bankName, originatorName, originatorAddress, wireMessage, bridgeWalletId, senderName, senderBankRoutingNumber, description, trackingNumber, transactionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferSource {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentRail: ").append(toIndentedString(paymentRail)).append("\n");
    sb.append("    paymentScheme: ").append(toIndentedString(paymentScheme)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    omad: ").append(toIndentedString(omad)).append("\n");
    sb.append("    imad: ").append(toIndentedString(imad)).append("\n");
    sb.append("    bankBeneficiaryName: ").append(toIndentedString(bankBeneficiaryName)).append("\n");
    sb.append("    bankBeneficiaryAddress: ").append(toIndentedString(bankBeneficiaryAddress)).append("\n");
    sb.append("    bankRoutingNumber: ").append(toIndentedString(bankRoutingNumber)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    originatorName: ").append(toIndentedString(originatorName)).append("\n");
    sb.append("    originatorAddress: ").append(toIndentedString(originatorAddress)).append("\n");
    sb.append("    wireMessage: ").append(toIndentedString(wireMessage)).append("\n");
    sb.append("    bridgeWalletId: ").append(toIndentedString(bridgeWalletId)).append("\n");
    sb.append("    senderName: ").append(toIndentedString(senderName)).append("\n");
    sb.append("    senderBankRoutingNumber: ").append(toIndentedString(senderBankRoutingNumber)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

