/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UnknownBankAccount
 */
@JsonPropertyOrder({
  UnknownBankAccount.JSON_PROPERTY_ACCOUNT_NUMBER,
  UnknownBankAccount.JSON_PROPERTY_BIC,
  UnknownBankAccount.JSON_PROPERTY_LAST4
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UnknownBankAccount {
  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account_number";
  @jakarta.annotation.Nonnull
  private String accountNumber;

  public static final String JSON_PROPERTY_BIC = "bic";
  @jakarta.annotation.Nonnull
  private String bic;

  public static final String JSON_PROPERTY_LAST4 = "last_4";
  @jakarta.annotation.Nullable
  private String last4;

  public UnknownBankAccount() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public UnknownBankAccount(
    @JsonProperty(JSON_PROPERTY_LAST4) String last4
  ) {
    this();
    this.last4 = last4;
  }

  public UnknownBankAccount accountNumber(@jakarta.annotation.Nonnull String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

  /**
   * The number of the bank account
   * @return accountNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountNumber(@jakarta.annotation.Nonnull String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public UnknownBankAccount bic(@jakarta.annotation.Nonnull String bic) {
    
    this.bic = bic;
    return this;
  }

  /**
   * The Bank Identifier Code (BIC) of the bank account
   * @return bic
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BIC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBic() {
    return bic;
  }


  @JsonProperty(value = JSON_PROPERTY_BIC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBic(@jakarta.annotation.Nonnull String bic) {
    this.bic = bic;
  }

  /**
   * Last 4 digits of the bank account number
   * @return last4
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST4, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLast4() {
    return last4;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnknownBankAccount unknownBankAccount = (UnknownBankAccount) o;
    return Objects.equals(this.accountNumber, unknownBankAccount.accountNumber) &&
        Objects.equals(this.bic, unknownBankAccount.bic) &&
        Objects.equals(this.last4, unknownBankAccount.last4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, bic, last4);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnknownBankAccount {\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    last4: ").append(toIndentedString(last4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

