/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateLiquidationAddress
 */
@JsonPropertyOrder({
  UpdateLiquidationAddress.JSON_PROPERTY_EXTERNAL_ACCOUNT_ID,
  UpdateLiquidationAddress.JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT,
  UpdateLiquidationAddress.JSON_PROPERTY_DESTINATION_ACH_REFERENCE,
  UpdateLiquidationAddress.JSON_PROPERTY_DESTINATION_WIRE_MESSAGE,
  UpdateLiquidationAddress.JSON_PROPERTY_DESTINATION_SEPA_REFERENCE,
  UpdateLiquidationAddress.JSON_PROPERTY_DESTINATION_SPEI_REFERENCE,
  UpdateLiquidationAddress.JSON_PROPERTY_RETURN_ADDRESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UpdateLiquidationAddress {
  public static final String JSON_PROPERTY_EXTERNAL_ACCOUNT_ID = "external_account_id";
  @jakarta.annotation.Nullable
  private String externalAccountId;

  public static final String JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT = "custom_developer_fee_percent";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> customDeveloperFeePercent = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_DESTINATION_ACH_REFERENCE = "destination_ach_reference";
  @jakarta.annotation.Nullable
  private String destinationAchReference;

  public static final String JSON_PROPERTY_DESTINATION_WIRE_MESSAGE = "destination_wire_message";
  @jakarta.annotation.Nullable
  private String destinationWireMessage;

  public static final String JSON_PROPERTY_DESTINATION_SEPA_REFERENCE = "destination_sepa_reference";
  @jakarta.annotation.Nullable
  private String destinationSepaReference;

  public static final String JSON_PROPERTY_DESTINATION_SPEI_REFERENCE = "destination_spei_reference";
  @jakarta.annotation.Nullable
  private String destinationSpeiReference;

  public static final String JSON_PROPERTY_RETURN_ADDRESS = "return_address";
  @jakarta.annotation.Nullable
  private String returnAddress;

  public UpdateLiquidationAddress() {
  }

  public UpdateLiquidationAddress externalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    
    this.externalAccountId = externalAccountId;
    return this;
  }

  /**
   * An optional identifier for the external account you wish to associate with this liquidation schedule.  **Note**: Only one liquidation address can be associated with an external account per (customer, chain, currency). 
   * @return externalAccountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalAccountId() {
    return externalAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccountId(@jakarta.annotation.Nullable String externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public UpdateLiquidationAddress customDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
    
    return this;
  }

  /**
   * The developer fee percent that will be applied to this Liquidation Address or null to use the default fee. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
   * minimum: 0
   * maximum: 100
   * @return customDeveloperFeePercent
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getCustomDeveloperFeePercent() {
        return customDeveloperFeePercent.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getCustomDeveloperFeePercent_JsonNullable() {
    return customDeveloperFeePercent;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_DEVELOPER_FEE_PERCENT)
  public void setCustomDeveloperFeePercent_JsonNullable(JsonNullable<BigDecimal> customDeveloperFeePercent) {
    this.customDeveloperFeePercent = customDeveloperFeePercent;
  }

  public void setCustomDeveloperFeePercent(@jakarta.annotation.Nullable BigDecimal customDeveloperFeePercent) {
    this.customDeveloperFeePercent = JsonNullable.<BigDecimal>of(customDeveloperFeePercent);
  }

  public UpdateLiquidationAddress destinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    
    this.destinationAchReference = destinationAchReference;
    return this;
  }

  /**
   * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
   * @return destinationAchReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationAchReference() {
    return destinationAchReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_ACH_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationAchReference(@jakarta.annotation.Nullable String destinationAchReference) {
    this.destinationAchReference = destinationAchReference;
  }

  public UpdateLiquidationAddress destinationWireMessage(@jakarta.annotation.Nullable String destinationWireMessage) {
    
    this.destinationWireMessage = destinationWireMessage;
    return this;
  }

  /**
   * A message to be sent with a wire transfer. It can have up to 140 characters. This message will be validated against 4 lines, each with a max length of 35 characters according to the Fedwire standard.
   * @return destinationWireMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationWireMessage() {
    return destinationWireMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_WIRE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationWireMessage(@jakarta.annotation.Nullable String destinationWireMessage) {
    this.destinationWireMessage = destinationWireMessage;
  }

  public UpdateLiquidationAddress destinationSepaReference(@jakarta.annotation.Nullable String destinationSepaReference) {
    
    this.destinationSepaReference = destinationSepaReference;
    return this;
  }

  /**
   * A reference message to be sent with a SEPA transaction. We recommend you set a unique value to help you and your customers track payments end to end. It must be from 6 to 140 characters. The allowed characters are &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, spaces, ampersand (&#x60;&amp;&#x60;), hyphen (&#x60;-&#x60;), full stop (&#x60;.&#x60;), and solidus (&#x60;/&#x60;). If not populated, the default value is \&quot;Payment via Bridge {unique_token}\&quot;.
   * @return destinationSepaReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationSepaReference() {
    return destinationSepaReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SEPA_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationSepaReference(@jakarta.annotation.Nullable String destinationSepaReference) {
    this.destinationSepaReference = destinationSepaReference;
  }

  public UpdateLiquidationAddress destinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    
    this.destinationSpeiReference = destinationSpeiReference;
    return this;
  }

  /**
   * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric &#x60;a-z&#x60;, &#x60;A-Z&#x60;, &#x60;0-9&#x60;, and space
   * @return destinationSpeiReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationSpeiReference() {
    return destinationSpeiReference;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION_SPEI_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationSpeiReference(@jakarta.annotation.Nullable String destinationSpeiReference) {
    this.destinationSpeiReference = destinationSpeiReference;
  }

  public UpdateLiquidationAddress returnAddress(@jakarta.annotation.Nullable String returnAddress) {
    
    this.returnAddress = returnAddress;
    return this;
  }

  /**
   * The crypto wallet address that Bridge will use to return funds to the customer in case of a failed transaction. This address must be on the same chain specified for the liquidation address. Please note, this functionality is not supported on Stellar.
   * @return returnAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnAddress() {
    return returnAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnAddress(@jakarta.annotation.Nullable String returnAddress) {
    this.returnAddress = returnAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateLiquidationAddress updateLiquidationAddress = (UpdateLiquidationAddress) o;
    return Objects.equals(this.externalAccountId, updateLiquidationAddress.externalAccountId) &&
        equalsNullable(this.customDeveloperFeePercent, updateLiquidationAddress.customDeveloperFeePercent) &&
        Objects.equals(this.destinationAchReference, updateLiquidationAddress.destinationAchReference) &&
        Objects.equals(this.destinationWireMessage, updateLiquidationAddress.destinationWireMessage) &&
        Objects.equals(this.destinationSepaReference, updateLiquidationAddress.destinationSepaReference) &&
        Objects.equals(this.destinationSpeiReference, updateLiquidationAddress.destinationSpeiReference) &&
        Objects.equals(this.returnAddress, updateLiquidationAddress.returnAddress);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalAccountId, hashCodeNullable(customDeveloperFeePercent), destinationAchReference, destinationWireMessage, destinationSepaReference, destinationSpeiReference, returnAddress);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateLiquidationAddress {\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    customDeveloperFeePercent: ").append(toIndentedString(customDeveloperFeePercent)).append("\n");
    sb.append("    destinationAchReference: ").append(toIndentedString(destinationAchReference)).append("\n");
    sb.append("    destinationWireMessage: ").append(toIndentedString(destinationWireMessage)).append("\n");
    sb.append("    destinationSepaReference: ").append(toIndentedString(destinationSepaReference)).append("\n");
    sb.append("    destinationSpeiReference: ").append(toIndentedString(destinationSpeiReference)).append("\n");
    sb.append("    returnAddress: ").append(toIndentedString(returnAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

