/*
 * Bridge API
 * APIs to move into, out of, and between any form of a dollar
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jhely.money.sdk.bridge.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jhely.money.sdk.bridge.model.Address2025WinterRefresh;
import org.jhely.money.sdk.bridge.model.AssociatedPerson;
import org.jhely.money.sdk.bridge.model.BusinessDocumentsInner;
import org.jhely.money.sdk.bridge.model.EndorsementType;
import org.jhely.money.sdk.bridge.model.IdentifyingInformationInner;
import org.jhely.money.sdk.bridge.model.UpdateBusinessCustomerPayloadPubliclyTradedListingsInner;
import org.jhely.money.sdk.bridge.model.UpdateBusinessCustomerPayloadRegulatedActivity;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateBusinessCustomerPayload
 */
@JsonPropertyOrder({
  UpdateBusinessCustomerPayload.JSON_PROPERTY_TYPE,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_BUSINESS_LEGAL_NAME,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_TRANSLITERATED_BUSINESS_LEGAL_NAME,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_BUSINESS_TRADE_NAME,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_TRANSLITERATED_BUSINESS_TRADE_NAME,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_BUSINESS_DESCRIPTION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_EMAIL,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_BUSINESS_TYPE,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_PRIMARY_WEBSITE,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_OTHER_WEBSITES,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_REGISTERED_ADDRESS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_TRANSLITERATED_REGISTERED_ADDRESS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_PHYSICAL_ADDRESS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_TRANSLITERATED_PHYSICAL_ADDRESS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_SIGNED_AGREEMENT_ID,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_IS_DAO,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_COMPLIANCE_SCREENING_EXPLANATION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_ASSOCIATED_PERSONS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_ENDORSEMENTS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_BUSINESS_INDUSTRY,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_PUBLICLY_TRADED_LISTINGS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_OWNERSHIP_THRESHOLD,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_HAS_MATERIAL_INTERMEDIARY_OWNERSHIP,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_ESTIMATED_ANNUAL_REVENUE_USD,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_EXPECTED_MONTHLY_PAYMENTS_USD,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_OPERATES_IN_PROHIBITED_COUNTRIES,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_ACCOUNT_PURPOSE,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_ACCOUNT_PURPOSE_OTHER,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_HIGH_RISK_ACTIVITIES_EXPLANATION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_HIGH_RISK_ACTIVITIES,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_SOURCE_OF_FUNDS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_SOURCE_OF_FUNDS_DESCRIPTION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_CONDUCTS_MONEY_SERVICES,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_USING_BRIDGE,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_DESCRIPTION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_IDENTIFYING_INFORMATION,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_DOCUMENTS,
  UpdateBusinessCustomerPayload.JSON_PROPERTY_REGULATED_ACTIVITY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UpdateBusinessCustomerPayload {
  /**
   * Type of the customer (individual vs. business)
   */
  public enum TypeEnum {
    BUSINESS(String.valueOf("business"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_BUSINESS_LEGAL_NAME = "business_legal_name";
  @jakarta.annotation.Nonnull
  private String businessLegalName;

  public static final String JSON_PROPERTY_TRANSLITERATED_BUSINESS_LEGAL_NAME = "transliterated_business_legal_name";
  @jakarta.annotation.Nullable
  private String transliteratedBusinessLegalName;

  public static final String JSON_PROPERTY_BUSINESS_TRADE_NAME = "business_trade_name";
  @jakarta.annotation.Nonnull
  private String businessTradeName;

  public static final String JSON_PROPERTY_TRANSLITERATED_BUSINESS_TRADE_NAME = "transliterated_business_trade_name";
  @jakarta.annotation.Nullable
  private String transliteratedBusinessTradeName;

  public static final String JSON_PROPERTY_BUSINESS_DESCRIPTION = "business_description";
  @jakarta.annotation.Nonnull
  private String businessDescription;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nonnull
  private String email;

  /**
   * How the business is legally registered
   */
  public enum BusinessTypeEnum {
    COOPERATIVE(String.valueOf("cooperative")),
    
    CORPORATION(String.valueOf("corporation")),
    
    LLC(String.valueOf("llc")),
    
    OTHER(String.valueOf("other")),
    
    PARTNERSHIP(String.valueOf("partnership")),
    
    SOLE_PROP(String.valueOf("sole_prop")),
    
    TRUST(String.valueOf("trust"));

    private String value;

    BusinessTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BusinessTypeEnum fromValue(String value) {
      for (BusinessTypeEnum b : BusinessTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BUSINESS_TYPE = "business_type";
  @jakarta.annotation.Nonnull
  private BusinessTypeEnum businessType;

  public static final String JSON_PROPERTY_PRIMARY_WEBSITE = "primary_website";
  @jakarta.annotation.Nullable
  private String primaryWebsite;

  public static final String JSON_PROPERTY_OTHER_WEBSITES = "other_websites";
  @jakarta.annotation.Nullable
  private List<String> otherWebsites = new ArrayList<>();

  public static final String JSON_PROPERTY_REGISTERED_ADDRESS = "registered_address";
  @jakarta.annotation.Nonnull
  private Address2025WinterRefresh registeredAddress;

  public static final String JSON_PROPERTY_TRANSLITERATED_REGISTERED_ADDRESS = "transliterated_registered_address";
  @jakarta.annotation.Nullable
  private Address2025WinterRefresh transliteratedRegisteredAddress;

  public static final String JSON_PROPERTY_PHYSICAL_ADDRESS = "physical_address";
  @jakarta.annotation.Nonnull
  private Address2025WinterRefresh physicalAddress;

  public static final String JSON_PROPERTY_TRANSLITERATED_PHYSICAL_ADDRESS = "transliterated_physical_address";
  @jakarta.annotation.Nullable
  private Address2025WinterRefresh transliteratedPhysicalAddress;

  public static final String JSON_PROPERTY_SIGNED_AGREEMENT_ID = "signed_agreement_id";
  @jakarta.annotation.Nonnull
  private String signedAgreementId;

  public static final String JSON_PROPERTY_IS_DAO = "is_dao";
  @jakarta.annotation.Nonnull
  private Boolean isDao;

  public static final String JSON_PROPERTY_COMPLIANCE_SCREENING_EXPLANATION = "compliance_screening_explanation";
  @jakarta.annotation.Nullable
  private String complianceScreeningExplanation;

  public static final String JSON_PROPERTY_ASSOCIATED_PERSONS = "associated_persons";
  @jakarta.annotation.Nonnull
  private List<AssociatedPerson> associatedPersons = new ArrayList<>();

  public static final String JSON_PROPERTY_ENDORSEMENTS = "endorsements";
  @jakarta.annotation.Nullable
  private List<EndorsementType> endorsements = new ArrayList<>();

  public static final String JSON_PROPERTY_BUSINESS_INDUSTRY = "business_industry";
  @jakarta.annotation.Nonnull
  private List<String> businessIndustry = new ArrayList<>();

  public static final String JSON_PROPERTY_PUBLICLY_TRADED_LISTINGS = "publicly_traded_listings";
  @jakarta.annotation.Nullable
  private List<UpdateBusinessCustomerPayloadPubliclyTradedListingsInner> publiclyTradedListings = new ArrayList<>();

  public static final String JSON_PROPERTY_OWNERSHIP_THRESHOLD = "ownership_threshold";
  @jakarta.annotation.Nullable
  private Integer ownershipThreshold;

  public static final String JSON_PROPERTY_HAS_MATERIAL_INTERMEDIARY_OWNERSHIP = "has_material_intermediary_ownership";
  @jakarta.annotation.Nonnull
  private Boolean hasMaterialIntermediaryOwnership;

  /**
   * Estimated annual revenue in USD  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   */
  public enum EstimatedAnnualRevenueUsdEnum {
    _0_99999(String.valueOf("0_99999")),
    
    _100000_999999(String.valueOf("100000_999999")),
    
    _1000000_9999999(String.valueOf("1000000_9999999")),
    
    _10000000_49999999(String.valueOf("10000000_49999999")),
    
    _50000000_249999999(String.valueOf("50000000_249999999")),
    
    _250000000_PLUS(String.valueOf("250000000_plus"));

    private String value;

    EstimatedAnnualRevenueUsdEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EstimatedAnnualRevenueUsdEnum fromValue(String value) {
      for (EstimatedAnnualRevenueUsdEnum b : EstimatedAnnualRevenueUsdEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ESTIMATED_ANNUAL_REVENUE_USD = "estimated_annual_revenue_usd";
  @jakarta.annotation.Nullable
  private EstimatedAnnualRevenueUsdEnum estimatedAnnualRevenueUsd;

  public static final String JSON_PROPERTY_EXPECTED_MONTHLY_PAYMENTS_USD = "expected_monthly_payments_usd";
  @jakarta.annotation.Nullable
  private Integer expectedMonthlyPaymentsUsd;

  public static final String JSON_PROPERTY_OPERATES_IN_PROHIBITED_COUNTRIES = "operates_in_prohibited_countries";
  @jakarta.annotation.Nullable
  private Boolean operatesInProhibitedCountries;

  /**
   * What is the primary purpose of the business account?
   */
  public enum AccountPurposeEnum {
    CHARITABLE_DONATIONS(String.valueOf("charitable_donations")),
    
    ECOMMERCE_RETAIL_PAYMENTS(String.valueOf("ecommerce_retail_payments")),
    
    INVESTMENT_PURPOSES(String.valueOf("investment_purposes")),
    
    OTHER(String.valueOf("other")),
    
    PAYMENTS_TO_FRIENDS_OR_FAMILY_ABROAD(String.valueOf("payments_to_friends_or_family_abroad")),
    
    PAYROLL(String.valueOf("payroll")),
    
    PERSONAL_OR_LIVING_EXPENSES(String.valueOf("personal_or_living_expenses")),
    
    PROTECT_WEALTH(String.valueOf("protect_wealth")),
    
    PURCHASE_GOODS_AND_SERVICES(String.valueOf("purchase_goods_and_services")),
    
    RECEIVE_PAYMENTS_FOR_GOODS_AND_SERVICES(String.valueOf("receive_payments_for_goods_and_services")),
    
    TAX_OPTIMIZATION(String.valueOf("tax_optimization")),
    
    THIRD_PARTY_MONEY_TRANSMISSION(String.valueOf("third_party_money_transmission")),
    
    TREASURY_MANAGEMENT(String.valueOf("treasury_management"));

    private String value;

    AccountPurposeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AccountPurposeEnum fromValue(String value) {
      for (AccountPurposeEnum b : AccountPurposeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCOUNT_PURPOSE = "account_purpose";
  @jakarta.annotation.Nonnull
  private AccountPurposeEnum accountPurpose;

  public static final String JSON_PROPERTY_ACCOUNT_PURPOSE_OTHER = "account_purpose_other";
  @jakarta.annotation.Nullable
  private String accountPurposeOther;

  public static final String JSON_PROPERTY_HIGH_RISK_ACTIVITIES_EXPLANATION = "high_risk_activities_explanation";
  @jakarta.annotation.Nullable
  private String highRiskActivitiesExplanation;

  /**
   * Gets or Sets highRiskActivities
   */
  public enum HighRiskActivitiesEnum {
    ADULT_ENTERTAINMENT(String.valueOf("adult_entertainment")),
    
    GAMBLING(String.valueOf("gambling")),
    
    HOLD_CLIENT_FUNDS(String.valueOf("hold_client_funds")),
    
    INVESTMENT_SERVICES(String.valueOf("investment_services")),
    
    LENDING_BANKING(String.valueOf("lending_banking")),
    
    MARIJUANA_OR_RELATED_SERVICES(String.valueOf("marijuana_or_related_services")),
    
    MONEY_SERVICES(String.valueOf("money_services")),
    
    NICOTINE_TOBACCO_OR_RELATED_SERVICES(String.valueOf("nicotine_tobacco_or_related_services")),
    
    OPERATE_FOREIGN_EXCHANGE_VIRTUAL_CURRENCIES_BROKERAGE_OTC(String.valueOf("operate_foreign_exchange_virtual_currencies_brokerage_otc")),
    
    PHARMACEUTICALS(String.valueOf("pharmaceuticals")),
    
    PRECIOUS_METALS_PRECIOUS_STONES_JEWELRY(String.valueOf("precious_metals_precious_stones_jewelry")),
    
    SAFE_DEPOSIT_BOX_RENTALS(String.valueOf("safe_deposit_box_rentals")),
    
    THIRD_PARTY_PAYMENT_PROCESSING(String.valueOf("third_party_payment_processing")),
    
    WEAPONS_FIREARMS_AND_EXPLOSIVES(String.valueOf("weapons_firearms_and_explosives")),
    
    NONE_OF_THE_ABOVE(String.valueOf("none_of_the_above"));

    private String value;

    HighRiskActivitiesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HighRiskActivitiesEnum fromValue(String value) {
      for (HighRiskActivitiesEnum b : HighRiskActivitiesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_HIGH_RISK_ACTIVITIES = "high_risk_activities";
  @jakarta.annotation.Nullable
  private List<HighRiskActivitiesEnum> highRiskActivities = new ArrayList<>();

  /**
   * The source of funds for the business, e.g. profits, income, venture capital, etc.
   */
  public enum SourceOfFundsEnum {
    BUSINESS_LOANS(String.valueOf("business_loans")),
    
    GRANTS(String.valueOf("grants")),
    
    INTER_COMPANY_FUNDS(String.valueOf("inter_company_funds")),
    
    INVESTMENT_PROCEEDS(String.valueOf("investment_proceeds")),
    
    LEGAL_SETTLEMENT(String.valueOf("legal_settlement")),
    
    OWNERS_CAPITAL(String.valueOf("owners_capital")),
    
    PENSION_RETIREMENT(String.valueOf("pension_retirement")),
    
    SALE_OF_ASSETS(String.valueOf("sale_of_assets")),
    
    SALES_OF_GOODS_AND_SERVICES(String.valueOf("sales_of_goods_and_services")),
    
    TAX_REFUND(String.valueOf("tax_refund")),
    
    THIRD_PARTY_FUNDS(String.valueOf("third_party_funds")),
    
    TREASURY_RESERVES(String.valueOf("treasury_reserves"));

    private String value;

    SourceOfFundsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceOfFundsEnum fromValue(String value) {
      for (SourceOfFundsEnum b : SourceOfFundsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE_OF_FUNDS = "source_of_funds";
  @jakarta.annotation.Nonnull
  private SourceOfFundsEnum sourceOfFunds;

  public static final String JSON_PROPERTY_SOURCE_OF_FUNDS_DESCRIPTION = "source_of_funds_description";
  @jakarta.annotation.Nullable
  private String sourceOfFundsDescription;

  public static final String JSON_PROPERTY_CONDUCTS_MONEY_SERVICES = "conducts_money_services";
  @jakarta.annotation.Nullable
  private Boolean conductsMoneyServices;

  public static final String JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_USING_BRIDGE = "conducts_money_services_using_bridge";
  @jakarta.annotation.Nullable
  private Boolean conductsMoneyServicesUsingBridge;

  public static final String JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_DESCRIPTION = "conducts_money_services_description";
  @jakarta.annotation.Nullable
  private String conductsMoneyServicesDescription;

  public static final String JSON_PROPERTY_IDENTIFYING_INFORMATION = "identifying_information";
  @jakarta.annotation.Nonnull
  private List<IdentifyingInformationInner> identifyingInformation = new ArrayList<>();

  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
  @jakarta.annotation.Nonnull
  private List<BusinessDocumentsInner> documents = new ArrayList<>();

  public static final String JSON_PROPERTY_REGULATED_ACTIVITY = "regulated_activity";
  @jakarta.annotation.Nullable
  private UpdateBusinessCustomerPayloadRegulatedActivity regulatedActivity;

  public UpdateBusinessCustomerPayload() {
  }

  public UpdateBusinessCustomerPayload type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Type of the customer (individual vs. business)
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public UpdateBusinessCustomerPayload businessLegalName(@jakarta.annotation.Nonnull String businessLegalName) {
    
    this.businessLegalName = businessLegalName;
    return this;
  }

  /**
   * The official registered name of the business as documented with government authorities.
   * @return businessLegalName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_LEGAL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBusinessLegalName() {
    return businessLegalName;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_LEGAL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessLegalName(@jakarta.annotation.Nonnull String businessLegalName) {
    this.businessLegalName = businessLegalName;
  }

  public UpdateBusinessCustomerPayload transliteratedBusinessLegalName(@jakarta.annotation.Nullable String transliteratedBusinessLegalName) {
    
    this.transliteratedBusinessLegalName = transliteratedBusinessLegalName;
    return this;
  }

  /**
   * Required if &#x60;business_legal_name&#x60; includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
   * @return transliteratedBusinessLegalName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_BUSINESS_LEGAL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransliteratedBusinessLegalName() {
    return transliteratedBusinessLegalName;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_BUSINESS_LEGAL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransliteratedBusinessLegalName(@jakarta.annotation.Nullable String transliteratedBusinessLegalName) {
    this.transliteratedBusinessLegalName = transliteratedBusinessLegalName;
  }

  public UpdateBusinessCustomerPayload businessTradeName(@jakarta.annotation.Nonnull String businessTradeName) {
    
    this.businessTradeName = businessTradeName;
    return this;
  }

  /**
   * The trading name or DBA (Doing Business As) name under which the business operates publicly.
   * @return businessTradeName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_TRADE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBusinessTradeName() {
    return businessTradeName;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_TRADE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessTradeName(@jakarta.annotation.Nonnull String businessTradeName) {
    this.businessTradeName = businessTradeName;
  }

  public UpdateBusinessCustomerPayload transliteratedBusinessTradeName(@jakarta.annotation.Nullable String transliteratedBusinessTradeName) {
    
    this.transliteratedBusinessTradeName = transliteratedBusinessTradeName;
    return this;
  }

  /**
   * Required if &#x60;business_trade&#x60; includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
   * @return transliteratedBusinessTradeName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_BUSINESS_TRADE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransliteratedBusinessTradeName() {
    return transliteratedBusinessTradeName;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_BUSINESS_TRADE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransliteratedBusinessTradeName(@jakarta.annotation.Nullable String transliteratedBusinessTradeName) {
    this.transliteratedBusinessTradeName = transliteratedBusinessTradeName;
  }

  public UpdateBusinessCustomerPayload businessDescription(@jakarta.annotation.Nonnull String businessDescription) {
    
    this.businessDescription = businessDescription;
    return this;
  }

  /**
   * A brief summary of the business
   * @return businessDescription
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBusinessDescription() {
    return businessDescription;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessDescription(@jakarta.annotation.Nonnull String businessDescription) {
    this.businessDescription = businessDescription;
  }

  public UpdateBusinessCustomerPayload email(@jakarta.annotation.Nonnull String email) {
    
    this.email = email;
    return this;
  }

  /**
   * The business&#39;s primary email address
   * @return email
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@jakarta.annotation.Nonnull String email) {
    this.email = email;
  }

  public UpdateBusinessCustomerPayload businessType(@jakarta.annotation.Nonnull BusinessTypeEnum businessType) {
    
    this.businessType = businessType;
    return this;
  }

  /**
   * How the business is legally registered
   * @return businessType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BusinessTypeEnum getBusinessType() {
    return businessType;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessType(@jakarta.annotation.Nonnull BusinessTypeEnum businessType) {
    this.businessType = businessType;
  }

  public UpdateBusinessCustomerPayload primaryWebsite(@jakarta.annotation.Nullable String primaryWebsite) {
    
    this.primaryWebsite = primaryWebsite;
    return this;
  }

  /**
   * The business&#39;s primary website/web presence. A document with purpose &#39;proof_of_nature_of_business&#39; is required if this is not provided
   * @return primaryWebsite
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_WEBSITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrimaryWebsite() {
    return primaryWebsite;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_WEBSITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryWebsite(@jakarta.annotation.Nullable String primaryWebsite) {
    this.primaryWebsite = primaryWebsite;
  }

  public UpdateBusinessCustomerPayload otherWebsites(@jakarta.annotation.Nullable List<String> otherWebsites) {
    
    this.otherWebsites = otherWebsites;
    return this;
  }

  public UpdateBusinessCustomerPayload addOtherWebsitesItem(String otherWebsitesItem) {
    if (this.otherWebsites == null) {
      this.otherWebsites = new ArrayList<>();
    }
    this.otherWebsites.add(otherWebsitesItem);
    return this;
  }

  /**
   * The business&#39;s other websites and social media handles
   * @return otherWebsites
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OTHER_WEBSITES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getOtherWebsites() {
    return otherWebsites;
  }


  @JsonProperty(value = JSON_PROPERTY_OTHER_WEBSITES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherWebsites(@jakarta.annotation.Nullable List<String> otherWebsites) {
    this.otherWebsites = otherWebsites;
  }

  public UpdateBusinessCustomerPayload registeredAddress(@jakarta.annotation.Nonnull Address2025WinterRefresh registeredAddress) {
    
    this.registeredAddress = registeredAddress;
    return this;
  }

  /**
   * Get registeredAddress
   * @return registeredAddress
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REGISTERED_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Address2025WinterRefresh getRegisteredAddress() {
    return registeredAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_REGISTERED_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegisteredAddress(@jakarta.annotation.Nonnull Address2025WinterRefresh registeredAddress) {
    this.registeredAddress = registeredAddress;
  }

  public UpdateBusinessCustomerPayload transliteratedRegisteredAddress(@jakarta.annotation.Nullable Address2025WinterRefresh transliteratedRegisteredAddress) {
    
    this.transliteratedRegisteredAddress = transliteratedRegisteredAddress;
    return this;
  }

  /**
   * Get transliteratedRegisteredAddress
   * @return transliteratedRegisteredAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_REGISTERED_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address2025WinterRefresh getTransliteratedRegisteredAddress() {
    return transliteratedRegisteredAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_REGISTERED_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransliteratedRegisteredAddress(@jakarta.annotation.Nullable Address2025WinterRefresh transliteratedRegisteredAddress) {
    this.transliteratedRegisteredAddress = transliteratedRegisteredAddress;
  }

  public UpdateBusinessCustomerPayload physicalAddress(@jakarta.annotation.Nonnull Address2025WinterRefresh physicalAddress) {
    
    this.physicalAddress = physicalAddress;
    return this;
  }

  /**
   * Get physicalAddress
   * @return physicalAddress
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PHYSICAL_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Address2025WinterRefresh getPhysicalAddress() {
    return physicalAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_PHYSICAL_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhysicalAddress(@jakarta.annotation.Nonnull Address2025WinterRefresh physicalAddress) {
    this.physicalAddress = physicalAddress;
  }

  public UpdateBusinessCustomerPayload transliteratedPhysicalAddress(@jakarta.annotation.Nullable Address2025WinterRefresh transliteratedPhysicalAddress) {
    
    this.transliteratedPhysicalAddress = transliteratedPhysicalAddress;
    return this;
  }

  /**
   * Get transliteratedPhysicalAddress
   * @return transliteratedPhysicalAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_PHYSICAL_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address2025WinterRefresh getTransliteratedPhysicalAddress() {
    return transliteratedPhysicalAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSLITERATED_PHYSICAL_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransliteratedPhysicalAddress(@jakarta.annotation.Nullable Address2025WinterRefresh transliteratedPhysicalAddress) {
    this.transliteratedPhysicalAddress = transliteratedPhysicalAddress;
  }

  public UpdateBusinessCustomerPayload signedAgreementId(@jakarta.annotation.Nonnull String signedAgreementId) {
    
    this.signedAgreementId = signedAgreementId;
    return this;
  }

  /**
   * The ID of the signed agreement that the customer completed. You can get a signed agreement id for a _new_ customer by following [this guide](https://apidocs.bridge.xyz/docs/terms-of-service#tos-acceptance-for-a-new-customer). 
   * @return signedAgreementId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNED_AGREEMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignedAgreementId() {
    return signedAgreementId;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_AGREEMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedAgreementId(@jakarta.annotation.Nonnull String signedAgreementId) {
    this.signedAgreementId = signedAgreementId;
  }

  public UpdateBusinessCustomerPayload isDao(@jakarta.annotation.Nonnull Boolean isDao) {
    
    this.isDao = isDao;
    return this;
  }

  /**
   * Whether the business is a DAO (Decentralized Autonomous Organization)
   * @return isDao
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_DAO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDao() {
    return isDao;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_DAO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDao(@jakarta.annotation.Nonnull Boolean isDao) {
    this.isDao = isDao;
  }

  public UpdateBusinessCustomerPayload complianceScreeningExplanation(@jakarta.annotation.Nullable String complianceScreeningExplanation) {
    
    this.complianceScreeningExplanation = complianceScreeningExplanation;
    return this;
  }

  /**
   * Required if &#x60;conducts_money_services&#x60; is true. A detailed description of the business&#39;s compliance and anti-money laundering controls and practices.
   * @return complianceScreeningExplanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPLIANCE_SCREENING_EXPLANATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplianceScreeningExplanation() {
    return complianceScreeningExplanation;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLIANCE_SCREENING_EXPLANATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplianceScreeningExplanation(@jakarta.annotation.Nullable String complianceScreeningExplanation) {
    this.complianceScreeningExplanation = complianceScreeningExplanation;
  }

  public UpdateBusinessCustomerPayload associatedPersons(@jakarta.annotation.Nonnull List<AssociatedPerson> associatedPersons) {
    
    this.associatedPersons = associatedPersons;
    return this;
  }

  public UpdateBusinessCustomerPayload addAssociatedPersonsItem(AssociatedPerson associatedPersonsItem) {
    if (this.associatedPersons == null) {
      this.associatedPersons = new ArrayList<>();
    }
    this.associatedPersons.add(associatedPersonsItem);
    return this;
  }

  /**
   * List of notable people associated with the business such as UBOs.
   * @return associatedPersons
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ASSOCIATED_PERSONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AssociatedPerson> getAssociatedPersons() {
    return associatedPersons;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSOCIATED_PERSONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssociatedPersons(@jakarta.annotation.Nonnull List<AssociatedPerson> associatedPersons) {
    this.associatedPersons = associatedPersons;
  }

  public UpdateBusinessCustomerPayload endorsements(@jakarta.annotation.Nullable List<EndorsementType> endorsements) {
    
    this.endorsements = endorsements;
    return this;
  }

  public UpdateBusinessCustomerPayload addEndorsementsItem(EndorsementType endorsementsItem) {
    if (this.endorsements == null) {
      this.endorsements = new ArrayList<>();
    }
    this.endorsements.add(endorsementsItem);
    return this;
  }

  /**
   * List of endorsements to request for this customer. If omitted, we&#39;ll attempt to grant &#x60;base&#x60; and &#x60;sepa&#x60;. 
   * @return endorsements
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDORSEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EndorsementType> getEndorsements() {
    return endorsements;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDORSEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndorsements(@jakarta.annotation.Nullable List<EndorsementType> endorsements) {
    this.endorsements = endorsements;
  }

  public UpdateBusinessCustomerPayload businessIndustry(@jakarta.annotation.Nonnull List<String> businessIndustry) {
    
    this.businessIndustry = businessIndustry;
    return this;
  }

  public UpdateBusinessCustomerPayload addBusinessIndustryItem(String businessIndustryItem) {
    if (this.businessIndustry == null) {
      this.businessIndustry = new ArrayList<>();
    }
    this.businessIndustry.add(businessIndustryItem);
    return this;
  }

  /**
   * The industry in which this business operates. Click [here](https://apidocs.bridge.xyz/page/business-industry-list-updated-2022-naics-codes) for the complete list of valid industries and codes.
   * @return businessIndustry
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_INDUSTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getBusinessIndustry() {
    return businessIndustry;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_INDUSTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessIndustry(@jakarta.annotation.Nonnull List<String> businessIndustry) {
    this.businessIndustry = businessIndustry;
  }

  public UpdateBusinessCustomerPayload publiclyTradedListings(@jakarta.annotation.Nullable List<UpdateBusinessCustomerPayloadPubliclyTradedListingsInner> publiclyTradedListings) {
    
    this.publiclyTradedListings = publiclyTradedListings;
    return this;
  }

  public UpdateBusinessCustomerPayload addPubliclyTradedListingsItem(UpdateBusinessCustomerPayloadPubliclyTradedListingsInner publiclyTradedListingsItem) {
    if (this.publiclyTradedListings == null) {
      this.publiclyTradedListings = new ArrayList<>();
    }
    this.publiclyTradedListings.add(publiclyTradedListingsItem);
    return this;
  }

  /**
   * A list of public exchanges that the company is traded on if applicable.
   * @return publiclyTradedListings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PUBLICLY_TRADED_LISTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateBusinessCustomerPayloadPubliclyTradedListingsInner> getPubliclyTradedListings() {
    return publiclyTradedListings;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLICLY_TRADED_LISTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPubliclyTradedListings(@jakarta.annotation.Nullable List<UpdateBusinessCustomerPayloadPubliclyTradedListingsInner> publiclyTradedListings) {
    this.publiclyTradedListings = publiclyTradedListings;
  }

  public UpdateBusinessCustomerPayload ownershipThreshold(@jakarta.annotation.Nullable Integer ownershipThreshold) {
    
    this.ownershipThreshold = ownershipThreshold;
    return this;
  }

  /**
   * The applicable beneficial ownership threshold for the submitted &#x60;associated_persons&#x60; information. Valid values are between 5 to 25. Default value is 25.
   * @return ownershipThreshold
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNERSHIP_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOwnershipThreshold() {
    return ownershipThreshold;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNERSHIP_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnershipThreshold(@jakarta.annotation.Nullable Integer ownershipThreshold) {
    this.ownershipThreshold = ownershipThreshold;
  }

  public UpdateBusinessCustomerPayload hasMaterialIntermediaryOwnership(@jakarta.annotation.Nonnull Boolean hasMaterialIntermediaryOwnership) {
    
    this.hasMaterialIntermediaryOwnership = hasMaterialIntermediaryOwnership;
    return this;
  }

  /**
   * The business has at least one intermediate legal entity owner with 25% or more ownership
   * @return hasMaterialIntermediaryOwnership
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_MATERIAL_INTERMEDIARY_OWNERSHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasMaterialIntermediaryOwnership() {
    return hasMaterialIntermediaryOwnership;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_MATERIAL_INTERMEDIARY_OWNERSHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasMaterialIntermediaryOwnership(@jakarta.annotation.Nonnull Boolean hasMaterialIntermediaryOwnership) {
    this.hasMaterialIntermediaryOwnership = hasMaterialIntermediaryOwnership;
  }

  public UpdateBusinessCustomerPayload estimatedAnnualRevenueUsd(@jakarta.annotation.Nullable EstimatedAnnualRevenueUsdEnum estimatedAnnualRevenueUsd) {
    
    this.estimatedAnnualRevenueUsd = estimatedAnnualRevenueUsd;
    return this;
  }

  /**
   * Estimated annual revenue in USD  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return estimatedAnnualRevenueUsd
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ESTIMATED_ANNUAL_REVENUE_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EstimatedAnnualRevenueUsdEnum getEstimatedAnnualRevenueUsd() {
    return estimatedAnnualRevenueUsd;
  }


  @JsonProperty(value = JSON_PROPERTY_ESTIMATED_ANNUAL_REVENUE_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimatedAnnualRevenueUsd(@jakarta.annotation.Nullable EstimatedAnnualRevenueUsdEnum estimatedAnnualRevenueUsd) {
    this.estimatedAnnualRevenueUsd = estimatedAnnualRevenueUsd;
  }

  public UpdateBusinessCustomerPayload expectedMonthlyPaymentsUsd(@jakarta.annotation.Nullable Integer expectedMonthlyPaymentsUsd) {
    
    this.expectedMonthlyPaymentsUsd = expectedMonthlyPaymentsUsd;
    return this;
  }

  /**
   * Expected monthly payments in USD  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return expectedMonthlyPaymentsUsd
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPECTED_MONTHLY_PAYMENTS_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpectedMonthlyPaymentsUsd() {
    return expectedMonthlyPaymentsUsd;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPECTED_MONTHLY_PAYMENTS_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpectedMonthlyPaymentsUsd(@jakarta.annotation.Nullable Integer expectedMonthlyPaymentsUsd) {
    this.expectedMonthlyPaymentsUsd = expectedMonthlyPaymentsUsd;
  }

  public UpdateBusinessCustomerPayload operatesInProhibitedCountries(@jakarta.annotation.Nullable Boolean operatesInProhibitedCountries) {
    
    this.operatesInProhibitedCountries = operatesInProhibitedCountries;
    return this;
  }

  /**
   * Does the business operate in any prohibited countries?  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return operatesInProhibitedCountries
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATES_IN_PROHIBITED_COUNTRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOperatesInProhibitedCountries() {
    return operatesInProhibitedCountries;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATES_IN_PROHIBITED_COUNTRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatesInProhibitedCountries(@jakarta.annotation.Nullable Boolean operatesInProhibitedCountries) {
    this.operatesInProhibitedCountries = operatesInProhibitedCountries;
  }

  public UpdateBusinessCustomerPayload accountPurpose(@jakarta.annotation.Nonnull AccountPurposeEnum accountPurpose) {
    
    this.accountPurpose = accountPurpose;
    return this;
  }

  /**
   * What is the primary purpose of the business account?
   * @return accountPurpose
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PURPOSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AccountPurposeEnum getAccountPurpose() {
    return accountPurpose;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PURPOSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountPurpose(@jakarta.annotation.Nonnull AccountPurposeEnum accountPurpose) {
    this.accountPurpose = accountPurpose;
  }

  public UpdateBusinessCustomerPayload accountPurposeOther(@jakarta.annotation.Nullable String accountPurposeOther) {
    
    this.accountPurposeOther = accountPurposeOther;
    return this;
  }

  /**
   * Required if the primary purpose is &#39;other&#39;.
   * @return accountPurposeOther
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PURPOSE_OTHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountPurposeOther() {
    return accountPurposeOther;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PURPOSE_OTHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountPurposeOther(@jakarta.annotation.Nullable String accountPurposeOther) {
    this.accountPurposeOther = accountPurposeOther;
  }

  public UpdateBusinessCustomerPayload highRiskActivitiesExplanation(@jakarta.annotation.Nullable String highRiskActivitiesExplanation) {
    
    this.highRiskActivitiesExplanation = highRiskActivitiesExplanation;
    return this;
  }

  /**
   * An explanation of the high risk activities that the business performs.   _Required if &#x60;high_risk_activities&#x60; contains entries other than &#x60;none_of_the_above&#x60;_ 
   * @return highRiskActivitiesExplanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH_RISK_ACTIVITIES_EXPLANATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHighRiskActivitiesExplanation() {
    return highRiskActivitiesExplanation;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH_RISK_ACTIVITIES_EXPLANATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighRiskActivitiesExplanation(@jakarta.annotation.Nullable String highRiskActivitiesExplanation) {
    this.highRiskActivitiesExplanation = highRiskActivitiesExplanation;
  }

  public UpdateBusinessCustomerPayload highRiskActivities(@jakarta.annotation.Nullable List<HighRiskActivitiesEnum> highRiskActivities) {
    
    this.highRiskActivities = highRiskActivities;
    return this;
  }

  public UpdateBusinessCustomerPayload addHighRiskActivitiesItem(HighRiskActivitiesEnum highRiskActivitiesItem) {
    if (this.highRiskActivities == null) {
      this.highRiskActivities = new ArrayList<>();
    }
    this.highRiskActivities.add(highRiskActivitiesItem);
    return this;
  }

  /**
   * List of high-risk activities the business is involved in.  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return highRiskActivities
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH_RISK_ACTIVITIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<HighRiskActivitiesEnum> getHighRiskActivities() {
    return highRiskActivities;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH_RISK_ACTIVITIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighRiskActivities(@jakarta.annotation.Nullable List<HighRiskActivitiesEnum> highRiskActivities) {
    this.highRiskActivities = highRiskActivities;
  }

  public UpdateBusinessCustomerPayload sourceOfFunds(@jakarta.annotation.Nonnull SourceOfFundsEnum sourceOfFunds) {
    
    this.sourceOfFunds = sourceOfFunds;
    return this;
  }

  /**
   * The source of funds for the business, e.g. profits, income, venture capital, etc.
   * @return sourceOfFunds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE_OF_FUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SourceOfFundsEnum getSourceOfFunds() {
    return sourceOfFunds;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_OF_FUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceOfFunds(@jakarta.annotation.Nonnull SourceOfFundsEnum sourceOfFunds) {
    this.sourceOfFunds = sourceOfFunds;
  }

  public UpdateBusinessCustomerPayload sourceOfFundsDescription(@jakarta.annotation.Nullable String sourceOfFundsDescription) {
    
    this.sourceOfFundsDescription = sourceOfFundsDescription;
    return this;
  }

  /**
   * Description of the source of funds for the business&#39; account.  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return sourceOfFundsDescription
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_OF_FUNDS_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceOfFundsDescription() {
    return sourceOfFundsDescription;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_OF_FUNDS_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceOfFundsDescription(@jakarta.annotation.Nullable String sourceOfFundsDescription) {
    this.sourceOfFundsDescription = sourceOfFundsDescription;
  }

  public UpdateBusinessCustomerPayload conductsMoneyServices(@jakarta.annotation.Nullable Boolean conductsMoneyServices) {
    
    this.conductsMoneyServices = conductsMoneyServices;
    return this;
  }

  /**
   * The business offers money services, investment products, and/or other financial services.  _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_ 
   * @return conductsMoneyServices
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getConductsMoneyServices() {
    return conductsMoneyServices;
  }


  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConductsMoneyServices(@jakarta.annotation.Nullable Boolean conductsMoneyServices) {
    this.conductsMoneyServices = conductsMoneyServices;
  }

  public UpdateBusinessCustomerPayload conductsMoneyServicesUsingBridge(@jakarta.annotation.Nullable Boolean conductsMoneyServicesUsingBridge) {
    
    this.conductsMoneyServicesUsingBridge = conductsMoneyServicesUsingBridge;
    return this;
  }

  /**
   * The business plans to conduct money services, investment products, and/or other financial services using its Bridge account. A document with purpose &#39;flow_of_funds&#39; is required if this is true.  _Required if &#x60;conducts_money_services&#x60; is true_ 
   * @return conductsMoneyServicesUsingBridge
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_USING_BRIDGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getConductsMoneyServicesUsingBridge() {
    return conductsMoneyServicesUsingBridge;
  }


  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_USING_BRIDGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConductsMoneyServicesUsingBridge(@jakarta.annotation.Nullable Boolean conductsMoneyServicesUsingBridge) {
    this.conductsMoneyServicesUsingBridge = conductsMoneyServicesUsingBridge;
  }

  public UpdateBusinessCustomerPayload conductsMoneyServicesDescription(@jakarta.annotation.Nullable String conductsMoneyServicesDescription) {
    
    this.conductsMoneyServicesDescription = conductsMoneyServicesDescription;
    return this;
  }

  /**
   * Description of the money services offered by the business.  _Required if &#x60;conducts_money_services&#x60; is true_ 
   * @return conductsMoneyServicesDescription
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConductsMoneyServicesDescription() {
    return conductsMoneyServicesDescription;
  }


  @JsonProperty(value = JSON_PROPERTY_CONDUCTS_MONEY_SERVICES_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConductsMoneyServicesDescription(@jakarta.annotation.Nullable String conductsMoneyServicesDescription) {
    this.conductsMoneyServicesDescription = conductsMoneyServicesDescription;
  }

  public UpdateBusinessCustomerPayload identifyingInformation(@jakarta.annotation.Nonnull List<IdentifyingInformationInner> identifyingInformation) {
    
    this.identifyingInformation = identifyingInformation;
    return this;
  }

  public UpdateBusinessCustomerPayload addIdentifyingInformationItem(IdentifyingInformationInner identifyingInformationItem) {
    if (this.identifyingInformation == null) {
      this.identifyingInformation = new ArrayList<>();
    }
    this.identifyingInformation.add(identifyingInformationItem);
    return this;
  }

  /**
   * Get identifyingInformation
   * @return identifyingInformation
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDENTIFYING_INFORMATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<IdentifyingInformationInner> getIdentifyingInformation() {
    return identifyingInformation;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFYING_INFORMATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifyingInformation(@jakarta.annotation.Nonnull List<IdentifyingInformationInner> identifyingInformation) {
    this.identifyingInformation = identifyingInformation;
  }

  public UpdateBusinessCustomerPayload documents(@jakarta.annotation.Nonnull List<BusinessDocumentsInner> documents) {
    
    this.documents = documents;
    return this;
  }

  public UpdateBusinessCustomerPayload addDocumentsItem(BusinessDocumentsInner documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * Please click \&quot;ADD OBJECT\&quot; for more information.
   * @return documents
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BusinessDocumentsInner> getDocuments() {
    return documents;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocuments(@jakarta.annotation.Nonnull List<BusinessDocumentsInner> documents) {
    this.documents = documents;
  }

  public UpdateBusinessCustomerPayload regulatedActivity(@jakarta.annotation.Nullable UpdateBusinessCustomerPayloadRegulatedActivity regulatedActivity) {
    
    this.regulatedActivity = regulatedActivity;
    return this;
  }

  /**
   * Get regulatedActivity
   * @return regulatedActivity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REGULATED_ACTIVITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateBusinessCustomerPayloadRegulatedActivity getRegulatedActivity() {
    return regulatedActivity;
  }


  @JsonProperty(value = JSON_PROPERTY_REGULATED_ACTIVITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegulatedActivity(@jakarta.annotation.Nullable UpdateBusinessCustomerPayloadRegulatedActivity regulatedActivity) {
    this.regulatedActivity = regulatedActivity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateBusinessCustomerPayload updateBusinessCustomerPayload = (UpdateBusinessCustomerPayload) o;
    return Objects.equals(this.type, updateBusinessCustomerPayload.type) &&
        Objects.equals(this.businessLegalName, updateBusinessCustomerPayload.businessLegalName) &&
        Objects.equals(this.transliteratedBusinessLegalName, updateBusinessCustomerPayload.transliteratedBusinessLegalName) &&
        Objects.equals(this.businessTradeName, updateBusinessCustomerPayload.businessTradeName) &&
        Objects.equals(this.transliteratedBusinessTradeName, updateBusinessCustomerPayload.transliteratedBusinessTradeName) &&
        Objects.equals(this.businessDescription, updateBusinessCustomerPayload.businessDescription) &&
        Objects.equals(this.email, updateBusinessCustomerPayload.email) &&
        Objects.equals(this.businessType, updateBusinessCustomerPayload.businessType) &&
        Objects.equals(this.primaryWebsite, updateBusinessCustomerPayload.primaryWebsite) &&
        Objects.equals(this.otherWebsites, updateBusinessCustomerPayload.otherWebsites) &&
        Objects.equals(this.registeredAddress, updateBusinessCustomerPayload.registeredAddress) &&
        Objects.equals(this.transliteratedRegisteredAddress, updateBusinessCustomerPayload.transliteratedRegisteredAddress) &&
        Objects.equals(this.physicalAddress, updateBusinessCustomerPayload.physicalAddress) &&
        Objects.equals(this.transliteratedPhysicalAddress, updateBusinessCustomerPayload.transliteratedPhysicalAddress) &&
        Objects.equals(this.signedAgreementId, updateBusinessCustomerPayload.signedAgreementId) &&
        Objects.equals(this.isDao, updateBusinessCustomerPayload.isDao) &&
        Objects.equals(this.complianceScreeningExplanation, updateBusinessCustomerPayload.complianceScreeningExplanation) &&
        Objects.equals(this.associatedPersons, updateBusinessCustomerPayload.associatedPersons) &&
        Objects.equals(this.endorsements, updateBusinessCustomerPayload.endorsements) &&
        Objects.equals(this.businessIndustry, updateBusinessCustomerPayload.businessIndustry) &&
        Objects.equals(this.publiclyTradedListings, updateBusinessCustomerPayload.publiclyTradedListings) &&
        Objects.equals(this.ownershipThreshold, updateBusinessCustomerPayload.ownershipThreshold) &&
        Objects.equals(this.hasMaterialIntermediaryOwnership, updateBusinessCustomerPayload.hasMaterialIntermediaryOwnership) &&
        Objects.equals(this.estimatedAnnualRevenueUsd, updateBusinessCustomerPayload.estimatedAnnualRevenueUsd) &&
        Objects.equals(this.expectedMonthlyPaymentsUsd, updateBusinessCustomerPayload.expectedMonthlyPaymentsUsd) &&
        Objects.equals(this.operatesInProhibitedCountries, updateBusinessCustomerPayload.operatesInProhibitedCountries) &&
        Objects.equals(this.accountPurpose, updateBusinessCustomerPayload.accountPurpose) &&
        Objects.equals(this.accountPurposeOther, updateBusinessCustomerPayload.accountPurposeOther) &&
        Objects.equals(this.highRiskActivitiesExplanation, updateBusinessCustomerPayload.highRiskActivitiesExplanation) &&
        Objects.equals(this.highRiskActivities, updateBusinessCustomerPayload.highRiskActivities) &&
        Objects.equals(this.sourceOfFunds, updateBusinessCustomerPayload.sourceOfFunds) &&
        Objects.equals(this.sourceOfFundsDescription, updateBusinessCustomerPayload.sourceOfFundsDescription) &&
        Objects.equals(this.conductsMoneyServices, updateBusinessCustomerPayload.conductsMoneyServices) &&
        Objects.equals(this.conductsMoneyServicesUsingBridge, updateBusinessCustomerPayload.conductsMoneyServicesUsingBridge) &&
        Objects.equals(this.conductsMoneyServicesDescription, updateBusinessCustomerPayload.conductsMoneyServicesDescription) &&
        Objects.equals(this.identifyingInformation, updateBusinessCustomerPayload.identifyingInformation) &&
        Objects.equals(this.documents, updateBusinessCustomerPayload.documents) &&
        Objects.equals(this.regulatedActivity, updateBusinessCustomerPayload.regulatedActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, businessLegalName, transliteratedBusinessLegalName, businessTradeName, transliteratedBusinessTradeName, businessDescription, email, businessType, primaryWebsite, otherWebsites, registeredAddress, transliteratedRegisteredAddress, physicalAddress, transliteratedPhysicalAddress, signedAgreementId, isDao, complianceScreeningExplanation, associatedPersons, endorsements, businessIndustry, publiclyTradedListings, ownershipThreshold, hasMaterialIntermediaryOwnership, estimatedAnnualRevenueUsd, expectedMonthlyPaymentsUsd, operatesInProhibitedCountries, accountPurpose, accountPurposeOther, highRiskActivitiesExplanation, highRiskActivities, sourceOfFunds, sourceOfFundsDescription, conductsMoneyServices, conductsMoneyServicesUsingBridge, conductsMoneyServicesDescription, identifyingInformation, documents, regulatedActivity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateBusinessCustomerPayload {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    businessLegalName: ").append(toIndentedString(businessLegalName)).append("\n");
    sb.append("    transliteratedBusinessLegalName: ").append(toIndentedString(transliteratedBusinessLegalName)).append("\n");
    sb.append("    businessTradeName: ").append(toIndentedString(businessTradeName)).append("\n");
    sb.append("    transliteratedBusinessTradeName: ").append(toIndentedString(transliteratedBusinessTradeName)).append("\n");
    sb.append("    businessDescription: ").append(toIndentedString(businessDescription)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    businessType: ").append(toIndentedString(businessType)).append("\n");
    sb.append("    primaryWebsite: ").append(toIndentedString(primaryWebsite)).append("\n");
    sb.append("    otherWebsites: ").append(toIndentedString(otherWebsites)).append("\n");
    sb.append("    registeredAddress: ").append(toIndentedString(registeredAddress)).append("\n");
    sb.append("    transliteratedRegisteredAddress: ").append(toIndentedString(transliteratedRegisteredAddress)).append("\n");
    sb.append("    physicalAddress: ").append(toIndentedString(physicalAddress)).append("\n");
    sb.append("    transliteratedPhysicalAddress: ").append(toIndentedString(transliteratedPhysicalAddress)).append("\n");
    sb.append("    signedAgreementId: ").append(toIndentedString(signedAgreementId)).append("\n");
    sb.append("    isDao: ").append(toIndentedString(isDao)).append("\n");
    sb.append("    complianceScreeningExplanation: ").append(toIndentedString(complianceScreeningExplanation)).append("\n");
    sb.append("    associatedPersons: ").append(toIndentedString(associatedPersons)).append("\n");
    sb.append("    endorsements: ").append(toIndentedString(endorsements)).append("\n");
    sb.append("    businessIndustry: ").append(toIndentedString(businessIndustry)).append("\n");
    sb.append("    publiclyTradedListings: ").append(toIndentedString(publiclyTradedListings)).append("\n");
    sb.append("    ownershipThreshold: ").append(toIndentedString(ownershipThreshold)).append("\n");
    sb.append("    hasMaterialIntermediaryOwnership: ").append(toIndentedString(hasMaterialIntermediaryOwnership)).append("\n");
    sb.append("    estimatedAnnualRevenueUsd: ").append(toIndentedString(estimatedAnnualRevenueUsd)).append("\n");
    sb.append("    expectedMonthlyPaymentsUsd: ").append(toIndentedString(expectedMonthlyPaymentsUsd)).append("\n");
    sb.append("    operatesInProhibitedCountries: ").append(toIndentedString(operatesInProhibitedCountries)).append("\n");
    sb.append("    accountPurpose: ").append(toIndentedString(accountPurpose)).append("\n");
    sb.append("    accountPurposeOther: ").append(toIndentedString(accountPurposeOther)).append("\n");
    sb.append("    highRiskActivitiesExplanation: ").append(toIndentedString(highRiskActivitiesExplanation)).append("\n");
    sb.append("    highRiskActivities: ").append(toIndentedString(highRiskActivities)).append("\n");
    sb.append("    sourceOfFunds: ").append(toIndentedString(sourceOfFunds)).append("\n");
    sb.append("    sourceOfFundsDescription: ").append(toIndentedString(sourceOfFundsDescription)).append("\n");
    sb.append("    conductsMoneyServices: ").append(toIndentedString(conductsMoneyServices)).append("\n");
    sb.append("    conductsMoneyServicesUsingBridge: ").append(toIndentedString(conductsMoneyServicesUsingBridge)).append("\n");
    sb.append("    conductsMoneyServicesDescription: ").append(toIndentedString(conductsMoneyServicesDescription)).append("\n");
    sb.append("    identifyingInformation: ").append(toIndentedString(identifyingInformation)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    regulatedActivity: ").append(toIndentedString(regulatedActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

